#!/bin/bash

# Automatic test script master file

set -euo pipefail

cleanup()
{
	[ -z "${COOKIES:-}" ] || rm -f "$COOKIES"
}

trap cleanup EXIT

# parse command line options
export debug=0
export verbose=0

argv=()

for arg
do
	case "$arg" in
		--help)
			sed $'s/\\\\033/\033/g' <<-EOF

			Usage: \033[1;37m$(basename "${BASH_SOURCE[0]}")\033[m

			    --airportcity-stop-before=dd-HHMM
			        Stop airportcity test before "dd-HHMM".

			    --copy-scripts
			        Copy css/js into results.

			    --debug
			        Print what is being done.

			    --getflights-stop-at=dd-HHMM
			        Stop before getflights test at "dd-HHMM" after preparation.

			    --getflights-stop-before=dd-HHMM
			        Stop before getflights test "dd-HHMM" without preparation.

			    --help
			        Show this message.

			    --verbose
			        Print current test.

			EOF
			exit 0
			;;

		--airportcity-stop-before=*)
			airportcity_stop_before="${arg#*=}"
			;;

		--copy-scripts)
			copy_scripts=1
			;;

		-d|--debug)
			debug=1
			;;

		--getflights-stop-at=*)
			getflights_stop_at="${arg#*=}"
			;;

		--getflights-stop-before=*)
			getflights_stop_before="${arg#*=}"
			;;

		-v|--verbose)
			verbose=1
			;;

		*)
			argv+=("$arg")
			;;
	esac
done

set -- "${argv[@]}"

###############################################################################
# <preparation>
###############################################################################

readonly SCRIPTDIR=$(realpath "$(dirname "${BASH_SOURCE[0]}")")
declare -rx FRA_FLUGPLAN_HOST="${FRA_FLUGPLAN_HOST:-fra-flugplan.local}"
declare -rx url="https://$FRA_FLUGPLAN_HOST"

source "$SCRIPTDIR/functions.inc.sh"

chkdep readlink --version
chkdep minversion sed        "4.2.1"  "$(sed --version 2>&1 || echo | sed -nr '/^(GNU *)?sed/ { s/^[^0-9]*//g; /^$/d; p }')"
chkdep minversion awk        "4.1.1"  "$(awk --version 2>&1)" "||" \
       minversion mawk       "1.3.3"  "$(awk -W version 2>&1 || echo | sed -nr '/mawk/ { s/^[^0-9]*([^ ]+).*/\1/g; p }')"
chkdep minversion curl       "7.26.0" "$(curl --version 2>&1 || echo | sed -nr '/^curl/ { s/^[^0-9]*([^ ]+).*/\1/g; p }')"
chkdep minversion php        "5.4"    "$(curl -sSI "https://$FRA_FLUGPLAN_HOST/" | sed -n '/PHP\//{s#.*PHP/##g; s# .*$##g; p}')"
chkdep minversion mysql      "14.14"  "$(mysql --version 2>&1 || echo | sed -r 's/^[^0-9]*([^ ]+).*/\1/g')"
chkdep minversion jq         "1.5"    "$(jq --version 2>&1 || echo | sed 's/^[^0-9]*//g')"
chkdep minversion python     "2.7.3"  "$(python --version 2>&1 | sed 's/^[^0-9]*//g')"
chkdep minversion mailtodisk "1.0"    "$(mailtodisk --version 2>&1)"

mailtodisk --check ||
{
	echo "mailtodisk is not properly set up." >&2
	exit 1
}

declare -rx PRJDIR=$(git -C "$SCRIPTDIR" rev-parse --show-toplevel)
readonly DATADIR="${PRJDIR%%/htdocs/*}/htdocs/var/run/fra-flugplan"

mkdir -p "$SCRIPTDIR/results" "$DATADIR"

# Runways 18,99 in use
cat <<EOF > "$DATADIR/betriebsrichtung.ini"
18 = active
99 = active
EOF

export COOKIES=$(mktemp --suffix=.cookies)

###############################################################################
# </preparation>
###############################################################################

readarray -t testsuites < <(
	if [ $# -eq 0 ]; then
		find "$PRJDIR/tests/" -maxdepth 1 -type f -name "test_*.sh" -printf "%f\n" |
		sort -n |
		sed -r 's/test_(.+)\.sh$/\1/g'
	else
		# Get test base name and check for the presence of the testsuite file
		for file
		do
			[[ $file ]] || continue

			testsuite=$(basename "$file" ".sh")
			testsuite="${testsuite#test_}"

			if [ -r "$PRJDIR/tests/test_$testsuite.sh" ]; then
				echo "$testsuite"
			else
				echo -e "\033[31mCannot find 'test_$testsuite'.\033[m" >&2
				exit 1
			fi
		done
	fi
)

if [[ ${#testsuites[@]} -eq 0 ]]; then
	echo -e "\033[31mNo testsuites specified or no files found.\033[m" >&2
	exit 1
fi

status=0

for testsuite in "${testsuites[@]}"
do
	echo -en "\033[36m$testsuite\033[m " >&2

	# cleanup {

	expect="$SCRIPTDIR/expect/$testsuite"
	results="$SCRIPTDIR/results/$testsuite"

	rm -rf "$results" "$COOKIES"

	mailtodisk --remove '*'

	# }

	script="$SCRIPTDIR/test_$testsuite.sh"

	readarray -t testcases < <(
		sed -nr '/^test_/ { s/^([a-z0-9_]+).*$/\1/g; p }' "$script"
	)

	if [[ ${#testcases[@]} -eq 0 ]]; then
		echo -e "\033[31mTest suite '$testsuite'\033[m" >&2
		echo -e "\033[31mdoes not seem to contain any test cases.\033[m" >&2
		exit 1
	fi

	declare -A testcase_fileext=()
	declare -A testcase_mailto=()

	readarray -t decorators < <(
		awk 'BEGIN {
			o = 0
		}

		/^#\s*@@([a-z0-9_]+)=/ {
			opt = gensub(/^#\s*@@([^ \t\r\n]+)/, "\\1", "g", $0)
			eq = index(opt, "=")
			key = substr(opt, 0, eq - 1)
			value = substr(opt, eq)
			# print "fileext[ALL]=txt"
			print key "[ALL]" value
		}

		/^#\s*@([a-z0-9_]+)=/ {
			opts[o++] = gensub(/^#\s*@([^ \t\r\n]+)/, "\\1", "g", $0)
		}

		/^test_/ {
			for (i = 0; i < o; i++) {
				testcase = gensub(/^(test_[a-z0-9_]+).*$/, "\\1", "g", $0)
				eq = index(opts[i], "=")
				key = substr(opts[i], 0, eq - 1)
				value = substr(opts[i], eq)
				print key "[" testcase "]" value
			}

			o = 0
		}' "$script"
	)

	for decorator in "${decorators[@]}"
	do
		printf -v "testcase_${decorator%%=*}" "${decorator#*=}"
	done

	if [[ ${testcase_mailto[@]:-} ]]; then
		for mailto in "${testcase_mailto[@]}"
		do
			readarray -t -d, recipients < <(echo -n "$mailto")

			for recipient in "${recipients[@]}"
			do
				mailtodisk --add "$recipient" "$results/mail.txt"
			done
		done
	fi

	mkdir -p "$results"

	# drop/re-create database
	initdb

	defext="${testcase_fileext[ALL]:-htm}"

	if ! (
		source "$script"

		for testcase in "${testcases[@]}"
		do
			echo -n . >&2

			ext="${testcase_fileext[$testcase]:-${defext}}"

			"$testcase" > >(
				sed -r \
					-e "s#(https://|=)${FRA_FLUGPLAN_HOST}#\1fra-flugplan.de#g" \
					-e 's/\?rev=[0-9]*/?rev=$Rev$/g' > "$results/${testcase#test_}.${ext}"
			) 2>&1
		done

		echo
	)
	then
		echo -e "\033[31m ──> FAILED\033[m" >&2
		status=1
	else
		if [ -e "$results/mail.txt" ]; then
			# See user.php:
			#     http://www.outlookfaq.net/index.php?action=artikel&cat=6&id=84&artlang=de
			iconv -f iso-8859-1 -t utf-8 "$results/mail.txt" |
			strsubst RE_EMAIL > "$results/mail-utf-8.txt" &&
			mv "$results/mail-utf-8.txt" "$results/mail.txt"
		fi

		if [[ ${copy_scripts:-} ]]; then
			# Copy referenced scripts to properly view results
			cp -al "$PRJDIR/css" "$PRJDIR/img" "$PRJDIR/script" "$results"
		fi

		if ! diff=$(
			diff "$expect" "$results" \
				--brief \
				--recursive \
				--exclude=css \
				--exclude=img \
				--exclude=script
			)
		then
			echo -e "\033[31m└──> FAILED\033[m" >&2
			status=1
		fi
	fi
done

exit $status
