<?php

$lang_help = array(
	0 => '[Back to top]',
	1 => 'Help - Contents',
	2 => 'Basic usage',
	3 => 'Watchlist',
	4 => 'Defining a watchlist',
	5 => 'Sorting',
	6 => 'Sorting registrations',
	7 => 'Mobile devices',
	8 => 'Got trouble?',
	9 => '(1) Select whether you want to view arriving or departing flights',
	10 => '(2) In the headline this selection will be shown',
	11 => '(3) The <a href="http://en.wikipedia.org/wiki/Runways#Orientation_and_dimensions">runway(s) in operation</a> will be shown in the red box',
	12 => '(4) Flight times will be shown in format <span class="b">"+/-day hour:minutes"</span>, where +0 means today, +1 is tomorrow, and so on',
	13 => '(5) Premature flights are indicated by times in red',
	14 => '(6) Flights in the past will be grayed out',
	15 => '(7) Registrations are linked to <a href="http://www.airliners.net">www.airliners.net</a> (click on the icon to the left)',
	16 => '(8) Register/Login to benefit from the <span class="bi">watchlist</span> feature',
	17 => '(1) Let your favourite aircrafts be hilighted in green. A list thereof - including a comment per aircraft - will be stored within your user profile',
	18 => '(2) Click onto the watchlist tab or the link in the navigation area to let it slide into view. This list can be edited as you wish',
	19 => '<span class="b">The watchlist feature requires <span class="i"><a href="http://www.enable-javascript.com/">JavaScript to be enabled</a></span>.</span>',
	20 => 'Enter registration/comment pairs,',
	21 => '(1) use the Add button to add lines to the table',
	22 => '(2) You can also remove registrations if you do not want them ony your watchlist any longer',
	23 => '(3) Press Refresh to commit the changes',
	24 => 'Click one of the column headers to sort by a certain criteria',
	25 => 'If you are logged in and have defined a watchlist, the watched aircrafts will be sorted first',
	26 => 'For decent support of mobile devices there is still some work to do. Sorry. If you want support for a specific device/browser, do not hestitate to <a href="mailto:hausmeister(&auml;t)flederwiesel.com&subject=fra-schedule inquiry">send an inquiry</a><a href="#at"><sup style="font-style: italic;">[1]</sup></a>',
	27 => 'Software is never error-free. I tested this site as much as possible within the limits of my spare time. If you however, have trouble using the site or need further help than is provided here, feel free to <a href="mailto:hausmeister(&auml;t)flederwiesel.com&subject=fra-schedule trouble">Contact me</a><a href="#at"><sup style="font-style: italic;">[1]</sup></a>',
	28 => 'Contact: hausmeister(&auml;t)flederwiesel.com. Replace the (&auml;t) in the e-mail address with @',
);

?>
