#!/bin/bash

readonly VERSION=1.0

if [ $# -gt 0 ]; then
	case "$1" in
	-a|--add)
		shift
		receipient="$1"
		dest="$2"

		if [ -z "$receipient" ]; then
			echo "Please specify receipient." >&2
			exit 1
		else
			if [ -z "$dest" ]; then
				echo "Please specify destination for '$receipient'." >&2
				exit 1
			else
				echo "$dest" > "/etc/mailtodisk/$receipient"
			fi
		fi
		;;

	-c|--check)
		# Check whether mailtodisk is properly installed
		if ! stat=$(stat -c "%a %n" /etc/mailtodisk); then
			exit 2
		else
			read perm file <<< "$stat"

			if [ ! -d "$file" ]; then
				echo "$file is not a directory." >&2
				exit 1
			elif [ "$perm" != "777" ]; then
				echo "$file: $perm (must have 777)." >&2
				exit 3
			fi
		fi
		;;

	-h|--help)
		echo "$0"
		cat <<-EOF

		  -a --add     RECEIPIENT FILE
		  -c --check
		  -h --help
		  -i --install
		  -r --remove  RECEIPIENT FILE
		  -v --verbose

		Emails will be read from stdin and "receipents" used from the "To:" header field.

		If a known receipient is encountered (having been registered via --add), the mail
		content is written to the according file.

		Use --add/--remove to create/drop "mailboxes", i.e. to specify which file is used
		for certain receipients.

		Currently, only a single receipient per message is supported.

EOF
		;;

	-i|--install)
			if [ -d /etc/mailtodisk ]; then
				chmod 0777 /etc/mailtodisk
			else
				if [ -e /etc/mailtodisk ]; then
					if ! [ -d /etc/mailtodisk ]; then
						rm -rf /etc/mailtodisk
					fi
				fi

				if ! [ -d /etc/mailtodisk ]; then
					mkdir -m 777 /etc/mailtodisk
				fi
			fi
		;;

	-r|--remove)
		shift

		if [ -z "$1" ]; then
			echo "Please specify receipient." >&2
			exit 1
		else
			if [ "*" = "$1" ]; then
				rm -f "/etc/mailtodisk/"*
			else
				rm -f "/etc/mailtodisk/$1"
			fi
		fi
		;;
	-v|--version)
		echo "1.0"
		;;
	*)
		exit 0
		;;
	esac
else
	read line
	to=$(sed -r 's/^To: (.*<)?([^>]+)>?/\2/g; /[a-z0-9.-]+@[a-z0-9.-]+\.[a-z]+/!q1' <<<"$line")

	if [ $? -ne 0 ]; then
		# rubbish
		echo "Expected user@domain.tld, found \`$to\`." >&2
		exit 1
	else
		if [ ! -f "/etc/mailtodisk/$to" ]; then
			echo "No such mailbox: \`$to\`." >&2
			exit 2
		else
			file=$(cat "/etc/mailtodisk/$to")

			if [ -n "$file" ]; then
				dir=$(dirname "$file")

				if [ -d "$dir" ]; then
					(
						echo "Date: $(date --rfc-2822)"
						echo "$line"
						cat
						echo "======================================================"
					)>> "$file"
					line=
				fi
			fi
		fi
	fi
fi
