/******************************************************************************
 *
 * Copyright © Tobias Kühne
 *
 * You may use and distribute this software free of charge for non-commercial
 * purposes. The software must be distributed in its entirety, i.e. containing
 * ALL binary and source files without modification.
 * Publication of modified versions of the source code provided herein,
 * is permitted only with the author's written consent. In this case the
 * copyright notice must not be removed or altered, all modifications to the
 * source code must be clearly marked as such.
 *
 ******************************************************************************/

DROP DATABASE IF EXISTS `flederwiesel_fra-schedule`;

CREATE DATABASE `flederwiesel_fra-schedule` CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci';
USE `flederwiesel_fra-schedule`;

/******************************************************************************
 * Tables
 ******************************************************************************/

CREATE TABLE IF NOT EXISTS `users`
(
	`id` integer NOT NULL AUTO_INCREMENT,
	`email` varchar(255) NOT NULL,
	`name` varchar(64) NOT NULL,
	`salt` varchar(64) NOT NULL,
	`passwd` varchar(64) NOT NULL,
	`token` varchar(64) NULL DEFAULT NULL,
	`token_type` enum('none', 'activation', 'password') NOT NULL,
	`token_expires` timestamp NULL DEFAULT NULL,
	# ALTER TABLE `users` ADD COLUMN `last login` timestamp NULL DEFAULT NULL
	`last login` timestamp NULL DEFAULT NULL,
	`timezone` smallint DEFAULT 3600,
	`language` varchar(2) NOT NULL DEFAULT 'en',
	`ip` varchar(16) NOT NULL,	/* at the time of registration */
	`tm-` integer NOT NULL DEFAULT 0,
	`tm+` integer NOT NULL DEFAULT 3600,
	`tt-` integer NOT NULL DEFAULT 0,
	`tt+` integer NOT NULL DEFAULT 86400,
	`notification-from` time NOT NULL DEFAULT '00:00',
	`notification-until` time NOT NULL DEFAULT '00:00',
	# ALTER TABLE `users` ADD COLUMN `send mail` BOOL DEFAULT TRUE
	`send mail` BOOL DEFAULT TRUE,
	# ALTER TABLE `users` ADD COLUMN `notification-timefmt` varchar(24)
	`notification-timefmt` varchar(24) DEFAULT NULL,
	PRIMARY KEY (`id`),
	UNIQUE KEY `name` (`name`),
	UNIQUE KEY `email` (`email`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `groups`
(
	`id` integer NOT NULL AUTO_INCREMENT,
	`name` varchar(64) NOT NULL,
	`comment` varchar(64) DEFAULT NULL,
	PRIMARY KEY (`id`),
	UNIQUE KEY `name` (`name`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `membership`
(
	`user` integer NOT NULL,
	`group` integer NOT NULL,
	PRIMARY KEY(`user`, `group`),
	FOREIGN KEY(`user`) REFERENCES `users`(`id`),
	FOREIGN KEY(`group`) REFERENCES `groups`(`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `airlines`
(
	`id` integer NOT NULL AUTO_INCREMENT,
	`uid` integer NOT NULL,
	`code` varchar(3),
	`name` varchar(128),
	PRIMARY KEY (`id`),
	CONSTRAINT `unique: code` UNIQUE (`code`),
	FOREIGN KEY(`uid`) REFERENCES `users`(`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `models`
(
	`id` integer NOT NULL AUTO_INCREMENT,
	`uid` integer NOT NULL,
	`icao` varchar(4) NOT NULL,
	`name` varchar(96) NOT NULL,
	PRIMARY KEY (`id`),
	CONSTRAINT `unique:icao` UNIQUE (`icao`),
	FOREIGN KEY(`uid`) REFERENCES `users`(`id`)
) COMMENT = 'http://www.airlinecodes.co.uk'
ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `aircrafts`
(
	`id` integer NOT NULL AUTO_INCREMENT,
	`uid` integer NOT NULL,
	`reg` varchar(8) NOT NULL,
	`model` integer NOT NULL,
	PRIMARY KEY (`id`),
	CONSTRAINT `unique:reg` UNIQUE (`reg`),
	FOREIGN KEY(`uid`) REFERENCES `users`(`id`),
	FOREIGN KEY(`model`) REFERENCES `models`(`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `airports`
(
	`id` integer NOT NULL AUTO_INCREMENT,
	`uid` integer NOT NULL,
	`iata` varchar(3) NULL,
	`icao` varchar(4) NOT NULL,
	`name` varchar(255) NOT NULL,
	PRIMARY KEY (`id`),
	CONSTRAINT `unique:icao` UNIQUE(`icao`),
	FOREIGN KEY(`uid`) REFERENCES `users`(`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `flights`
(
	`id` integer NOT NULL AUTO_INCREMENT,
	`uid` integer NOT NULL,
	`type` enum('P', 'F', 'C') NOT NULL DEFAULT 'P',
	`direction` enum('arrival', 'departure') NOT NULL,
	`airline` integer NOT NULL,
	`code` varchar(6) NOT NULL,
	`scheduled` datetime NOT NULL,
	`expected` timestamp NULL DEFAULT NULL,
	`airport` integer DEFAULT NULL,
	`model` integer DEFAULT NULL,
	`aircraft` integer DEFAULT NULL,
	`last update` timestamp NULL,
	PRIMARY KEY (`id`),
	CONSTRAINT `unique:direction, airline, code, scheduled` UNIQUE (`direction`, `airline`, `code`, `scheduled`),
	FOREIGN KEY(`uid`) REFERENCES `users`(`id`),
	FOREIGN KEY(`airline`) REFERENCES `airlines`(`id`),
	FOREIGN KEY(`airport`) REFERENCES `airports`(`id`),
	FOREIGN KEY(`model`) REFERENCES `models`(`id`),
	FOREIGN KEY(`aircraft`) REFERENCES `aircrafts`(`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

/* Copy `flights` table structure (including indices!) */
CREATE TABLE IF NOT EXISTS `history` LIKE `flights`;

/* Remove AUTO_INCREMENT */
ALTER TABLE `history` AUTO_INCREMENT = 0;

/* Count visits to FRA */
CREATE TABLE IF NOT EXISTS `visits`
(
	`aircraft` integer NOT NULL,
	`num` integer NOT NULL,
	`current` datetime NOT NULL,
	`previous` datetime DEFAULT NULL,
	PRIMARY KEY (`aircraft`),
	FOREIGN KEY(`aircraft`) REFERENCES `aircrafts`(`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `watchlist`
(
	`id` integer NOT NULL AUTO_INCREMENT,
	`user` int(11) NOT NULL,
	`notify` bool DEFAULT FALSE,
	# ALTER TABLE `watchlist` MODIFY `reg` varchar(31)
	`reg` varchar(31) NOT NULL,
	`comment` varchar(255) DEFAULT NULL,
	PRIMARY KEY (`id`),
	UNIQUE KEY `user, reg` (`user`, `reg`),
	FOREIGN KEY(`user`) REFERENCES `users`(`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `watchlist-notifications`
(
	`id` integer NOT NULL AUTO_INCREMENT,
	`watch` integer NOT NULL,
	`flight` integer NOT NULL,
	`notified` datetime DEFAULT NULL,
	PRIMARY KEY(`id`),
	UNIQUE KEY(`watch`, `flight`),
	FOREIGN KEY(`watch`) REFERENCES `watchlist`(`id`),
	FOREIGN KEY(`flight`) REFERENCES `flights`(`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

/******************************************************************************
 * Indices
 ******************************************************************************/

CREATE INDEX `airlines:uid` ON `airlines`(`uid` ASC);
CREATE INDEX `models:uid` ON `models`(`uid` ASC);
CREATE INDEX `aircrafts:uid` ON `aircrafts`(`uid` ASC);
CREATE INDEX `airports:uid` ON `airports`(`uid` ASC);
CREATE INDEX `flights:uid` ON `flights`(`uid` ASC);
CREATE INDEX `flights:scheduled` ON `flights`(`scheduled` ASC);
CREATE INDEX `flights:code` ON `flights`(`code` ASC);
CREATE INDEX `flights:direction` ON `flights`(`direction` ASC);
CREATE INDEX `history:uid` ON `history`(`uid` ASC);
CREATE INDEX `history:scheduled` ON `history`(`scheduled` ASC);
CREATE INDEX `history:code` ON `history`(`code` ASC);
CREATE INDEX `history:direction` ON `history`(`direction` ASC);
CREATE INDEX `watchlist:user` ON `watchlist`(`user` ASC);
CREATE INDEX `watchlist:reg` ON `watchlist`(`reg` ASC);
CREATE INDEX `visits:aircraft` ON `visits`(`aircraft` ASC);
CREATE INDEX `visits:current` ON `visits`(`current` ASC);
CREATE INDEX `membership:user` ON `membership`(`user` ASC);
CREATE INDEX `membership:group` ON `membership`(`group` ASC);

/******************************************************************************
 * Data
 ******************************************************************************/

INSERT INTO `groups`(`name`, `comment`)
VALUES
('admin',      NULL),
('users',      NULL),
('addflights', NULL),
('specials',   NULL);

INSERT INTO `users`(`name`, `email`, `salt`, `passwd`, `language`)
VALUES
(
	'root',
	'flederwiesel@fra-flugplan.de',
	'cf78aafd5c5410b7b12c2794a52cda1bccd01316f30df57aa29c5609ba979c15',
	'c4ae99aa0209ce5bea9687cf0548d8ebc942ba14e166c45957a876bcec194fed',
	'en'
);

SELECT LAST_INSERT_ID() INTO @root;

INSERT INTO `membership`(`user`, `group`)
(
	SELECT @root AS `user`, `id` AS `group`
	FROM `groups`
	WHERE `name` IN ('admin', 'addflights', 'specials', 'users')
);

INSERT INTO `airlines`(`uid`, `code`, `name`)
VALUES
(@root, 'A3',  'Aegean Airlines'),
(@root, 'AA',  'American Airlines'),
(@root, 'AB',  'Airberlin'),
(@root, 'AC',  'Air Canada'),
(@root, 'AEE', 'Aegean Airlines'),
(@root, 'AF',  'Air France'),
(@root, 'AH',  'Air Algerie'),
(@root, 'AI',  'Air India'),
(@root, 'AP',  'Air One'),
(@root, 'AT',  'Royal Air Maroc'),
(@root, 'AY',  'Finnair'),
(@root, 'AZ',  'Alitalia'),
(@root, 'BA',  'British Airways'),
(@root, 'BD',  'British Midland International'),
(@root, 'BE',  'Flybe'),
(@root, 'BPA', 'Blue Panorama Airlines'),
(@root, 'BRU', 'Belavia'),
(@root, 'BT',  'Air Baltic'),
(@root, 'BUC', 'Bulgarian Air Charter'),
(@root, 'CA',  'Air China'),
(@root, 'CAI', 'Corendon Airlines'),
(@root, 'CFE', 'BA CityFlyer'),
(@root, 'CI',  'China Airlines'),
(@root, 'CX',  'Cathay Pacific Airways'),
(@root, 'CY',  'Cyprus Airways'),
(@root, 'DE',  'Condor'),
(@root, 'DL',  'Delta Air Lines'),
(@root, 'DLN', 'Dalmatian'),
(@root, 'EI',  'Aer Lingus'),
(@root, 'EK',  'Emirates'),
(@root, 'EN',  'Air Dolomiti'),
(@root, 'ERT', 'Eritrean Airlines'),
(@root, 'ET',  'Ethiopian Airlines'),
(@root, 'EY',  'Etihad Airways'),
(@root, 'FB',  'Bulgaria Air'),
(@root, 'FHY', 'Freebird Airlines'),
(@root, 'FI',  'Icelandair'),
(@root, 'FV',  'Rossiya'),
(@root, 'GF',  'Gulf Air'),
(@root, 'GH',  'Globus'),
(@root, 'GHY', 'German Sky Airlines '),
(@root, 'GWI', 'Germanwings'),
(@root, 'GXL', 'XL Airways Germany'),
(@root, 'HCC', 'Holidays Czech Airlines'),
(@root, 'HG',  'NIKI'),
(@root, 'HY',  'Uzbekistan Airways'),
(@root, 'IB',  'Iberia'),
(@root, 'IR',  'Iran Air'),
(@root, 'IY',  'Yemenia Yemen Airways'),
(@root, 'IZ',  'Arkia Israel Airlines'),
(@root, 'JA',  'B&H Airlines'),
(@root, 'JFU', 'Jet4you'),
(@root, 'JJ',  'TAM Linhas Aéreas'),
(@root, 'JL',  'JAL Japan Airlines'),
#(@root, 'JU',  'JAT Airways'),
(@root, 'JU', 'Air Serbia'),
(@root, 'KC',  'Air Astana'),
(@root, 'KE',  'Korean Air'),
(@root, 'KIL', 'Kuban Airlines'),
(@root, 'KK',  'Atlasjet Airlines'),
(@root, 'KL',  'KLM Royal Dutch Airlines'),
(@root, 'KM',  'Air Malta'),
(@root, 'KRP', 'Carpatair'),
(@root, 'KU',  'Kuwait Airways'),
(@root, 'LA',  'LAN Airlines'),
(@root, 'LBT', 'Nouvelair Tunisie'),
(@root, 'LG',  'Luxair'),
(@root, 'LH',  'Lufthansa'),
(@root, 'LO',  'LOT Polish Airlines'),
(@root, 'LV',  'Albanian Airlines'),
(@root, 'LX',  'Swiss International Air Lines'),
(@root, 'LY',  'El Al Israel Airlines'),
(@root, 'ME',  'MEA Middle East Airlines'),
(@root, 'MH',  'Malaysia Airlines'),
(@root, 'MHK', 'Alnaser Airlines'),
(@root, 'MK',  'Air Mauritius'),
(@root, 'MLD', 'Air Moldova'),
(@root, 'MS',  'Egypt Air'),
(@root, 'MSC', 'Air Cairo'),
(@root, 'MU',  'China Eastern Airlines'),
(@root, 'NH',  'ANA'),
(@root, 'OK',  'CSA Czech Airlines'),
(@root, 'OLT', 'OLT Express'),
(@root, 'OM',  'MIAT Mongolian Airlines'),
(@root, 'OS',  'Austrian Airlines Group'),
(@root, 'OU',  'Croatia Airlines'),
(@root, 'OZ',  'Asiana Airlines'),
(@root, 'PGT', 'Pegasus Airlines'),
(@root, 'PHW', 'Ave.com'),
(@root, 'PK',  'PIA Pakistan International Airlines'),
(@root, 'PS',  'Ukraine International Airlines'),
(@root, 'QB',  'Sky Georgia'),
(@root, 'QF',  'Qantas Airways'),
(@root, 'QR',  'Qatar Airways'),
(@root, 'RB',  'Syrianair'),
(@root, 'RJ',  'Royal Jordanian'),
(@root, 'RKM', 'RAK Airways'),
(@root, 'RNV', 'Armavia'),
(@root, 'RO',  'Tarom'),
(@root, 'SA',  'South African Airways'),
(@root, 'SBI', 'S7 Airlines'),
(@root, 'SK',  'SAS Scandinavian Airlines'),
(@root, 'SMR', 'Somon Air'),
(@root, 'SOV', 'Saravia-Saratov Airlines'),
(@root, 'SP',  'SATA Internacional'),
(@root, 'SQ',  'Singapore Airlines'),
(@root, 'SU',  'Aeroflot'),
(@root, 'SUW', 'Sunny Airways'),
(@root, 'SV',  'Saudi Arabian Airlines'),
(@root, 'SW',  'Air Namibia'),
(@root, 'TG',  'Thai Airways International'),
(@root, 'TGZ', 'Georgian Airways'),
(@root, 'TK',  'Turkish Airlines'),
(@root, 'TP',  'TAP Portugal'),
(@root, 'TRK', 'Turkuaz Airlines'),
(@root, 'TS',  'Air Transat'),
(@root, 'TU',  'Tunis Air'),
(@root, 'TUA', 'Turkmenistan Airlines'),
(@root, 'TUI', 'TUIfly'),
(@root, 'TWI', 'Tailwind Havayollari'),
(@root, 'UA',  'United Airlines'),
(@root, 'UDN', 'Dniproavia'),
(@root, 'UL',  'Srilankan Airlines'),
(@root, 'UN',  'Transaero Airlines'),
(@root, 'US',  'US Airways'),
(@root, 'VIM', 'Air VIA Bulgarian'),
(@root, 'VLM', 'VLM Airlines'),
(@root, 'VN',  'Vietnam Airlines'),
(@root, 'VQ',  'FlyHellas.com'),
(@root, 'WY',  'Oman Air'),
(@root, 'X3',  'TUIfly'),
(@root, 'XG',  'SunExpress Deutschland'),
(@root, 'XQ',  'SunExpress'),
(@root, 'YM',  'Montenegro Airlines'),
(@root, 'ZY',  'Sky Airlines'),
(@root, 'ZZ',  'ZZ'),
(@root, 'JP',  'Adria Airways'),
(@root, 'HU',  'Hainan Airlines'),
(@root, 'ST',  'Germania'),
(@root, 'EW',  'Eurowings'),
(@root, '4U',  'Germanwings'),
(@root, 'EZE', 'Eastern Airways'),
(@root, 'MON', 'Monarch Airlines'),
(@root, 'IFA', 'FAI Airservice'),
(@root, 'BV',  'Blue Panorama Airlines'),
(@root, 'TFL', 'Arkefly'),
(@root, 'AEY', 'Air Italy'),
(@root, 'DWT', 'Darwin Airline'),
(@root, 'YW',  'Air Nostrum'),
(@root, 'OHY', 'Onur Air'),
(@root, 'FPO', 'Europe Airpost'),
(@root, 'JTG', 'Jet Time'),
(@root, 'EXS', 'Jet2.com'),
(@root, 'HAY', 'Hamburg Airways'),
(@root, 'EZ',  'Evergreen International Airlines'),
(@root, 'HV',  'Transavia Airlines'),
(@root, 'VPA', 'VIP Wings'),
(@root, 'JAF', 'JetAirFly'),
(@root, 'BO',  'Aerologic'),
(@root, 'BOX', 'Aerologic'),
(@root, 'UC',  'LAN Cargo'),
(@root, 'ACX', 'ACG Air Cargo Germany'),
(@root, 'BR',  'EVA Air'),
(@root, 'ABW', 'AirBridgeCargo'),
(@root, 'FX',  'FedEx'),
(@root, 'RGN', 'Cygnus Air'),
(@root, 'CZ',  'China Southern Airlines'),
(@root, 'ABR', 'Air Bridge Carriers'),
(@root, 'AHO', 'Air Hamburg'),
(@root, 'CSA', 'Czech Airlines'),
(@root, 'DLH', 'Lufthansa'),
(@root, 'ETD', 'Etihad Airways'),
(@root, 'EXH', 'Executive AG'),
(@root, 'EXT', 'Nightexpress'),
(@root, 'FFD', 'Stuttgarter Flugdienst'),
(@root, 'FMY', 'Aviation Legere de l\'Armee de Terre'),
(@root, 'IAM', 'Aeronautica Militare Italiana'),
(@root, 'JEI', 'Jet Executive International Charter'),
(@root, 'KAC', 'Kuwait Airways'),
(@root, 'KZR', 'Air Astana'),
(@root, 'LNX', 'London Executive Aviation - LEA'),
(@root, 'LZB', 'Bulgaria Air'),
(@root, 'MAS', 'Malaysia Airlines'),
(@root, 'MGR', 'Magna Air'),
(@root, 'NJE', 'NetJets Transportes Aereos'),
(@root, 'QAJ', 'Quick Air Jet Charter'),
(@root, 'RZO', 'SATA Internacional'),
(@root, 'SHY', 'Sky Airlines'),
(@root, 'THY', 'Turkish Airlines'),
(@root, 'AFL', 'Aeroflot'),
(@root, 'AZG', 'Sakaviaservice'),
(@root, 'CMB', 'US Transportation Command'),
(@root, 'GTI', 'Atlas Air'),
(@root, 'MNB', 'MNG Airlines'),
(@root, 'YZR', 'Yangtze River Express Airlines'),
(@root, 'AG',  'Affretair'),
(@root, 'FRA', 'FR Aviation'),
(@root, 'OAW', 'Helvetic'),
(@root, 'AEA', 'Air Europa'),
(@root, 'QS',  'Travel Servis/Smartwings'),
(@root, 'BIE', 'Air Mediterranee'),
(@root, 'I2',  'Iberia Express'),
(@root, 'HC',  'Aero Tropics'),
(@root, 'BM',  'BMI regional'),
(@root, 'FQ',  'Thomas Cook Belgium Airlines'),
(@root, 'IQ',  'Augsburg Airways'),
(@root, 'ZZZ', 'ZZZ'),
(@root, 'SWT', 'Swiftair'),
(@root, 'XLF', 'XL Airways France'),
(@root, 'FC',  'Flybe Nordic'),
(@root, 'KZ',  'Nippon Cargo Airlines'),
(@root, 'WDL', 'WDL Aviation'),
(@root, 'VLG', 'Vueling'),
(@root, 'VY',  'Vueling Airlines'),
(@root, 'S4',  'SATA International'),
(@root, 'IA',  'Iraqi Airways'),
(@root, 'AHY', 'Azerbaijan Airlines'),
(@root, 'SZ',  'Somon Air'),
(@root, 'UT',  'UTAir'),
(@root, 'TDR', 'Trade Air'),
(@root, 'QY',  'DHL'),
(@root, 'TF',  'Malmö Aviation'),
(@root, 'RU',  'Air Brigde Cargo'),
(@root, 'AWC', 'Titan Airways'),
(@root, 'MT',  'Thomas Cook Airlines'),
(@root, 'OAE', 'Omni Air International'),
(@root, 'RC',  'Atlantic Airways'),
(@root, 'CLJ', 'Cello Aviation'),
(@root, 'YY',  'YY'),
(@root, 'WX',  'CityJet'),
(@root, '6G',  'Go2Sky'),
(@root, 'AXE', 'AirExplore'),
(@root, 'HFY', 'Hi Fly'),
(@root, 'LAV', 'Alba Star'),
(@root, 'PVG', 'Privilege Style'),
(@root, 'PC',  'Pegasus Hava Tasimaciligi'),
(@root, 'ISK', 'Intersky'),
(@root, 'ENT', 'Enter Air'),
(@root, 'A6',  'Air Alps'),
(@root, '9Y',  'FlyGeorgia'),
(@root, '6W',  'Saratov Airlines'),
(@root, 'A9',  'Air Zena'),
(@root, 'DTR', 'Danish Air Transport'),
(@root, 'NJ',  'Nordic Global Airlines'),
(@root, 'ORB', 'Oren Air'),
(@root, 'EZY', 'easyJet'),
(@root, 'BG',  'Biman Bangladesh Airlines'),
(@root, 'UX',  'Air Europa'),
(@root, 'CKS', 'Kalitta Air'),
(@root, 'HQ',  'Thomas Cook Airlines Belgium'),
(@root, 'SRK', 'SkyWork Airlines'),
(@root, 'DNM', 'Denim Air'),
(@root, 'DK',  'Thomas Cook Airlines Scandinavia'),
(@root, 'DY',  'Norwegian Air Shuttle'),
(@root, 'WLC', 'Welcome Air'),
(@root, 'SN',  'Brussels Airlines'),
(@root, 'ISR', 'Israir Airlines'),
(@root, 'AIB', 'Airbus Industrie'),
(@root, 'NMA', 'Nesma Airlines'),
(@root, 'AJD', 'flyVista'),
(@root, 'QN',  'Air Armenia'),
(@root, 'V7',  'Volotea'),
(@root, 'OV',  'Estonian Air'),
(@root, 'OR',  'Arkefly'),
(@root, '8Q',  'Onur Air'),
(@root, 'AAB', 'Abelag Aviation'),
(@root, 'AV',  'Avianca'),
(@root, 'GA',  'Garuda Indonesia'),
(@root, 'HM',  'Air Seychelles'),
(@root, 'JAI', 'Jet Airways'),
(@root, 'LPV', 'Air Alps Aviation'),
(@root, 'NZ',  'Air New Zealand'),
(@root, 'TUL', 'Tulpar Air'),
(@root, 'HRM', 'Hermes Airlines'),
(@root, '7W',  'Wind Rose Aviation'),
(@root, '3O', 'Air Arabia Maroc'),
(@root, 'B2', 'Belavia Airlines'),
(@root, 'BCS', 'EAT-European Air Transport'),
(@root, 'CC', 'Air Atlanta Icelandic');

INSERT INTO `models`(`uid`, `id`, `icao`, `name`)
VALUES
(@root,   1, 'A124', 'Antonov AN-124 Ruslan'),
(@root,   2, 'A140', 'Antonov AN-140'),
(@root,   3, 'A148', 'Antonov AN-148'),
(@root,   4, 'A306', 'Airbus Industrie A300-600'),
(@root,   5, 'A30B', 'Airbus Industrie A300B2/B4/C4/F4'),
(@root,   6, 'A310', 'Airbus A310'),
(@root,   7, 'A318', 'Airbus A318'),
(@root,   8, 'A319', 'Airbus A319'),
(@root,   9, 'A320', 'Airbus A320-100/200'),
(@root,  10, 'A32A', 'Airbus A320-100/200 (Sharklets)'),
(@root,  11, 'A321', 'Airbus A321-100/200'),
(@root,  12, 'A330', 'Airbus A330 all models'),
(@root,  13, 'A332', 'Airbus A330-200'),
(@root,  14, 'A333', 'Airbus A330-300'),
(@root,  15, 'A340', 'Airbus A340 all models'),
(@root,  16, 'A342', 'Airbus A340-200'),
(@root,  17, 'A343', 'Airbus A340-300'),
(@root,  18, 'A345', 'Airbus A340-500'),
(@root,  19, 'A346', 'Airbus A340-600'),
(@root,  20, 'A388', 'Airbus A380-800'),
(@root,  21, 'A3ST', 'Airbus Industrie A300-600ST Beluga Freighter'),
(@root,  22, 'A748', 'Hawker Siddeley HS.748'),
(@root,  23, 'AC68', 'Gulfstream/Rockwell (Aero) Commander'),
(@root,  24, 'AC90', 'Gulfstream/Rockwell (Aero) Turbo Commander'),
(@root,  25, 'AN12', 'Antonov AN-12'),
(@root,  26, 'AN24', 'Antonov AN-24'),
(@root,  27, 'AN26', 'Antonov AN-26'),
(@root,  28, 'AN28', 'Antonov AN-28 / PZL Miele M-28 Skytruck'),
(@root,  29, 'AN30', 'Antonov AN-30'),
(@root,  30, 'AN32', 'Antonov AN-32'),
(@root,  31, 'AN72', 'Antonov AN-72 / AN-74'),
(@root,  32, 'AT43', 'Aerospatiale/Alenia ATR 42-300 / 320'),
(@root,  33, 'AT45', 'Aerospatiale/Alenia ATR 42-500'),
(@root,  34, 'AT72', 'Aerospatiale/Alenia ATR 72-200/210'),
(@root,  35, 'ATP', 'British Aerospace ATP'),
(@root,  36, 'B190', 'Beechcraft 1900/1900C/1900D'),
(@root,  37, 'B461', 'BAe 146-100'),
(@root,  38, 'B462', 'BAe 146-200'),
(@root,  39, 'B463', 'BAe 146-300'),
(@root,  40, 'B703', 'Boeing 707-300'),
(@root,  41, 'B712', 'Boeing 717'),
(@root,  42, 'B720', 'Boeing 720B'),
(@root,  43, 'B721', 'Boeing 727-100'),
(@root,  44, 'B722', 'Boeing 727-200'),
(@root,  45, 'B731', 'Boeing 737-100'),
(@root,  46, 'B732', 'Boeing 737-200'),
(@root,  47, 'B733', 'Boeing 737-300'),
(@root,  48, 'B734', 'Boeing 737-400'),
(@root,  49, 'B735', 'Boeing 737-500'),
(@root,  50, 'B736', 'Boeing 737-600'),
(@root,  51, 'B737', 'Boeing 737-700'),
(@root,  52, 'B738', 'Boeing 737-800'),
(@root,  53, 'B739', 'Boeing 737-900'),
(@root,  54, 'B741', 'Boeing 747-100'),
(@root,  55, 'B742', 'Boeing 747-200'),
(@root,  56, 'B743', 'Boeing 747-300'),
(@root,  57, 'B744', 'Boeing 747-400'),
(@root,  58, 'B748', 'Boeing 747-8I'),
(@root,  59, 'B74R', 'Boeing 747SR'),
(@root,  60, 'B752', 'Boeing 757-200'),
(@root,  61, 'B753', 'Boeing 757-300'),
(@root,  62, 'B762', 'Boeing 767-200'),
(@root,  63, 'B763', 'Boeing 767-300'),
(@root,  64, 'B764', 'Boeing 767-400'),
(@root,  65, 'B772', 'Boeing 777-200'),
(@root,  66, 'B773', 'Boeing 777-300'),
(@root,  67, 'B77L', 'Boeing 777-200LR'),
(@root,  68, 'B77W', 'Boeing 777-300ER'),
(@root,  69, 'B788', 'Boeing 787 "Dreamliner"'),
(@root,  70, 'BA11', 'British Aerospace (BAC) One Eleven'),
(@root,  71, 'BELF', 'Shorts SC-5 Belfast'),
(@root,  72, 'BN2P', 'Pilatus Britten-Norman BN-2A/B Islander'),
(@root,  73, 'C130', 'Lockheed L-182 / 282 / 382 (L-100) Hercules'),
(@root,  74, 'C212', 'CASA / IPTN 212 Aviocar'),
(@root,  75, 'C46', 'Curtiss C-46 Commando'),
(@root,  76, 'CL44', 'Canadair CL-44'),
(@root,  77, 'CL60', 'Canadair Challenger'),
(@root,  78, 'CN35', 'CASA / IPTN CN-235'),
(@root,  79, 'CONC', 'Aerospatiale/BAC Concorde'),
(@root,  80, 'CONI', 'Lockheed L-1049 Super Constellation'),
(@root,  81, 'COUC', 'Helio H-250 Courier / H-295 / 385 Super Courier'),
(@root,  82, 'CRJ1', 'Canadair Regional Jet 100'),
(@root,  83, 'CRJ2', 'Canadair Regional Jet 200'),
(@root,  84, 'CRJ7', 'Canadair Regional Jet 700'),
(@root,  85, 'CRJ9', 'Canadair Regional Jet 900'),
(@root,  86, 'CVLP', 'Convair CV-240/440'),
(@root,  87, 'CVLT', 'Convair CV-580/600/640'),
(@root,  88, 'D228', 'Fairchild Dornier Do.228'),
(@root,  89, 'D328', 'Fairchild Dornier Do.328'),
(@root,  90, 'DC10', 'Douglas DC-10'),
(@root,  91, 'DC3', 'Douglas DC-3'),
(@root,  92, 'DC6', 'Douglas DC6A/B/C'),
(@root,  93, 'DC85', 'Douglas DC-8-50 Freighter'),
(@root,  94, 'DC86', 'Douglas DC-8-62'),
(@root,  95, 'DC87', 'Douglas DC-8-71/72/73'),
(@root,  96, 'DC9', 'Douglas DC-9 all models'),
(@root,  97, 'DC91', 'Douglas DC-9-10'),
(@root,  98, 'DC92', 'Douglas DC-9-20'),
(@root,  99, 'DC93', 'Douglas DC-9-30'),
(@root, 100, 'DC94', 'Douglas DC-9-40'),
(@root, 101, 'DC95', 'Douglas DC-9-50'),
(@root, 102, 'DH2T', 'De Havilland Canada DHC-2 Turbo-Beaver'),
(@root, 103, 'DH8A', 'De Havilland Canada DHC-8-100 Dash 8 / 8Q'),
(@root, 104, 'DH8B', 'De Havilland Canada DHC-8-200 Dash 8 / 8Q'),
(@root, 105, 'DH8C', 'De Havilland Canada DHC-8-300 Dash 8 / 8Q'),
(@root, 106, 'DH8D', 'De Havilland Canada DHC-8-400 Dash 8Q'),
(@root, 107, 'DHC2', 'De Havilland Canada DHC-2 Beaver'),
(@root, 108, 'DHC3', 'De Havilland Canada DHC-3 Otter / Turbo Otter'),
(@root, 109, 'DHC4', 'De Havilland Canada DHC-4 Caribou'),
(@root, 110, 'DHC6', 'De Havilland Canada DHC-6 Twin Otter'),
(@root, 111, 'DHC7', 'De Havilland Canada DHC-7 Dash 7'),
(@root, 112, 'DOVE', 'De Havilland DH.104 Dove'),
(@root, 113, 'E110', 'Embraer EMB.110 Bandeirnate'),
(@root, 114, 'E120', 'Embraer EMB.120 Brasilia'),
(@root, 115, 'E135', 'Embraer RJ135'),
(@root, 116, 'E145', 'Embraer RJ145 Amazon'),
(@root, 117, 'E170', 'Embraer 170'),
(@root, 118, 'E190', 'Embraer 190'),
(@root, 119, 'F100', 'Fokker 100'),
(@root, 120, 'F27', 'Fokker F.27 Friendship / Fairchild F.27'),
(@root, 121, 'F28', 'Fokker F.28 Fellowship'),
(@root, 122, 'F50', 'Fokker 50'),
(@root, 123, 'F70', 'Fokker 70'),
(@root, 124, 'G159', 'Gulfstream Aerospace G-159 Gulfstream I'),
(@root, 125, 'G21', 'Grumman G.21 Goose'),
(@root, 126, 'G73T', 'Grumman G.73 Turbo Mallard'),
(@root, 127, 'GLEX', 'Canadair Global Express'),
(@root, 128, 'HERN', 'De Havilland DH.114 Heron'),
(@root, 129, 'I114', 'Ilyushin IL114'),
(@root, 130, 'IL18', 'Ilyushin IL18'),
(@root, 131, 'IL62', 'Ilyushin IL62'),
(@root, 132, 'IL76', 'Ilyushin IL76'),
(@root, 133, 'IL86', 'Ilyushin IL86'),
(@root, 134, 'IL96', 'Ilyushin IL96'),
(@root, 135, 'J328', 'Fairchild Dornier 328JET'),
(@root, 136, 'JS31', 'British Aerospace Jetstream 31'),
(@root, 137, 'JS32', 'British Aerospace Jetstream 32'),
(@root, 138, 'JS41', 'British Aerospace Jetstream 41'),
(@root, 139, 'JU52', 'Junkers Ju52/3M'),
(@root, 140, 'L101', 'Lockheed L-1011 1 / 50 / 100 / 150 / 200 / 250 Tristar'),
(@root, 141, 'L188', 'Lockheed L-188 Electra'),
(@root, 142, 'L410', 'LET 410'),
(@root, 143, 'LOAD', 'Ayres LM-200 Loadmaster'),
(@root, 144, 'MD11', 'McDonnell Douglas MD11'),
(@root, 145, 'MD80', 'McDonnell Douglas MD80'),
(@root, 146, 'MD81', 'McDonnell Douglas MD81'),
(@root, 147, 'MD82', 'McDonnell Douglas MD82'),
(@root, 148, 'MD83', 'McDonnell Douglas MD83'),
(@root, 149, 'MD87', 'McDonnell Douglas MD87'),
(@root, 150, 'MD88', 'McDonnell Douglas MD88'),
(@root, 151, 'MD90', 'McDonnell Douglas MD90'),
(@root, 152, 'MU2', 'Mitsubishi Mu-2'),
(@root, 153, 'N262', 'Aerospatiale (Nord) 262'),
(@root, 154, 'N74S', 'Boeing 747SP'),
(@root, 155, 'NOMA', 'Government Aircraft Factories N22B / N24A Nomad'),
(@root, 156, 'P68', 'Partenavia P.68'),
(@root, 157, 'PC12', 'Pilatus PC-12'),
(@root, 158, 'PC6T', 'Pilatus PC-6 Turbo Porter'),
(@root, 159, 'RJ1H', 'Avro RJ100 Avroliner'),
(@root, 160, 'RJ70', 'Avro RJ70 Avroliner'),
(@root, 161, 'RJ85', 'Avro RJ85 Avroliner'),
(@root, 162, 'RX1H', 'Avro RJX100'),
(@root, 163, 'RX85', 'Avro RJX85 	M B11 	BA11 	British Aerospace (BAC) One Eleven / RomBAC One Eleven'),
(@root, 164, 'S210', 'Aerospatiale (Sud Aviation) Se.210 Caravelle'),
(@root, 165, 'S601', 'Aerospatiale SN.601 Corvette'),
(@root, 166, 'SB20', 'Saab 2000'),
(@root, 167, 'SC7', 'Shorts SC-7 Skyvan'),
(@root, 168, 'SF34', 'Saab SF340A/B'),
(@root, 169, 'SH33', 'Shorts SD.330'),
(@root, 170, 'SH36', 'Shorts SD.360'),
(@root, 171, 'T134', 'Tupolev Tu134'),
(@root, 172, 'T154', 'Tupolev Tu154'),
(@root, 173, 'T204', 'Tupolev Tu-204 / Tu-214'),
(@root, 174, 'TRIS', 'Pilatus Britten-Norman BN-2A Mk III Trislander'),
(@root, 175, 'VISC', 'Vickers Viscount'),
(@root, 176, 'WW24', 'Israel Aircraft Industries 1124 Westwind'),
(@root, 177, 'Y12', 'Harbin Yunshuji Y12'),
(@root, 178, 'YK40', 'Yakovlev Yak 40'),
(@root, 179, 'YK42', 'Yakovlev Yak 42'),
(@root, 180, 'YS11', 'NAMC YS-11'),
(@root, 181, 'AT75', 'Aerospatiale/Alenia ATR 72-500'),
(@root, 182, 'AT76', 'Aerospatiale/Alenia ATR 72-600'),
(@root, 183, 'CRJX', 'Canadair Regional Jet 1000'),
(@root, 184, 'AT73', 'Aerospatiale/Alenia ATR72-200'),
(@root, 187, 'GLF4', 'Gulfstream 4'),
(@root, 188, 'H25B', 'Hawker-Siddeley HS-125-700'),
(@root, 189, 'A32B', 'Airbus A321-100/200 (Sharklets)'),
(@root, 193, 'A359', 'Airbus A350-900'),
(@root, 195, 'CL30', 'Bombardier Challenger 300'),
(@root, 196, 'B789', 'Boeing 787-9'),
(@root, 197, 'SU95', 'Sukhoi Superjet 100-95B'),
(@root, 201, 'C56X', 'Cessna 560XL Citation Excel');

INSERT INTO `airports`(`uid`, `id`, `iata`, `icao`, `name`)
VALUES
(@root,   1, 'ABV', 'DNAA', 'Abuja, Nigeria'),
(@root,   2, 'ABZ', 'EGPD', 'Aberdeen, Großbritannien'),
(@root,   3, 'ACC', 'DGAA', 'Accra, Ghana'),
(@root,   4, 'ACE', 'GCRR', 'Lanzarote, Spanien'),
(@root,   5, 'ADA', 'LTAF', 'Adana, Türkei'),
(@root,   6, 'ADB', 'LTBJ', 'Izmir, Türkei'),
(@root,   7, 'ADD', 'HAAB', 'Addis Abeba, Äthiopien'),
(@root,   8, 'AGA', 'GMAD', 'Agadir, Marokko'),
(@root,   9, 'AGP', 'LEMG', 'Malaga, Spanien'),
(@root,  10, 'ALA', 'UAAA', 'Almaty, Kasachstan'),
(@root,  11, 'ALG', 'DAAG', 'Algier, Algerien'),
(@root,  12, 'AMM', 'OJAI', 'Amman, Jordanien'),
(@root,  13, 'AMS', 'EHAM', 'Amsterdam, Niederlande'),
(@root,  14, 'ARN', 'ESSA', 'Stockholm, Schweden'),
(@root,  15, 'ASB', 'UTAA', 'Ashgabat, Turkmenistan'),
(@root,  16, 'ASM', 'HHAS', 'Asmara, Eritrea'),
(@root,  17, 'ASR', 'LTAU', 'Kayseri, Türkei'),
(@root,  18, 'ATH', 'LGAV', 'Athen, Griechenland'),
(@root,  19, 'ATL', 'KATL', 'Atlanta, USA'),
(@root,  20, 'AUH', 'OMAA', 'Abu Dhabi, Ver.Arab.Emirate'),
(@root,  21, 'AYT', 'LTAI', 'Antalya, Türkei'),
(@root,  22, 'BAH', 'OBBI', 'Bahrain, Bahrain'),
(@root,  23, 'BCN', 'LEBL', 'Barcelona, Spanien'),
(@root,  24, 'BEG', 'LYBE', 'Belgrad, Serbien'),
(@root,  25, 'BEY', 'OLBA', 'Beirut, Libanon'),
(@root,  26, 'BGI', 'TBPB', 'Barbados, Barbados'),
(@root,  27, 'BGO', 'ENBR', 'Bergen, Norwegen'),
(@root,  28, 'BGY', 'LIME', 'Bergamo-Orio AlSerio, Italien'),
(@root,  29, 'BHX', 'EGBB', 'Birmingham, Großbritannien'),
(@root,  30, 'BIO', 'LEBB', 'Bilbao, Spanien'),
(@root,  31, 'BJL', 'GBYD', 'Banjul, Gambia'),
(@root,  32, 'BKK', 'VTBS', 'Bangkok, Thailand'),
(@root,  33, 'BLL', 'EKBI', 'Billund, Dänemark'),
(@root,  34, 'BLQ', 'LIPE', 'Bologna, Italien'),
(@root,  35, 'BLR', 'VOBL', 'Bangalore, Indien'),
(@root,  36, 'BOG', 'SKBO', 'Bogota, Kolumbien'),
(@root,  37, 'BOM', 'VABB', 'Mumbai, Indien'),
(@root,  38, 'BOS', 'KBOS', 'Boston, USA'),
(@root,  39, 'BRE', 'EDDW', 'Bremen, Deutschland'),
(@root,  40, 'BRU', 'EBBR', 'Brüssel, Belgien'),
(@root,  41, 'BSL', 'LFSB', 'Basel, Schweiz'),
(@root,  42, 'BUD', 'LHBP', 'Budapest, Ungarn'),
(@root,  43, 'CAI', 'HECA', 'Kairo, Ägypten'),
(@root,  44, 'CAN', 'ZGGG', 'Guangzhou, China'),
(@root,  45, 'CCS', 'SVMI', 'Caracas, Venezuela'),
(@root,  46, 'CCU', 'VECC', 'Kolkata, Indien'),
(@root,  47, 'CDG', 'LFPG', 'Paris-Ch.De Gaulle, Frankreich'),
(@root,  48, 'CLT', 'KCLT', 'Charlotte, USA'),
(@root,  49, 'CMB', 'VCBI', 'Colombo, Sri Lanka'),
(@root,  50, 'CMN', 'GMMN', 'Casablanca, Marokko'),
(@root,  51, 'CPH', 'EKCH', 'Kopenhagen, Dänemark'),
(@root,  52, 'CPT', 'FACT', 'Kapstadt, Südafrika'),
(@root,  53, 'CTA', 'LICC', 'Catania, Italien'),
(@root,  54, 'CUN', 'MMUN', 'Cancun, Mexiko'),
(@root,  55, 'DAM', 'OSDI', 'Damaskus, Syrien'),
(@root,  56, 'DBV', 'LDDU', 'Dubrovnik, Kroatien'),
(@root,  57, 'DEL', 'VIDP', 'Delhi, Indien'),
(@root,  58, 'DEN', 'KDEN', 'Denver, USA'),
(@root,  59, 'DFW', 'KDFW', 'Dallas-Fort Worth, USA'),
(@root,  60, 'DJE', 'DTTJ', 'Djerba, Tunesien'),
(@root,  61, 'DME', 'UUDD', 'Moskau-Domodedovo, Russland'),
(@root,  62, 'DMM', 'OEDF', 'Dammam, Saudi-Arabien'),
(@root,  63, 'DOH', 'OTBD', 'Doha, Katar'),
(@root,  64, 'DRS', 'EDDC', 'Dresden, Deutschland'),
(@root,  65, 'DTW', 'KDTW', 'Detroit, USA'),
(@root,  66, 'DUB', 'EIDW', 'Dublin, Irland'),
(@root,  67, 'DUS', 'EDDL', 'Düsseldorf, Deutschland'),
(@root,  68, 'DXB', 'OMDB', 'Dubai, Ver.Arab.Emirate'),
(@root,  69, 'DYU', 'UTDD', 'Duschanbe, Tadschikistan'),
(@root,  70, 'EBL', 'ORER', 'Erbil, Irak'),
(@root,  71, 'EDI', 'EGPH', 'Edinburgh, Großbritannien'),
(@root,  72, 'EMA', 'EGNX', 'East Midlands, Großbritannien'),
(@root,  73, 'ESB', 'LTAC', 'Ankara, Türkei'),
(@root,  74, 'EWR', 'KEWR', 'New York-Newark, USA'),
(@root,  75, 'EZE', 'SAEZ', 'Buenos Aires, Argentinien'),
(@root,  76, 'FAO', 'LPFR', 'Faro, Portugal'),
(@root,  77, 'FCO', 'LIRF', 'Rom-Fiumicino, Italien'),
(@root,  78, 'FDH', 'EDNY', 'Friedrichshafen, Deutschland'),
(@root,  79, 'FLL', 'KFLL', 'Fort Lauderdale, USA'),
(@root,  80, 'FLR', 'LIRQ', 'Florenz, Italien'),
(@root,  81, 'FMO', 'EDDG', 'Münster Osnabrück, Deutschland'),
(@root,  82, 'FNC', 'LPMA', 'Madeira, Portugal'),
(@root,  83, 'FUE', 'GCFV', 'Fuerteventura, Spanien'),
(@root,  84, 'GDN', 'EPGD', 'Gdansk/Danzig, Polen'),
(@root,  85, 'GIG', 'SBGL', 'Rio de Janeiro, Brasilien'),
(@root,  86, 'GOI', 'VAGO', 'Goa, Indien'),
(@root,  87, 'GOT', 'ESGG', 'Göteborg, Schweden'),
(@root,  88, 'GRU', 'SBGR', 'Sao Paulo-Guarulhos, Brasilien'),
(@root,  89, 'GRZ', 'LOWG', 'Graz, Österreich'),
(@root,  90, 'GVA', 'LSGG', 'Genf, Schweiz'),
(@root,  91, 'GZT', 'LTAJ', 'Gaziantep, Türkei'),
(@root,  92, 'HAJ', 'EDDV', 'Hannover, Deutschland'),
(@root,  93, 'HAM', 'EDDH', 'Hamburg, Deutschland'),
(@root,  94, 'HAN', 'VVNB', 'Hanoi, Vietnam'),
(@root,  95, 'HAV', 'MUHA', 'Havanna, Kuba'),
(@root,  96, 'HEL', 'EFHK', 'Helsinki, Finnland'),
(@root,  97, 'HGH', 'ZSHC', 'Hangzhou, China'),
(@root,  98, 'HKG', 'VHHH', 'Hongkong, Hong Kong'),
(@root,  99, 'HKT', 'VTSP', 'Phuket'),
(@root, 100, 'HND', 'RJTT', 'Tokio Haneda, Japan'),
(@root, 101, 'HOG', 'MUHG', 'Holguin, Kuba'),
(@root, 102, 'HRG', 'HEGN', 'Hurghada, Ägypten'),
(@root, 103, 'IAD', 'KIAD', 'Washington, USA'),
(@root, 104, 'IAH', 'KIAH', 'Houston, USA'),
(@root, 105, 'ICN', 'RKSI', 'Seoul-Incheon, Korea-Süd'),
(@root, 106, 'IKA', 'OIIE', 'Teheran ImamKhomeini, Iran'),
(@root, 107, 'INN', 'LOWI', 'Innsbruck, Österreich'),
(@root, 108, 'ISB', 'OPRN', 'Islamabad, Pakistan'),
(@root, 109, 'IST', 'LTBA', 'Istanbul, Türkei'),
(@root, 110, 'JED', 'OEJN', 'Jeddah, Saudi-Arabien'),
(@root, 111, 'JFK', 'KJFK', 'New York-J.F.Kennedy, USA'),
(@root, 112, 'JNB', 'FAJS', 'Johannesburg, Südafrika'),
(@root, 113, 'JRO', 'HTKJ', 'Kilimanjaro, Tansania'),
(@root, 114, 'KBP', 'UKBB', 'Kiew-Borispol, Ukraine'),
(@root, 115, 'KEF', 'BIKF', 'Reykjavik, Island'),
(@root, 116, 'KIV', 'LUKK', 'Chisinau, Moldawien'),
(@root, 117, 'KIX', 'RJBB', 'Osaka, Japan'),
(@root, 118, 'KLU', 'LOWK', 'Klagenfurt, Österreich'),
(@root, 119, 'KRK', 'EPKK', 'Krakau, Polen'),
(@root, 120, 'KRT', 'HSSS', 'Khartoum, Sudan'),
(@root, 121, 'KTW', 'EPKT', 'Kattowitz, Polen'),
(@root, 122, 'KUL', 'WMKK', 'Kuala Lumpur, Malaysia'),
(@root, 123, 'KWI', 'OKBK', 'Kuwait, Kuwait'),
(@root, 124, 'KZN', 'UWKD', 'Kazan, Russland'),
(@root, 125, 'LAD', 'FNLU', 'Luanda, Angola'),
(@root, 126, 'LAS', 'KLAS', 'Las Vegas, USA'),
(@root, 127, 'LAX', 'KLAX', 'Los Angeles, USA'),
(@root, 128, 'LCA', 'LCLK', 'Larnaca, Zypern'),
(@root, 129, 'LCY', 'EGLC', 'London-City Airport, Großbritannien'),
(@root, 130, 'LED', 'ULLI', 'Sankt Petersburg, Russland'),
(@root, 131, 'LEJ', 'EDDP', 'Leipzig Halle, Deutschland'),
(@root, 132, 'LGW', 'EGKK', 'London-Gatwick, Großbritannien'),
(@root, 133, 'LHE', 'OPLA', 'Lahore, Pakistan'),
(@root, 134, 'LHR', 'EGLL', 'London-Heathrow, Großbritannien'),
(@root, 135, 'LIN', 'LIML', 'Mailand-Linate, Italien'),
(@root, 136, 'LIS', 'LPPT', 'Lissabon, Portugal'),
(@root, 137, 'LJU', 'LJLJ', 'Ljubljana, Slowenien'),
(@root, 138, 'LNZ', 'LOWL', 'Linz, Österreich'),
(@root, 139, 'LOS', 'DNMM', 'Lagos, Nigeria'),
(@root, 140, 'LPA', 'GCLP', 'Las Palmas, Spanien'),
(@root, 141, 'LRM', 'MDLR', 'La Romana, Dominikan. Rep.'),
(@root, 142, 'LUX', 'ELLX', 'Luxemburg, Luxemburg'),
(@root, 143, 'LXR', 'HELX', 'Luxor, Ägypten'),
(@root, 144, 'LYS', 'LFLL', 'Lyon, Frankreich'),
(@root, 145, 'MAA', 'VOMM', 'Chennai, Indien'),
(@root, 146, 'MAD', 'LEMD', 'Madrid, Spanien'),
(@root, 147, 'MAN', 'EGCC', 'Manchester, Großbritannien'),
(@root, 148, 'MBA', 'HKMO', 'Mombasa, Kenia'),
(@root, 149, 'MBJ', 'MKJS', 'Montego Bay, Jamaika'),
(@root, 150, 'MCO', 'KMCO', 'Orlando, USA'),
(@root, 151, 'MCT', 'OOMS', 'Muscat, Oman'),
(@root, 152, 'MEX', 'MMMX', 'Mexico City, Mexiko'),
(@root, 153, 'MIA', 'KMIA', 'Miami, USA'),
(@root, 154, 'MLA', 'LMML', 'Malta, Malta'),
(@root, 155, 'MLE', 'VRMM', 'Male, Malediven'),
(@root, 156, 'MRS', 'LFML', 'Marseille, Frankreich'),
(@root, 157, 'MRU', 'FIMP', 'Mauritius, Mauritius'),
(@root, 158, 'MSQ', 'UMMS', 'Minsk, Weißrussland'),
(@root, 159, 'MUC', 'EDDM', 'München, Deutschland'),
(@root, 160, 'MXP', 'LIMC', 'Mailand-Malpensa, Italien'),
(@root, 161, 'NAP', 'LIRN', 'Neapel, Italien'),
(@root, 162, 'NBE', 'DTNZ', 'Enfidha, Tunesien'),
(@root, 163, 'NBO', 'HKJK', 'Nairobi, Kenia'),
(@root, 164, 'NCE', 'LFMN', 'Nizza, Frankreich'),
(@root, 165, 'NDR', 'GMFN', 'Nador, Marokko'),
(@root, 166, 'NGO', 'RJGG', 'Nagoya, Japan'),
(@root, 167, 'NKG', 'ZSNJ', 'Nanking, China'),
(@root, 168, 'NRT', 'RJAA', 'Tokio Narita, Japan'),
(@root, 169, 'NUE', 'EDDN', 'Nürnberg, Deutschland'),
(@root, 170, 'OPO', 'LPPR', 'Porto, Portugal'),
(@root, 171, 'ORD', 'KORD', 'Chicago, USA'),
(@root, 172, 'OSL', 'ENGM', 'Oslo, Norwegen'),
(@root, 173, 'OTP', 'LROP', 'Bukarest, Rumänien'),
(@root, 174, 'OVB', 'UNNT', 'Novosibirsk, Russland'),
(@root, 175, 'PEE', 'USPP', 'Perm, Russland'),
(@root, 176, 'PEK', 'ZBAA', 'Peking, China'),
(@root, 177, 'PFO', 'LCPH', 'Paphos, Zypern'),
(@root, 178, 'PHC', 'DNPO', 'Port Harcourt, Nigeria'),
(@root, 179, 'PHL', 'KPHL', 'Philadelphia, USA'),
(@root, 180, 'PMI', 'LEPA', 'Palma de Mallorca, Spanien'),
(@root, 181, 'PNQ', 'VAPO', 'Pune, Indien'),
(@root, 182, 'PNR', 'FCPP', 'Pointe Noire, Kongo'),
(@root, 183, 'POP', 'MDPP', 'Puerto Plata, Dominikan. Rep.'),
(@root, 184, 'POZ', 'EPPO', 'Poznan/Posen, Polen'),
(@root, 185, 'PRG', 'LKPR', 'Prag, Tschechien'),
(@root, 186, 'PRN', 'LYPR', 'Pristina, Serbien'),
(@root, 187, 'PTY', 'MPTO', 'Panama City, Panama'),
(@root, 188, 'PUJ', 'MDPC', 'Punta Cana, Dominikan. Rep.'),
(@root, 189, 'PVG', 'ZSPD', 'Shanghai PuDong, China'),
(@root, 190, 'REC', 'SBRF', 'Recife, Brasilien'),
(@root, 191, 'RIX', 'EVRA', 'Riga, Lettland'),
(@root, 192, 'RMF', 'HEMA', 'Marsa Alam, Ägypten'),
(@root, 193, 'ROV', 'URRR', 'Rostow, Russland'),
(@root, 194, 'RUH', 'OERK', 'Riad, Saudi-Arabien'),
(@root, 195, 'RZE', 'EPRZ', 'Rzeszow, Polen'),
(@root, 196, 'SAH', 'OYSN', 'Sanaa, Jemen'),
(@root, 197, 'SAW', 'LTFJ', 'Istanbul S-Gokcen, Türkei'),
(@root, 198, 'SCL', 'SCEL', 'Santiago de Chile, Chile'),
(@root, 199, 'SDQ', 'MDSD', 'Santo Domingo, Dominikan. Rep.'),
(@root, 200, 'SEA', 'KSEA', 'Seattle, USA'),
(@root, 201, 'SFO', 'KSFO', 'San Francisco, USA'),
(@root, 202, 'SGN', 'VVTS', 'Ho Chi Minh City, Vietnam'),
(@root, 203, 'SHE', 'ZYTX', 'Shenyang, China'),
(@root, 204, 'SIN', 'WSSS', 'Singapur, Singapur'),
(@root, 205, 'SJO', 'MROC', 'San Jose, Costa Rica'),
(@root, 206, 'SJU', 'TJSJ', 'San Juan, Puerto Rico'),
(@root, 207, 'SKG', 'LGTS', 'Thessaloniki, Griechenland'),
(@root, 208, 'SOF', 'LBSF', 'Sofia, Bulgarien'),
(@root, 209, 'SOU', 'EGHI', 'Southampton, Großbritannien'),
(@root, 210, 'SPC', 'GCLA', 'La Palma, Spanien'),
(@root, 211, 'SPU', 'LDSP', 'Split, Kroatien'),
(@root, 212, 'SSA', 'SBSV', 'Salvador, Brasilien'),
(@root, 213, 'SSG', 'FGSL', 'Malabo, Äquator.-Guinea'),
(@root, 214, 'SSH', 'HESH', 'Sharm El Sheik, Ägypten'),
(@root, 215, 'STR', 'EDDS', 'Stuttgart, Deutschland'),
(@root, 216, 'SVG', 'ENZV', 'Stavanger, Norwegen'),
(@root, 217, 'SVO', 'UUEE', 'Moskau-Sheremetyevo, Russland'),
(@root, 218, 'SVX', 'USSS', 'Ekaterinburg, Russland'),
(@root, 219, 'SYD', 'YSSY', 'Sydney, Australien'),
(@root, 220, 'SZG', 'LOWS', 'Salzburg, Österreich'),
(@root, 221, 'TAB', 'TTCP', 'Tobago, Trinidad Tobago'),
(@root, 222, 'TAS', 'UTTT', 'Taschkent, Usbekistan'),
(@root, 223, 'TFS', 'GCTS', 'Teneriffa-Sur Reina, Spanien'),
(@root, 224, 'TGD', 'LYPG', 'Podgorica, Montenegro'),
(@root, 225, 'TIP', 'HLLT', 'Tripolis, Libyen'),
(@root, 226, 'TLL', 'EETN', 'Tallinn, Estland'),
(@root, 227, 'TLS', 'LFBO', 'Toulouse, Frankreich'),
(@root, 228, 'TLV', 'LLBG', 'Tel Aviv, Israel'),
(@root, 229, 'TPE', 'RCTP', 'Taipeh, Taiwan'),
(@root, 230, 'TRN', 'LIMF', 'Turin, Italien'),
(@root, 231, 'TSE', 'UACC', 'Astana, Kasachstan'),
(@root, 232, 'TUN', 'DTTA', 'Tunis, Tunesien'),
(@root, 233, 'TXL', 'EDDT', 'Berlin-Tegel, Deutschland'),
(@root, 234, 'UVF', 'TLPL', 'Saint Lucia, Saint Lucia'),
(@root, 235, 'VCE', 'LIPZ', 'Venedig, Italien'),
(@root, 236, 'VIE', 'LOWW', 'Wien, Österreich'),
(@root, 237, 'VNO', 'EYVI', 'Vilnius, Litauen'),
(@root, 238, 'VRA', 'MUVR', 'Varadero, Kuba'),
(@root, 239, 'VRN', 'LIPX', 'Verona, Italien'),
(@root, 240, 'WAW', 'EPWA', 'Warschau, Polen'),
(@root, 241, 'WDH', 'FYWH', 'Windhuk, Namibia'),
(@root, 242, 'WRO', 'EPWR', 'Wroclaw/Breslau, Polen'),
(@root, 243, 'XRY', 'LEJR', 'Jerez de la Frontera, Spanien'),
(@root, 244, 'YOW', 'CYOW', 'Ottawa, Kanada'),
(@root, 245, 'YUL', 'CYUL', 'Montreal-Trudeau, Kanada'),
(@root, 246, 'YVR', 'CYVR', 'Vancouver, Kanada'),
(@root, 247, 'YYC', 'CYYC', 'Calgary, Kanada'),
(@root, 248, 'YYZ', 'CYYZ', 'Toronto, Kanada'),
(@root, 249, 'ZAD', 'LDZD', 'Zadar, Kroatien'),
(@root, 250, 'ZAG', 'LDZA', 'Zagreb, Kroatien'),
(@root, 251, 'ZRH', 'LSZH', 'Zürich, Schweiz'),
(@root, 252, 'SEZ', 'FSIA', 'Mahe, Seychellen'),
(@root, 253, 'AJR', 'ESNX', 'Arvidsjaur, Schweden'),
(@root, 254, 'BIA', 'LFKB', 'Bastia, Frankreich'),
(@root, 255, 'PDL', 'LPPD', 'Ponta Delgada, Portugal'),
(@root, 256, 'GLA', 'EGPF', 'Glasgow, Großbritannien'),
(@root, 257, 'ANU', 'TAPA', 'Antigua, Antigua'),
(@root, 258, 'RKT', 'OMRK', 'Ras al Khaymah, Ver.Arab.Emirate'),
(@root, 259, 'COK', 'VOCI', 'Cochin, Indien'),
(@root, 260, 'ZNZ', 'HTZA', 'Sansibar, Tansania'),
(@root, 261, 'CGN', 'EDDK', 'Köln Bonn, Deutschland'),
(@root, 262, 'VKO', 'UUWW', 'Moskau-Vnukovo, Russland'),
(@root, 263, 'GOA', 'LIMJ', 'Genua, Italien'),
(@root, 264, 'TRD', 'ENVA', 'Trondheim, Norwegen'),
(@root, 265, 'PMO', 'LICJ', 'Palermo, Italien'),
(@root, 266, 'OLB', 'LIEO', 'Olbia, Italien'),
(@root, 267, 'KUF', 'UWWW', 'Samara, Russland'),
(@root, 268, 'GOJ', 'UWGG', 'N. Novgorod, Russland'),
(@root, 269, 'CLE', 'KCLE', 'Cleveland, USA'),
(@root, 270, 'GWT', 'EDXW', 'Westerland, Deutschland'),
(@root, 271, 'VAR', 'LBWN', 'Varna, Bulgarien'),
(@root, 272, 'PHX', 'KPHX', 'Phoenix, USA'),
(@root, 273, 'ORN', 'DAOO', 'Oran, Algerien'),
(@root, 274, 'SAN', 'KSAN', 'San Diego-Lindberg, USA'),
(@root, 275, 'TAO', 'ZSQD', 'Qingdao, China'),
(@root, 276, 'SZF', 'LTFH', 'Samsun-Carsamba, Türkei'),
(@root, 277, 'RDU', 'KRDU', 'Raleigh/Durham, USA'),
(@root, 278, 'TBS', 'UGTB', 'Tbilisi, Georgien'),
(@root, 279, 'QSH', 'DUMI', 'Seeheim, Deutschland'),
(@root, 280, 'ALC', 'LEAL', 'Alicante, Spanien'),
(@root, 281, 'MAO', 'SBEG', 'Manaus, Brasilien'),
(@root, 282, 'HER', 'LGIR', 'Heraklion, Griechenland'),
(@root, 283, 'RLG', 'ETNL', 'Rostock Laage, Deutschland'),
(@root, 284, 'ERF', 'EDDE', 'Erfurt, Deutschland'),
(@root, 285, 'SOB', 'LHSM', 'Sarmellek, Ungarn'),
(@root, 286, 'BSB', 'SBBR', 'Brasilia, Brasilien'),
(@root, 287, 'DLM', 'LTBS', 'Dalaman, Türkei'),
(@root, 288, 'TCE', 'LRTC', 'Tulcea Cataloi, Rumänien'),
(@root, 289, 'RHO', 'LGRP', 'Rhodos, Griechenland'),
(@root, 290, 'KGS', 'LGKO', 'Kos, Griechenland'),
(@root, 291, 'UGC', 'UTNU', 'Urgench, Usbekistan'),
(@root, 292, 'CFU', 'LGKR', 'Kerkyra, Griechenland'),
(@root, 293, 'ANC', 'PANC', 'Anchorage, USA'),
(@root, 294, 'IBZ', 'LEIB', 'Ibiza, Spanien'),
(@root, 295, 'YHZ', 'CYHZ', 'Halifax, Kanada'),
(@root, 296, 'REU', 'LERS', 'Reus, Spanien'),
(@root, 297, 'PAE', 'KPAE', 'Everett, USA'),
(@root, 298, 'SID', 'GVAC', 'Sal, Kap Verde'),
(@root, 299, 'VLC', 'LEVC', 'Valencia, Spanien'),
(@root, 300, 'BJV', 'LTFE', 'Bodrum, Türkei'),
(@root, 301, 'BVC', 'GVBA', 'Boa Vista, Kap Verde'),
(@root, 302, 'GPA', 'LGRX', 'Patras, Griechenland'),
(@root, 303, 'PVK', 'LGPZ', 'Preveza/Lefkas, Griechenland'),
(@root, 304, 'SIP', 'UKFF', 'Simferopol, Ukraine'),
(@root, 305, 'BOJ', 'LBBG', 'Burgas, Bulgarien'),
(@root, 306, 'HDF', 'EDAH', 'Heringsdorf, Deutschland'),
(@root, 307, 'RJK', 'LDRI', 'Rijeka, Kroatien'),
(@root, 308, 'MLX', 'LTAT', 'Malatya, Türkei'),
(@root, 309, 'JER', 'EGJJ', 'Jersey, Großbritannien'),
(@root, 310, 'SUF', 'LICA', 'Lamezia Terme, Italien'),
(@root, 311, 'MAH', 'LEMH', 'Menorca, Spanien'),
(@root, 312, 'SMI', 'LGSM', 'Samos, Griechenland'),
(@root, 313, 'CHQ', 'LGSA', 'Chania, Griechenland'),
(@root, 314, 'FRA', 'EDDF', 'Frankfurt, Deutschland'),
(@root, 315, 'JTR', 'LGSR', 'Santorini, Griechenland'),
(@root, 316, 'MIR', 'DTMB', 'Monastir, Tunesien'),
(@root, 317, 'KVA', 'LGKV', 'Kavala, Griechenland'),
(@root, 318, 'ZTH', 'LGZA', 'Zakynthos, Griechenland'),
(@root, 319, 'JMK', 'LGMK', 'Mykonos, Griechenland'),
(@root, 320, 'LDE', 'LFBT', 'Lourdes, Frankreich'),
(@root, 321, 'YXY', 'CYXY', 'Whitehorse, Kanada'),
(@root, 322, 'EZS', 'LTCA', 'Elazig, Türkei'),
(@root, 323, 'JNB', 'FAOR', 'Johannesburg, Südafrika'),
(@root, 324, 'BRS', 'EGGD', 'Bristol, Großbritannien'),
(@root, 325, 'BGW', 'ORBI', 'Bagdad, Irak'),
(@root, 326, 'SXB', 'LFST', 'Strassburg, Frankreich'),
(@root, 327, 'BWI', 'KBWI', 'Baltimore-Washington, USA'),
(@root, 328, 'NBE', 'DTNH', 'Enfidha, Tunesien'),
(@root, 329, 'CTU', 'ZUUU', 'Chengdu, China'),
(@root, 330, 'TIV', 'LYTV', 'Tivat, Montenegro'),
(@root, 331, 'PUY', 'LDPL', 'Pula, Kroatien'),
(@root, 332, 'NDR', 'GMMW', 'Nador, Marokko'),
(@root, 333, 'CAS', 'GMMC', 'Casablanca / Anfa, Marokko'),
(@root, 334, 'TZX', 'LTCG', 'Trabzon, Türkei'),
(@root, 335, 'FAI', 'PAFA', 'Fairbanks, USA'),
(@root, 336, 'KSF', 'EDVK', 'Kassel, Deutschland'),
(@root, 337, 'SCN', 'EDDR', 'Saarbrücken, Deutschland'),
(@root, 338, 'BTS', 'LZIB', 'Bratislava, Slowakei'),
(@root, 339, 'STN', 'EGSS', 'London-Stansted, Großbritannien'),
(@root, 340, 'GCI', 'EGJB', 'Guernsey, Großbritannien'),
(@root, 341, 'SXF', 'EDDB', 'Berlin-Schönefeld, Deutschland'),
(@root, 342, 'LPL', 'EGGP', 'Liverpool, Großbritannien'),
(@root, 343, 'RTM', 'EHRD', 'Rotterdam, Niederlande'),
(@root, 344, 'LTN', 'EGGW', 'London-Luton Airport, Großbritannien'),
(@root, 345, 'QEF', 'EDFE', 'Egelsbach, Deutschland'),
(@root, 346, 'GYD', 'UBBB', 'Baku, Aserbaidschan'),
(@root, 347, 'FAE', 'EKVG', 'Vagar, Dänemark'),
(@root, 348, 'QMZ', 'EDFZ', 'Mainz Finthen, Deutschland'),
(@root, 349, 'LIL', 'LFQQ', 'Lille, Frankreich'),
(@root, 350, 'BOD', 'LFBD', 'Bordeaux, Frankreich'),
(@root, 351, 'LBV', 'FOOL', 'Libreville, Gabun'),
(@root, 352, 'BDS', 'LIBR', 'Brindisi, Italien'),
(@root, 353, 'GZP', 'LTFG', 'Gazipasa / Alanya, Türkei'),
(@root, 354, 'PAD', 'EDLP', 'Paderborn/Lippstadt, Deutschland'),
(@root, 355, 'MED', 'OEMA', 'Medina, Saudi-Arabien'),
(@root, 356, 'CND', 'LRCK', 'Konstanza, Rumänien'),
(@root, 357, 'RTW', 'UWSS', 'Saratov, Russland'),
(@root, 358, 'KLX', 'LGKL', 'Kalamata, Griechenland'),
(@root, 359, 'LWO', 'UKLL', 'Lvov, Ukraine'),
(@root, 360, 'HYD', 'VOHS', 'Hyderabad, Indien'),
(@root, 361, 'KUN', 'EYKA', 'Kaunas, Litauen'),
(@root, 362, 'AAA', 'AAAA', 'Ausland, FICTITIOUSPOINTS'),
(@root, 363, 'SFJ', 'BGSF', 'Kangerlussuaq, Grönland'),
(@root, 364, 'SVQ', 'LEZL', 'Sevilla, Spanien'),
(@root, 365, 'BVA', 'LFOB', 'Paris-Beauvais, Frankreich'),
(@root, 366, 'GRX', 'LEGR', 'Granada, Spanien'),
(@root, 367, 'AVN', 'LFMV', 'Avignon, Frankreich'),
(@root, 368, 'RAK', 'GMMX', 'Marrakesch, Marokko'),
(@root, 369, 'SGE', 'EDGS', 'Siegen, Deutschland'),
(@root, 370, 'ZAZ', 'LEZG', 'Zaragoza, Spanien'),
(@root, 371, 'SHJ', 'OMSJ', 'Sharjah, Ver.Arab.Emirate'),
(@root, 372, 'RGN', 'VYYY', 'Yangon, Myanmar'),
(@root, 373, 'REP', 'VDSR', 'Siem Reap, Kambodscha'),
(@root, 374, 'KRR', 'URKK', 'Krasnodar, Russland'),
(@root, 375, 'JKG', 'ESGJ', 'Jonkoping, Schweden'),
(@root, 376, 'CAG', 'LIEE', 'Cagliari, Italien'),
(@root, 377, 'EVN', 'UDYZ', 'Eriwan, Armenien'),
(@root, 378, 'UFA', 'UWUU', 'Ufa, Russland'),
(@root, 379, 'GOI', 'VOGO', 'Goa, Indien'),
(@root, 380, 'RVN', 'EFRO', 'Rovaniemi, Finnland'),
(@root, 381, 'TRS', 'LIPQ', 'Triest, Italien'),
(@root, 382, 'KTT', 'EFKT', 'Kittila, Finnland'),
(@root, 383, 'MEL', 'YMML', 'Melbourne, Australien'),
(@root, 384, 'DTM', 'EDLW', 'Dortmund, Deutschland'),
(@root, 385, 'PNA', 'LEPP', 'Pamplona, Spanien'),
(@root, 386, 'VLL', 'LEVD', 'Valladolid, Spanien'),
(@root, 387, 'TSR', 'LRTR', 'Timisoara, Rumänien'),
(@root, 388, 'BRN', 'LSZB', 'Bern, Schweiz'),
(@root, 389, 'TTU', 'GMTN', 'Tetouan, Marokko'),
(@root, 390, 'SLC', 'KSLC', 'Salt Lake City, USA'),
(@root, 391, 'MSP', 'KMSP', 'Minneapolis, USA'),
(@root, 392, 'SJJ', 'LQSA', 'Sarajevo, Bosnien-Herzegow'),
(@root, 393, 'TFN', 'GCXO', 'Teneriffa-Norte, Spanien'),
(@root, 394, 'TCP', 'HETB', 'Taba, Ägypten'),
(@root, 395, 'IGS', 'ETSI', 'Ingolstadt-Manching, Deutschland'),
(@root, 396, 'AZS', 'MDAB', 'Samana, Dominikan. Rep.'),
(@root, 397, 'DWC', 'OMDW', 'Dubai-Al Maktoum, Ver.Arab.Emirate'),
(@root, 398, 'IND', 'KIND', 'Indianapolis, USA'),
(@root, 399, 'OSI', 'LDOS', 'Osijek, Kroatien'),
(@root, 400, 'NJF', 'ORNI', 'Al Najaf, Irak'),
(@root, 401, 'PTP', 'TFFR', 'Pointe a Pitre, Guadeloupe'),
(@root, 402, 'DNZ', 'LTAY', 'Denizli, Türkei'),
(@root, 403, 'ACA', 'MMAA', 'Acapulco, Mexiko'),
(@root, 404, 'MJV', 'LELC', 'Murcia, Spanien'),
(@root, 405, 'AER', 'URSS', 'Sochi, Russland'),
(@root, 406, 'LIM', 'SPIM', 'Lima, Peru'),
(@root, 407, 'LME', 'LFRM', 'Le Mans, Frankreich'),
(@root, 409, 'HHN', 'EDFH', 'Frankfurt-Hahn, Deutschland'),
(@root, 410, 'BQN', 'TJBQ', 'Aguadilla, Puerto Rico'),
(@root, 411, 'CKG', 'ZUCK', 'Chongqing, China'),
(@root, 412, 'CVT', 'EGBE', 'Coventry'),
(@root, 413, 'CUR', 'TNCC', 'Curaçao'),
(@root, 414, 'CWB', 'SBCT', 'Curitiba, Brasilien'),
(@root, 415, 'DKR', 'GOOY', 'Dakar, Senegal'),
(@root, 416, 'DAC', 'VGHS', 'Dhaka, Bangladesh'),
(@root, 417, 'GDL', 'MMGL', 'Guadalajara, Mexiko'),
(@root, 418, 'KAN', 'DNKN', 'Kano, Nigeria'),
(@root, 419, 'KJA', 'UNKL', 'Krasnojarsk, Russland'),
(@root, 420, 'MEM', 'KMEM', 'Memphis, USA'),
(@root, 421, 'MVD', 'SUMU', 'Montevideo, Uruguay'),
(@root, 422, 'UIO', 'SEQM', 'Quito, Ecuador'),
(@root, 423, 'VCP', 'SBKP', 'São Paulo-Viracopos, Brasilien'),
(@root, 424, 'HFE', 'ZSOF', 'Hefei/Luogang, China'),
(@root, 425, 'TIA', 'LATI', 'Tirana, Albanien'),
(@root, 426, 'XFW', 'EDHI', 'Hamburg-Finkenwerder, Deutschland'),
(@root, 428, 'BRI', 'LIBD', 'Bari, Italien'),
(@root, 429, 'MPL', 'LFMT', 'Montpellier, Frankreich'),
(@root, 430, 'KSD', 'ESOK', 'Karlstad, Schweden'),
(@root, 431, 'CGK', 'WIII', 'Jakarta, Indonesien'),
(@root, 432, 'DOH', 'OTHH', 'Doha, Katar'),
(@root, 433, 'PEG', 'LIRZ', 'Perugia, Italien'),
(@root, 434, 'ULN', 'ZMUB', 'Ulan Bator, Mongolei'),
(@root, 435, 'FOR', 'SBFZ', 'Fortaleza, Brasilien'),
(@root, 436, 'LUZ', 'EPLB', 'Lublin, Polen'),
(@root, 437, 'ZQW', 'EDRZ', 'Zweibrücken, Deutschland'),
(@root, 438, 'YFB', 'CYFB', 'Iqaluit, Kanada'),
(@root, 439, 'OUD', 'GMFO', 'Oujda, Marokko'),
(@root, 440, 'QRR', 'EDRR', 'Rundflug, Deutschland'),
(@root, 441, 'SLL', 'OOSA', 'Salalah, Oman'),
(@root, 442, 'ORB', 'ESOE', 'Oerebro, Schweden'),
(@root, 443, 'GND', 'TGPY', 'Grenada, Grenada'),
(@root, 444, 'VGO', 'LEVX', 'Vigo, Spanien'),
(@root, 445, 'FKB', 'EDSB', 'Karlsruhe-Söllingen, Deutschland'),
(@root, 446, 'NAS', 'MYNN', 'Nassau, Bahamas'),
(@root, 447, 'ASW', 'HESN', 'Assuan, Ägypten'),
(@root, 448, 'YEI', 'LTBR', 'Bursa, Türkei'),
(@root, 449, 'OAI', 'OAIX', 'Bagram, Afghanistan'),
(@root, 450, 'LBG', 'LFPB', 'Paris-Le Bourget, Frankreich'),
(@root, 451, 'GRQ', 'EHGG', 'Groningen, Niederlande'),
(@root, 452, 'IVL', 'EFIV', 'Ivalo, Finnland'),
(@root, 453, 'NTE', 'LFRS', 'Nantes, Frankreich'),
(@root, 454, 'SKP', 'LWSK', 'Skopje, Mazedonien'),
(@root, 455, 'BZG', 'EPBY', 'Bydgoszcz, Polen'),
(@root, 456, 'AAL', 'EKYT', 'Aalborg, Dänemark'),
(@root, 457, 'VIT', 'LEVT', 'Vitoria, Spanien'),
(@root, 458, 'DHF', 'OMAM', 'Abu Dhabi-Al Dhafra, Ver.Arab.Emirate'),
(@root, 459, 'RIV', 'KRIV', 'Riverside, USA'),
(@root, 460, 'LEN', 'LELN', 'Leon, Spanien'),
(@root, 461, 'SLM', 'LESA', 'Salamanca, Spanien'),
(@root, 462, 'OSR', 'LKMT', 'Ostrava, Tschechien'),
(@root, 463, 'LGG', 'EBLG', 'Liege, Belgien'),
(@root, 464, 'NGB', 'ZSNB', 'Ningbo, China'),
(@root, 465, 'TUF', 'LFOT', 'Tours, Frankreich'),
(@root, 466, 'CSY', 'UWKS', 'Cheboksary, Russland'),
(@root, 467, 'PVD', 'KPVD', 'Providence, USA'),
(@root, 468, 'PDX', 'KPDX', 'Portland, USA'),
(@root, 469, 'VDB', 'ENFG', 'Fagernes, Norwegen'),
(@root, 470, 'QZX', 'EQZX', 'Teststation, Deutschland'),
(@root, 471, 'HBE', 'HEBA', 'Borg El Arab, Ägypten'),
(@root, 472, 'UUD', 'UIUU', 'Ulan-Ude, Russland'),
(@root, 473, 'ILZ', 'LZZI', 'Zilina, Slowakei'),
(@root, 474, 'LUG', 'LSZA', 'Lugano, Schweiz'),
(@root, 475, 'BDU', 'ENDU', 'Bardufoss, Norwegen'),
(@root, 476, 'ANR', 'EBAW', 'Antwerpen, Belgien'),
(@root, 477, 'TPA', 'KTPA', 'Tampa, USA'),
(@root, 478, 'RSW', 'KRSW', 'Fort Myers, USA'),
(@root, 479, 'TSN', 'ZBTJ', 'Tianjin, China'),
(@root, 480, 'NVI', 'UTSA', 'Navoi, Usbekistan'),
(@root, 481, 'MNL', 'RPLL', 'Manila, Philippinen'),
(@root, 482, 'CSX', 'ZGHA', 'Changsha, China'),
(@root, 483, 'TEQ', 'LTBU', 'Tekidag, Türkei'),
(@root, 484, 'KJK', 'EBKT', 'Kortrijk-Wevelgem International'),
(@root, 486, 'SNU', 'MUSC', 'Santa Clara-Abel Santamaria'),
(@root, 487, 'LHW', 'ZLLL', 'Lanzhou Zhongchuan'),
(@root, 488, '???', '????', ''),
(@root, 489, 'FDF', 'TFFF', 'Fort-de France  Martinique A.Cesaire'),
(@root, 490, 'PSA', 'LIRP', 'Pisa-Galileo Galilei International'),
(@root, 491, 'SNN', 'EINN', 'Shannon'),
(@root, 492, 'INV', 'EGPE', 'Inverness'),
(@root, 493, 'SIR', 'LSGS', 'Sion'),
(@root, 494, 'SEN', 'EGMC', 'London-Southend'),
(@root, 495, 'CEG', 'EGNR', 'Chester-Hawarden'),
(@root, 496, 'BQH', 'EGKB', 'London-Biggin Hill'),
(@root, 497, 'CFE', 'LFLC', 'Clermont-Ferrand-Auvergne'),
(@root, 498, 'FAB', 'EGLF', 'Farnborough'),
(@root, 499, 'BRQ', 'LKTB', 'Brünn-Turany'),
(@root, 500, 'ODE', 'EKOD', 'Odense-Hans Christian Andersen'),
(@root, 501, 'QMN', 'EDTM', 'Mengen'),
(@root, 502, 'OXF', 'EGTK', 'Oxford'),
(@root, 503, 'LLA', 'ESPA', 'Lulea-Kallax'),
(@root, 504, 'TSF', 'LIPH', 'Venice-Treviso Sant\'Angelo'),
(@root, 505, 'ACH', 'LSZR', 'Altenrhein'),
(@root, 506, 'BWE', 'EDVE', 'Braunschweig/Wolfsburg'),
(@root, 507, 'MGL', 'EDLN', 'Mönchengladbach'),
(@root, 508, 'EXT', 'EGTE', 'Exeter-International'),
(@root, 509, 'NCL', 'EGNT', 'Newcastle-International'),
(@root, 510, 'BYJ', 'LPBJ', 'Beja'),
(@root, 511, 'ADJ', 'OJAM', 'Amman-Marka International'),
(@root, 512, 'IEV', 'UKKK', 'Kiew-Zhuliany International'),
(@root, 513, 'ZHI', 'LSZG', 'Grenchen'),
(@root, 514, 'RNS', 'LFRN', 'Rennes-Saint-Jacques'),
(@root, 515, 'MST', 'EHBK', 'Maastricht/Aachen'),
(@root, 516, 'SYX', 'ZJSY', 'Sanya-Phoenix International'),
(@root, 517, 'NYO', 'ESKN', 'Stockholm-Skavsta'),
(@root, 518, 'OBF', 'EDMO', 'Oberpfaffenhofen'),
(@root, 519, 'EIN', 'EHEH', 'Eindhoven'),
(@root, 520, 'BZV', 'FCBB', 'Brazzaville-Maya-Maya'),
(@root, 521, 'TLN', 'LFTH', 'Toulon-Hyères'),
(@root, 522, 'TRF', 'ENTO', 'Sandefjord-Torp'),
(@root, 523, 'PIK', 'EGPK', 'Glasgow-Prestwick'),
(@root, 524, 'LBA', 'EGNM', 'Leeds/Bradford-International'),
(@root, 525, 'UGN', 'KUGN', 'Waukegan'),
(@root, 526, 'CIA', 'LIRA', 'Rom-Ciampino'),
(@root, 527, 'HPN', 'KHPN', 'Westchester County'),
(@root, 528, 'BMA', 'ESSB', 'Stockholm-Bromma'),
(@root, 529, 'AKH', 'OEKJ', 'Al Kharj-Prince Sultan Air Base'),
(@root, 530, 'AGH', 'ESTA', 'Angelholm-Helsingborg'),
(@root, 531, 'FMM', 'EDJA', 'Memmingen-Allgäu'),
(@root, 532, 'BOH', 'EGHH', 'Bournemouth'),
(@root, 533, 'LYX', 'EGMD', 'Lydd-London Ashford'),
(@root, 534, 'ZQC', 'EDRY', 'Speyer'),
(@root, 535, 'CMF', 'LFLB', 'Chambery/Aix-les-Bains'),
(@root, 536, 'PMF', 'LIMP', 'Parma-Giuseppe Verdi'),
(@root, 537, 'DSA', 'EGCN', 'Doncaster Sheffield'),
(@root, 538, 'OST', 'EBOS', 'Ostende/Brügge-International'),
(@root, 539, 'ABJ', 'DIAP', 'Abidjan-Felix Houphouet-Boigny International'),
(@root, 540, 'FIH', 'FZAA', 'Kinshasa-N\'Djili International'),
(@root, 541, 'KGL', 'HRYR', 'Kigali-International'),
(@root, 542, 'AGB', 'EDMA', 'Augsburg Airport'),
(@root, 543, 'OUA', 'DFFD', 'Ouagadougou'),
(@root, 544, 'GNY', 'LTCS', 'Sanliurfa- GAP'),
(@root, 545, 'MMX', 'ESMS', 'Malmo'),
(@root, 546, 'TTN', 'KTTN', 'Trenton-Mercer'),
(@root, 547, 'KLV', 'LKKV', 'Karlovy Vary'),
(@root, 548, 'XMN', 'ZSAM', 'Xiamen-Gaoqi International'),
(@root, 549, 'AOI', 'LIPY', 'Ancona-Falconara'),
(@root, 550, 'LHA', 'EDTL', 'Lahr-Black Forest'),
(@root, 551, 'VCV', 'KVCV', 'Victorville'),
(@root, 552, 'CEQ', 'LFMD', 'Cannes-Mandelieu'),
(@root, 553, 'LBC', 'EDHL', 'Lübeck'),
(@root, 554, 'PWK', 'KPWK', 'Chicago-Executive'),
(@root, 555, 'GRO', 'LEGE', 'Gerona-Costa Brava'),
(@root, 556, 'NRN', 'EDLV', 'Niederrhein'),
(@root, 557, 'RKE', 'EKRK', 'Kopenhagen-Roskilde'),
(@root, 558, 'JSI', 'LGSK', 'Skiathos-Alexandros Papadiamantis'),
(@root, 559, 'NWI', 'EGSH', 'Norwich-International'),
(@root, 560, 'NHT', 'EGWU', 'Northolt'),
(@root, 561, 'SZX', 'ZGSZ', 'Shenzhen-Bao\'an International'),
(@root, 562, 'IOM', 'EGNS', 'Isle of Man'),
(@root, 563, 'BGR', 'KBGR', 'Bangor-International'),
(@root, 564, 'BZO', 'LIPB', 'Bozen-Dolomiti'),
(@root, 565, 'BZR', 'LFMU', 'Beziers-Cap d\'Agde'),
(@root, 566, 'DOL', 'LFRG', 'Deauville-Saint-Gatien'),
(@root, 567, 'LYN', 'LFLY', 'Lyon-Bron'),
(@root, 568, 'FNA', 'GFLL', 'Freetown-Lungi International'),
(@root, 569, 'KIR', 'EIKY', 'Kerry'),
(@root, 570, 'OVD', 'LEAS', 'Asturias'),
(@root, 571, 'LCK', 'KLCK', 'Columbus-Rickenbacker International'),
(@root, 572, 'QKL', 'EDKK', 'Köln Hauptbahnhof'),
(@root, 573, 'AUS', 'KAUS', 'Austin-Robert Mueller Municipal'),
(@root, 574, 'SJC', 'KSJC', 'San Jose-Norman Y. Mineta International'),
(@root, 575, 'BLK', 'EGNH', 'Blackpool-International'),
(@root, 576, 'SGD', 'EKSB', 'Sonderborg'),
(@root, 577, 'BXO', 'LSZC', 'Buochs'),
(@root, 578, 'CGO', 'ZHCC', 'Zhengzhou-Xinzheng International'),
(@root, 579, 'TNG', 'GMTT', 'Tanger'),
(@root, 580, 'PXO', 'LPPS', 'Porto Santo Madeira'),
(@root, 581, 'VBS', 'LIPO', 'Brescia-Montichiari'),
(@root, 591, 'GRS', 'LIRS', 'Grosetto-Corrado Baccarini'),
(@root, 594, 'AZI', 'OMAD', 'Abu Dhabi-Al Bateen Executive'),
(@root, 596, 'MME', 'EGNV', 'Durham-Tees Valley'),
(@root, 597, 'PAP', 'MTPP', 'Port au Prince-Toussaint Louverture Internati'),
(@root, 599, 'KYA', 'LTAN', 'Konya'),
(@root, 608, 'CLY', 'LFKC', 'Calvi-Sainte-Catherine'),
(@root, 609, 'NQY', 'EGHQ', 'Newquay'),
(@root, 610, 'MHG', 'EDFM', 'Mannheim-City Airport'),
(@root, 611, 'ORY', 'LFPO', 'Paris-Orly'),
(@root, 612, 'EAS', 'LESO', 'San Sebastian'),
(@root, 613, 'VXO', 'ESMX', 'Vaxjo'),
(@root, 614, 'SBK', 'LFRT', 'Saint-Brieuc-Armor'),
(@root, 615, 'XXX', 'XXXX', 'Cancelled'),
(@root, 616, 'YQX', 'CYQX', 'Gander-International'),
(@root, 617, 'GIB', 'LXGB', 'Gibraltar'),
(@root, 620, 'NIM', 'DRRN', 'Niamey-Diori Hamani International'),
(@root, 621, 'RMI', 'LIPR', 'Rimini-Federico Fellini International');

TRUNCATE `visits`;

INSERT INTO `visits`(`aircraft`, `num`, `current`)
SELECT
	`flights`.`aircraft` AS `aircraft`,
	COUNT(`flights`.`scheduled`) AS `num`,
	MAX(`flights`.`scheduled`) AS `current`
FROM
(
	SELECT `direction`, `scheduled`, `aircraft`
	FROM `flights`
	WHERE `aircraft` IS NOT NULL

	UNION ALL

	SELECT `direction`,`scheduled`, `aircraft`
	FROM `history`
	WHERE `aircraft` IS NOT NULL
) AS `flights`
LEFT JOIN `aircrafts`
	   ON `aircrafts`.`id`=`flights`.`aircraft`
WHERE `direction`='arrival'
GROUP BY `aircraft`;
