/******************************************************************************
 *
 *       project: FRA-flights Live Schedule
 *
 *       $Author$
 *         $Date$
 *          $Rev$
 *
 ******************************************************************************
 *
 * Copyright © Tobias Kühne
 *
 * You may use and distribute this software free of charge for non-commercial
 * purposes. The software must be distributed in its entirety, i.e. containing
 * ALL binary and source files without modification.
 * Publication of modified versions of the source code provided herein,
 * is permitted only with the author's written consent. In this case the
 * copyright notice must not be removed or altered, all modifications to the
 * source code must be clearly marked as such.
 *
 ******************************************************************************/

DROP DATABASE IF EXISTS `fra-schedule`;

CREATE DATABASE IF NOT EXISTS `fra-schedule` CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci';
USE `fra-schedule`;

/******************************************************************************
 * Tables
 ******************************************************************************/

CREATE TABLE IF NOT EXISTS `airlines`
(
	`id` integer NOT NULL AUTO_INCREMENT,
	`code` varchar(3),
	`name` varchar(128),
	PRIMARY KEY (`id`),
	CONSTRAINT `unique: code` UNIQUE (`code`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `models`
(
	`id` integer NOT NULL AUTO_INCREMENT,
	`icao` varchar(4) NOT NULL,
	`name` varchar(96) NOT NULL,
	PRIMARY KEY (`id`),
	CONSTRAINT `unique:icao` UNIQUE (`icao`)
) COMMENT = 'http://www.airlinecodes.co.uk'
ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `aircrafts`
(
	`id` integer NOT NULL AUTO_INCREMENT,
	`reg` varchar(8) NOT NULL,
	`model` integer NOT NULL,
	PRIMARY KEY (`id`),
	CONSTRAINT `unique:reg` UNIQUE (`reg`),
	FOREIGN KEY(`model`) REFERENCES `models`(`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `airports`
(
	`id` integer NOT NULL AUTO_INCREMENT,
	`iata` varchar(3) NULL,
	`icao` varchar(4) NOT NULL,
	`name` varchar(255) NOT NULL,
	PRIMARY KEY (`id`),
	CONSTRAINT `unique:icao` UNIQUE(`icao`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `flights`
(
	`id` integer NOT NULL AUTO_INCREMENT,
	`type` enum('pax-regular', 'cargo', 'ferry') NOT NULL DEFAULT 'pax-regular',
	`direction` enum('arrival', 'departure') NOT NULL,
	`airline` integer NOT NULL,
	`code` varchar(6) NOT NULL,
	`scheduled` datetime NOT NULL,
	`expected` timestamp NULL DEFAULT NULL,
	`airport` integer DEFAULT NULL,
	`model` integer DEFAULT NULL,
	`aircraft` integer DEFAULT NULL,
	PRIMARY KEY (`id`),
	CONSTRAINT `unique:direction, airline, code, scheduled` UNIQUE (`direction`, `airline`, `code`, `scheduled`),
	FOREIGN KEY(`airline`) REFERENCES `airlines`(`id`),
	FOREIGN KEY(`airport`) REFERENCES `airports`(`id`),
	FOREIGN KEY(`model`) REFERENCES `models`(`id`),
	FOREIGN KEY(`aircraft`) REFERENCES `aircrafts`(`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `users` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `email` varchar(255) NOT NULL,
  `name` varchar(64) NOT NULL,
  `salt` varchar(64) NOT NULL,
  `passwd` varchar(64) NOT NULL,
  `token` varchar(64) NULL DEFAULT NULL,
  `token_type` enum('none', 'activation', 'password') NOT NULL,
  `token_expires` timestamp NULL DEFAULT NULL,
  `timezone` smallint DEFAULT 3600,
  `language` varchar(2) NOT NULL DEFAULT 'en',
  `ip` varchar(16) NOT NULL,	/* at the time of registration */
  PRIMARY KEY (`id`),
  UNIQUE KEY `name` (`name`),
  UNIQUE KEY `email` (`email`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `watchlist` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `user` int(11) NOT NULL,
  `reg` varchar(8) NOT NULL,
  `comment` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `user, reg` (`user`, `reg`),
  FOREIGN KEY(`user`) REFERENCES `users`(`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

/******************************************************************************
 * Triggers
 ******************************************************************************/

DELIMITER $$

CREATE TRIGGER `users:length`
BEFORE INSERT ON `users`
FOR EACH ROW
BEGIN
	IF LENGTH(NEW.`name`) < 4 THEN
		SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = '400: `users`.`name` must be at least 4 characters long.';
	END IF;
	IF LENGTH(NEW.`name`) > 64 THEN
		SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = '401: `users`.`name` must be no longer than 4 characters.';
	END IF;
	IF LENGTH(NEW.`salt`) != 64 THEN
		SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = '402: Salt is invalid.';
	END IF;
	IF LENGTH(NEW.`passwd`) != 64 THEN
		SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = '403: Password hash is invalid.';
	END IF;
END$$

/*
	Check:
	======

	INSERT INTO `users` (`name`, `email`, `passwd`, `salt`)
	VALUES(
		'zzz',
		'email.vaild.com',
		'80c93eaddcb3de5728c1fe86c62ac1bf5306134709dcf3770311548968926fae',
		'80c93eaddcb3de5728c1fe86c62ac1bf5306134709dcf3770311548968926fae');

	INSERT INTO `users` (`name`, `email`, `passwd`, `salt`)
	VALUES(
		'80c93eaddcb3de5728c1fe86c62ac1bf5306134709dcf3770311548968926fae0',
		'email.vaild.com',
		'80c93eaddcb3de5728c1fe86c62ac1bf5306134709dcf3770311548968926fae',
		'80c93eaddcb3de5728c1fe86c62ac1bf5306134709dcf3770311548968926fae');
	-- fails!

	INSERT INTO `users` (`name`, `email`, `passwd`, `salt`)
	VALUES(
		'erwin',
		'email.vaild.com',
		'',
		'80c93eaddcb3de5728c1fe86c62ac1bf5306134709dcf3770311548968926fae');

	INSERT INTO `users` (`name`, `email`, `passwd`, `salt`)
	VALUES(
		'erwin',
		'email.vaild.com',
		'80c93eaddcb3de5728c1fe86c62ac1bf5306134709dcf3770311548968926fae',
		'');
*/

CREATE TRIGGER `users:token`
BEFORE UPDATE ON `users`
FOR EACH ROW
BEGIN
	IF (NOT NEW.`token` IS NULL)
		AND NEW.`token_expires` IS NULL THEN
		SET NEW.`token_expires` = FROM_UNIXTIME(UNIX_TIMESTAMP(UTC_TIMESTAMP()) + 1 * 3600);
	END IF;
END$$

/*
	Check:
	======

	UPDATE `users` SET `token`='80c93eaddcb3de5728c1fe86c62ac1bf5306134709dcf3770311548968926fae'
		WHERE `id`=245;
*/

DELIMITER ;

/******************************************************************************
 * Indices
 ******************************************************************************/

CREATE INDEX `flights:scheduled` ON `flights`(`scheduled` ASC);
CREATE INDEX `flights:code` ON `flights`(`code` ASC);
CREATE INDEX `flights:direction` ON `flights`(`direction` ASC);
CREATE INDEX `watchlist:user` ON `watchlist`(`user` ASC);
CREATE INDEX `watchlist:reg` ON `watchlist`(`reg` ASC);

/******************************************************************************
 * Data
 ******************************************************************************/

INSERT INTO `airlines`(`code`, `name`)
VALUES
('A3',  'Aegean Airlines'),
('AA',  'American Airlines'),
('AB',  'Airberlin'),
('AC',  'Air Canada'),
('AEE', 'Aegean Airlines'),
('AF',  'Air France'),
('AH',  'Air Algerie'),
('AI',  'Air India'),
('AP',  'Air One'),
('AT',  'Royal Air Maroc'),
('AY',  'Finnair'),
('AZ',  'Alitalia'),
('BA',  'British Airways'),
('BD',  'British Midland International'),
('BE',  'Flybe'),
('BPA', 'Blue Panorama Airlines'),
('BRU', 'Belavia'),
('BT',  'Air Baltic'),
('BUC', 'Bulgarian Air Charter'),
('CA',  'Air China'),
('CAI', 'Corendon Airlines'),
('CFE', 'BA CityFlyer'),
('CI',  'China Airlines'),
('CX',  'Cathay Pacific Airways'),
('CY',  'Cyprus Airways'),
('DE',  'Condor'),
('DL',  'Delta Air Lines'),
('DLN', 'Dalmatian'),
('EI',  'Aer Lingus'),
('EK',  'Emirates'),
('EN',  'Air Dolomiti'),
('ERT', 'Eritrean Airlines'),
('ET',  'Ethiopian Airlines'),
('EY',  'Etihad Airways'),
('FB',  'Bulgaria Air'),
('FHY', 'Freebird Airlines'),
('FI',  'Icelandair'),
('FV',  'Rossiya'),
('GF',  'Gulf Air'),
('GH',  'Globus'),
('GHY', 'German Sky Airlines '),
('GWI', 'Germanwings'),
('GXL', 'XL Airways Germany'),
('HCC', 'Holidays Czech Airlines'),
('HG',  'NIKI'),
('HY',  'Uzbekistan Airways'),
('IB',  'Iberia'),
('IR',  'Iran Air'),
('IY',  'Yemenia Yemen Airways'),
('IZ',  'Arkia Israel Airlines'),
('JA',  'B&H Airlines'),
('JFU', 'Jet4you'),
('JJ',  'TAM Linhas Aéreas'),
('JL',  'JAL Japan Airlines'),
('JU',  'JAT Airways'),
('KC',  'Air Astana'),
('KE',  'Korean Air'),
('KIL', 'Kuban Airlines'),
('KK',  'Atlasjet Airlines'),
('KL',  'KLM Royal Dutch Airlines'),
('KM',  'Air Malta'),
('KRP', 'Carpatair'),
('KU',  'Kuwait Airways'),
('LA',  'LAN Airlines'),
('LBT', 'Nouvelair Tunisie'),
('LG',  'Luxair'),
('LH',  'Lufthansa'),
('LO',  'LOT Polish Airlines'),
('LV',  'Albanian Airlines'),
('LX',  'Swiss International Air Lines'),
('LY',  'El Al Israel Airlines'),
('ME',  'MEA Middle East Airlines'),
('MH',  'Malaysia Airlines'),
('MHK', 'Alnaser Airlines'),
('MK',  'Air Mauritius'),
('MLD', 'Air Moldova'),
('MS',  'Egypt Air'),
('MSC', 'Air Cairo'),
('MU',  'China Eastern Airlines'),
('NH',  'ANA'),
('OK',  'CSA Czech Airlines'),
('OLT', 'OLT Express'),
('OM',  'MIAT Mongolian Airlines'),
('OS',  'Austrian Airlines Group'),
('OU',  'Croatia Airlines'),
('OZ',  'Asiana Airlines'),
('PGT', 'Pegasus Airlines'),
('PHW', 'Ave.com'),
('PK',  'PIA Pakistan International Airlines'),
('PS',  'Ukraine International Airlines'),
('QB',  'Sky Georgia'),
('QF',  'Qantas Airways'),
('QR',  'Qatar Airways'),
('RB',  'Syrianair'),
('RJ',  'Royal Jordanian'),
('RKM', 'RAK Airways'),
('RNV', 'Armavia'),
('RO',  'Tarom'),
('SA',  'South African Airways'),
('SBI', 'S7 Airlines'),
('SK',  'SAS Scandinavian Airlines'),
('SMR', 'Somon Air'),
('SOV', 'Saravia-Saratov Airlines'),
('SP',  'SATA Internacional'),
('SQ',  'Singapore Airlines'),
('SU',  'Aeroflot'),
('SUW', 'Sunny Airways'),
('SV',  'Saudi Arabian Airlines'),
('SW',  'Air Namibia'),
('TG',  'Thai Airways International'),
('TGZ', 'Georgian Airways'),
('TK',  'Turkish Airlines'),
('TP',  'TAP Portugal'),
('TRK', 'Turkuaz Airlines'),
('TS',  'Air Transat'),
('TU',  'Tunis Air'),
('TUA', 'Turkmenistan Airlines'),
('TUI', 'TUIfly'),
('TWI', 'Tailwind Havayollari'),
('UA',  'United Airlines'),
('UDN', 'Dniproavia'),
('UL',  'Srilankan Airlines'),
('UN',  'Transaero Airlines'),
('US',  'US Airways'),
('VIM', 'Air VIA Bulgarian'),
('VLM', 'VLM Airlines'),
('VN',  'Vietnam Airlines'),
('VQ',  'FlyHellas.com'),
('WY',  'Oman Air'),
('X3',  'TUIfly'),
('XG',  'SunExpress Deutschland'),
('XQ',  'SunExpress'),
('YM',  'Montenegro Airlines'),
('ZY',  'Sky Airlines'),
('ZZ',  'ZZ'),
('JP',  'Adria Airways'),
('HU',  'Hainan Airlines'),
('ST',  'Germania'),
('EW',  'Eurowings'),
('4U',  'Germanwings'),
('EZE', 'Eastern Airways'),
('MON', 'Monarch Airlines'),
('IFA', 'FAI Airservice'),
('BV',  'Blue Panorama Airlines'),
('TFL', 'Arkefly'),
('AEY', 'Air Italy'),
('DWT', 'Darwin Airline'),
('YW',  'Air Nostrum'),
('OHY', 'Onur Air'),
('FPO', 'Europe Airpost'),
('JTG', 'Jet Time'),
('EXS', 'Jet2.com'),
('HAY', 'Hamburg Airways'),
('EZ',  'Evergreen International Airlines'),
('HV',  'Transavia Airlines'),
('VPA', 'VIP Wings'),
('JAF', 'JetAirFly'),
('BOX', 'Aerologic'),
('UC',  'LAN Cargo'),
('ACX', 'ACG Air Cargo Germany'),
('BR',  'EVA Air'),
('ABW', 'AirBridgeCargo'),
('FX',  'FedEx'),
('RGN', 'Cygnus Air'),
('CZ',  'China Southern Airlines'),
('ABR', 'Air Bridge Carriers'),
('AHO', 'Air Hamburg'),
('CSA', 'Czech Airlines'),
('DLH', 'Lufthansa'),
('ETD', 'Etihad Airways'),
('EXH', 'Executive AG'),
('EXT', 'Nightexpress'),
('FFD', 'Stuttgarter Flugdienst'),
('FMY', 'Aviation Legere de l''Armee de Terre'),
('IAM', 'Aeronautica Militare Italiana'),
('JEI', 'Jet Executive International Charter'),
('KAC', 'Kuwait Airways'),
('KZR', 'Air Astana'),
('LNX', 'London Executive Aviation - LEA'),
('LZB', 'Bulgaria Air'),
('MAS', 'Malaysia Airlines'),
('MGR', 'Magna Air'),
('NJE', 'NetJets Transportes Aereos'),
('QAJ', 'Quick Air Jet Charter'),
('RZO', 'SATA Internacional'),
('SHY', 'Sky Airlines'),
('THY', 'Turkish Airlines'),
('AFL', 'Aeroflot'),
('AZG', 'Sakaviaservice'),
('CMB', 'US Transportation Command'),
('GTI', 'Atlas Air'),
('MNB', 'MNG Airlines'),
('YZR', 'Yangtze River Express Airlines'),
('AG',  'Affretair'),
('FRA', 'FR Aviation'),
('OAW', 'Helvetic'),
('AEA', 'Air Europa'),
('QS',  'Travel Servis/Smartwings'),
('BIE', 'Air Mediterranee'),
('I2',  'MunichAirlines'),
('HC',  'Aero Tropics'),
('BM',  'BM'),
('FQ',  'Thomas Cook Belgium Airlines'),
('IQ',  'Augsburg Airways'),
('ZZZ', 'ZZZ'),
('SWT', 'Swiftair'),
('XLF', 'XL Airways France'),
('FC',  'Flybe Nordic'),
('KZ',  'Nippon Cargo Airlines'),
('WDL', 'WDL Aviation'),
('VLG', 'Vueling')
;

INSERT INTO `models`(`icao`, `name`)
VALUES
('A124', 'Antonov AN-124 Ruslan'),
('A140', 'Antonov AN-140'),
('A148', 'Antonov AN-148'),
('A306', 'Airbus Industrie A300-600'),
('A30B', 'Airbus Industrie A300B2/B4/C4/F4'),
('A310', 'Airbus A310'),
('A318', 'Airbus A318'),
('A319', 'Airbus A319'),
('A320', 'Airbus A320-100/200'),
('A321', 'Airbus A321-100/200'),
('A330', 'Airbus A330 all models'),
('A332', 'Airbus A330-200'),
('A333', 'Airbus A330-300'),
('A340', 'Airbus A340 all models'),
('A342', 'Airbus A340-200'),
('A343', 'Airbus A340-300'),
('A345', 'Airbus A340-500'),
('A346', 'Airbus A340-600'),
('A388', 'Airbus A380-800'),
('A3ST', 'Airbus Industrie A300-600ST Beluga Freighter'),
('A748', 'Hawker Siddeley HS.748'),
('AC68', 'Gulfstream/Rockwell (Aero) Commander'),
('AC90', 'Gulfstream/Rockwell (Aero) Turbo Commander'),
('AN12', 'Antonov AN-12'),
('AN24', 'Antonov AN-24'),
('AN26', 'Antonov AN-26'),
('AN28', 'Antonov AN-28 / PZL Miele M-28 Skytruck'),
('AN30', 'Antonov AN-30'),
('AN32', 'Antonov AN-32'),
('AN72', 'Antonov AN-72 / AN-74'),
('AT43', 'Aerospatiale/Alenia ATR 42-300 / 320'),
('AT45', 'Aerospatiale/Alenia ATR 42-500'),
('AT72', 'Aerospatiale/Alenia ATR 72-200/210'),
('ATP', 'British Aerospace ATP'),
('B190', 'Beechcraft 1900/1900C/1900D'),
('B461', 'BAe 146-100'),
('B462', 'BAe 146-200'),
('B463', 'BAe 146-300'),
('B703', 'Boeing 707-300'),
('B712', 'Boeing 717'),
('B720', 'Boeing 720B'),
('B721', 'Boeing 727-100'),
('B722', 'Boeing 727-200'),
('B731', 'Boeing 737-100'),
('B732', 'Boeing 737-200'),
('B733', 'Boeing 737-300'),
('B734', 'Boeing 737-400'),
('B735', 'Boeing 737-500'),
('B736', 'Boeing 737-600'),
('B737', 'Boeing 737-700'),
('B738', 'Boeing 737-800'),
('B739', 'Boeing 737-900'),
('B741', 'Boeing 747-100'),
('B742', 'Boeing 747-200'),
('B743', 'Boeing 747-300'),
('B744', 'Boeing 747-400'),
('B748', 'Boeing 747-8I'),
('B74R', 'Boeing 747SR'),
('B752', 'Boeing 757-200'),
('B753', 'Boeing 757-300'),
('B762', 'Boeing 767-200'),
('B763', 'Boeing 767-300'),
('B764', 'Boeing 767-400'),
('B772', 'Boeing 777-200'),
('B773', 'Boeing 777-300'),
('B77L', 'Boeing 777-200LR'),
('B77W', 'Boeing 777-300ER'),
('B788', 'Boeing 787 "Dreamliner"'),
('BA11', 'British Aerospace (BAC) One Eleven'),
('BELF', 'Shorts SC-5 Belfast'),
('BN2P', 'Pilatus Britten-Norman BN-2A/B Islander'),
('C130', 'Lockheed L-182 / 282 / 382 (L-100) Hercules'),
('C212', 'CASA / IPTN 212 Aviocar'),
('C46', 'Curtiss C-46 Commando'),
('CL44', 'Canadair CL-44'),
('CL60', 'Canadair Challenger'),
('CN35', 'CASA / IPTN CN-235'),
('CONC', 'Aerospatiale/BAC Concorde'),
('CONI', 'Lockheed L-1049 Super Constellation'),
('COUC', 'Helio H-250 Courier / H-295 / 385 Super Courier'),
('CRJ1', 'Canadair Regional Jet 100'),
('CRJ2', 'Canadair Regional Jet 200'),
('CRJ7', 'Canadair Regional Jet 700'),
('CRJ9', 'Canadair Regional Jet 900'),
('CVLP', 'Convair CV-240/440'),
('CVLT', 'Convair CV-580/600/640'),
('D228', 'Fairchild Dornier Do.228'),
('D328', 'Fairchild Dornier Do.328'),
('DC10', 'Douglas DC-10'),
('DC3', 'Douglas DC-3'),
('DC6', 'Douglas DC6A/B/C'),
('DC85', 'Douglas DC-8-50 Freighter'),
('DC86', 'Douglas DC-8-62'),
('DC87', 'Douglas DC-8-71/72/73'),
('DC9', 'Douglas DC-9 all models'),
('DC91', 'Douglas DC-9-10'),
('DC92', 'Douglas DC-9-20'),
('DC93', 'Douglas DC-9-30'),
('DC94', 'Douglas DC-9-40'),
('DC95', 'Douglas DC-9-50'),
('DH2T', 'De Havilland Canada DHC-2 Turbo-Beaver'),
('DH8A', 'De Havilland Canada DHC-8-100 Dash 8 / 8Q'),
('DH8B', 'De Havilland Canada DHC-8-200 Dash 8 / 8Q'),
('DH8C', 'De Havilland Canada DHC-8-300 Dash 8 / 8Q'),
('DH8D', 'De Havilland Canada DHC-8-400 Dash 8Q'),
('DHC2', 'De Havilland Canada DHC-2 Beaver'),
('DHC3', 'De Havilland Canada DHC-3 Otter / Turbo Otter'),
('DHC4', 'De Havilland Canada DHC-4 Caribou'),
('DHC6', 'De Havilland Canada DHC-6 Twin Otter'),
('DHC7', 'De Havilland Canada DHC-7 Dash 7'),
('DOVE', 'De Havilland DH.104 Dove'),
('E110', 'Embraer EMB.110 Bandeirnate'),
('E120', 'Embraer EMB.120 Brasilia'),
('E135', 'Embraer RJ135'),
('E145', 'Embraer RJ145 Amazon'),
('E170', 'Embraer 170'),
('E190', 'Embraer 190'),
('F100', 'Fokker 100'),
('F27', 'Fokker F.27 Friendship / Fairchild F.27'),
('F28', 'Fokker F.28 Fellowship'),
('F50', 'Fokker 50'),
('F70', 'Fokker 70'),
('G159', 'Gulfstream Aerospace G-159 Gulfstream I'),
('G21', 'Grumman G.21 Goose'),
('G73T', 'Grumman G.73 Turbo Mallard'),
('GLEX', 'Canadair Global Express'),
('HERN', 'De Havilland DH.114 Heron'),
('I114', 'Ilyushin IL114'),
('IL18', 'Ilyushin IL18'),
('IL62', 'Ilyushin IL62'),
('IL76', 'Ilyushin IL76'),
('IL86', 'Ilyushin IL86'),
('IL96', 'Ilyushin IL96'),
('J328', 'Fairchild Dornier 328JET'),
('JS31', 'British Aerospace Jetstream 31'),
('JS32', 'British Aerospace Jetstream 32'),
('JS41', 'British Aerospace Jetstream 41'),
('JU52', 'Junkers Ju52/3M'),
('L101', 'Lockheed L-1011 1 / 50 / 100 / 150 / 200 / 250 Tristar'),
('L188', 'Lockheed L-188 Electra'),
('L410', 'LET 410'),
('LOAD', 'Ayres LM-200 Loadmaster'),
('MD11', 'McDonnell Douglas MD11'),
('MD80', 'McDonnell Douglas MD80'),
('MD81', 'McDonnell Douglas MD81'),
('MD82', 'McDonnell Douglas MD82'),
('MD83', 'McDonnell Douglas MD83'),
('MD87', 'McDonnell Douglas MD87'),
('MD88', 'McDonnell Douglas MD88'),
('MD90', 'McDonnell Douglas MD90'),
('MU2', 'Mitsubishi Mu-2'),
('N262', 'Aerospatiale (Nord) 262'),
('N74S', 'Boeing 747SP'),
('NOMA', 'Government Aircraft Factories N22B / N24A Nomad'),
('P68', 'Partenavia P.68'),
('PC12', 'Pilatus PC-12'),
('PC6T', 'Pilatus PC-6 Turbo Porter'),
('RJ1H', 'Avro RJ100 Avroliner'),
('RJ70', 'Avro RJ70 Avroliner'),
('RJ85', 'Avro RJ85 Avroliner'),
('RX1H', 'Avro RJX100'),
('RX85', 'Avro RJX85 	M B11 	BA11 	British Aerospace (BAC) One Eleven / RomBAC One Eleven'),
('S210', 'Aerospatiale (Sud Aviation) Se.210 Caravelle'),
('S601', 'Aerospatiale SN.601 Corvette'),
('SB20', 'Saab 2000'),
('SC7', 'Shorts SC-7 Skyvan'),
('SF34', 'Saab SF340A/B'),
('SH33', 'Shorts SD.330'),
('SH36', 'Shorts SD.360'),
('T134', 'Tupolev Tu134'),
('T154', 'Tupolev Tu154'),
('T204', 'Tupolev Tu-204 / Tu-214'),
('TRIS', 'Pilatus Britten-Norman BN-2A Mk III Trislander'),
('VISC', 'Vickers Viscount'),
('WW24', 'Israel Aircraft Industries 1124 Westwind'),
('Y12', 'Harbin Yunshuji Y12'),
('YK40', 'Yakovlev Yak 40'),
('YK42', 'Yakovlev Yak 42'),
('YS11', 'NAMC YS-11'),
('AT75', 'Aerospatiale/Alenia ATR 72-500'),
('AT76', 'Aerospatiale/Alenia ATR 72-600')
;

INSERT INTO `airports`(`iata`, `icao`, `name`)
VALUES
('ABV', 'DNAA', 'Abuja, Nigeria'),
('ABZ', 'EGPD', 'Aberdeen, Großbritannien'),
('ACC', 'DGAA', 'Accra, Ghana'),
('ACE', 'GCRR', 'Lanzarote, Spanien'),
('ADA', 'LTAF', 'Adana, Türkei'),
('ADB', 'LTBJ', 'Izmir, Türkei'),
('ADD', 'HAAB', 'Addis Abeba, Äthiopien'),
('AGA', 'GMAD', 'Agadir, Marokko'),
('AGP', 'LEMG', 'Malaga, Spanien'),
('ALA', 'UAAA', 'Almaty, Kasachstan'),
('ALG', 'DAAG', 'Algier, Algerien'),
('AMM', 'OJAI', 'Amman, Jordanien'),
('AMS', 'EHAM', 'Amsterdam, Niederlande'),
('ARN', 'ESSA', 'Stockholm, Schweden'),
('ASB', 'UTAA', 'Ashgabat, Turkmenistan'),
('ASM', 'HHAS', 'Asmara, Eritrea'),
('ASR', 'LTAU', 'Kayseri, Türkei'),
('ATH', 'LGAV', 'Athen, Griechenland'),
('ATL', 'KATL', 'Atlanta, USA'),
('AUH', 'OMAA', 'Abu Dhabi, Ver.Arab.Emirate'),
('AYT', 'LTAI', 'Antalya, Türkei'),
('BAH', 'OBBI', 'Bahrain, Bahrain'),
('BCN', 'LEBL', 'Barcelona, Spanien'),
('BEG', 'LYBE', 'Belgrad, Serbien'),
('BEY', 'OLBA', 'Beirut, Libanon'),
('BGI', 'TBPB', 'Barbados, Barbados'),
('BGO', 'ENBR', 'Bergen, Norwegen'),
('BGY', 'LIME', 'Bergamo-Orio AlSerio, Italien'),
('BHX', 'EGBB', 'Birmingham, Großbritannien'),
('BIO', 'LEBB', 'Bilbao, Spanien'),
('BJL', 'GBYD', 'Banjul, Gambia'),
('BKK', 'VTBS', 'Bangkok, Thailand'),
('BLL', 'EKBI', 'Billund, Dänemark'),
('BLQ', 'LIPE', 'Bologna, Italien'),
('BLR', 'VOBL', 'Bangalore, Indien'),
('BOG', 'SKBO', 'Bogota, Kolumbien'),
('BOM', 'VABB', 'Mumbai, Indien'),
('BOS', 'KBOS', 'Boston, USA'),
('BRE', 'EDDW', 'Bremen, Deutschland'),
('BRU', 'EBBR', 'Brüssel, Belgien'),
('BSL', 'LFSB', 'Basel, Schweiz'),
('BUD', 'LHBP', 'Budapest, Ungarn'),
('CAI', 'HECA', 'Kairo, Ägypten'),
('CAN', 'ZGGG', 'Guangzhou, China'),
('CCS', 'SVMI', 'Caracas, Venezuela'),
('CCU', 'VECC', 'Kolkata, Indien'),
('CDG', 'LFPG', 'Paris-Ch.De Gaulle, Frankreich'),
('CLT', 'KCLT', 'Charlotte, USA'),
('CMB', 'VCBI', 'Colombo, Sri Lanka'),
('CMN', 'GMMN', 'Casablanca, Marokko'),
('CPH', 'EKCH', 'Kopenhagen, Dänemark'),
('CPT', 'FACT', 'Kapstadt, Südafrika'),
('CTA', 'LICC', 'Catania, Italien'),
('CUN', 'MMUN', 'Cancun, Mexiko'),
('DAM', 'OSDI', 'Damaskus, Syrien'),
('DBV', 'LDDU', 'Dubrovnik, Kroatien'),
('DEL', 'VIDP', 'Delhi, Indien'),
('DEN', 'KDEN', 'Denver, USA'),
('DFW', 'KDFW', 'Dallas-Fort Worth, USA'),
('DJE', 'DTTJ', 'Djerba, Tunesien'),
('DME', 'UUDD', 'Moskau-Domodedovo, Russland'),
('DMM', 'OEDF', 'Dammam, Saudi-Arabien'),
('DOH', 'OTBD', 'Doha, Katar'),
('DRS', 'EDDC', 'Dresden, Deutschland'),
('DTW', 'KDTW', 'Detroit, USA'),
('DUB', 'EIDW', 'Dublin, Irland'),
('DUS', 'EDDL', 'Düsseldorf, Deutschland'),
('DXB', 'OMDB', 'Dubai, Ver.Arab.Emirate'),
('DYU', 'UTDD', 'Duschanbe, Tadschikistan'),
('EBL', 'ORER', 'Erbil, Irak'),
('EDI', 'EGPH', 'Edinburgh, Großbritannien'),
('EMA', 'EGNX', 'East Midlands, Großbritannien'),
('ESB', 'LTAC', 'Ankara, Türkei'),
('EWR', 'KEWR', 'New York-Newark, USA'),
('EZE', 'SAEZ', 'Buenos Aires, Argentinien'),
('FAO', 'LPFR', 'Faro, Portugal'),
('FCO', 'LIRF', 'Rom-Fiumicino, Italien'),
('FDH', 'EDNY', 'Friedrichshafen, Deutschland'),
('FLL', 'KFLL', 'Fort Lauderdale, USA'),
('FLR', 'LIRQ', 'Florenz, Italien'),
('FMO', 'EDDG', 'Münster Osnabrück, Deutschland'),
('FNC', 'LPMA', 'Madeira, Portugal'),
('FUE', 'GCFV', 'Fuerteventura, Spanien'),
('GDN', 'EPGD', 'Gdansk/Danzig, Polen'),
('GIG', 'SBGL', 'Rio de Janeiro, Brasilien'),
('GOI', 'VAGO', 'Goa, Indien'),
('GOT', 'ESGG', 'Göteborg, Schweden'),
('GRU', 'SBGR', 'Sao Paulo-Guarulhos, Brasilien'),
('GRZ', 'LOWG', 'Graz, Österreich'),
('GVA', 'LSGG', 'Genf, Schweiz'),
('GZT', 'LTAJ', 'Gaziantep, Türkei'),
('HAJ', 'EDDV', 'Hannover, Deutschland'),
('HAM', 'EDDH', 'Hamburg, Deutschland'),
('HAN', 'VVNB', 'Hanoi, Vietnam'),
('HAV', 'MUHA', 'Havanna, Kuba'),
('HEL', 'EFHK', 'Helsinki, Finnland'),
('HGH', 'ZSHC', 'Hangzhou, China'),
('HKG', 'VHHH', 'Hongkong, Hong Kong'),
('HKT', 'VTSP', 'Phuket'),
('HND', 'RJTT', 'Tokio Haneda, Japan'),
('HOG', 'MUHG', 'Holguin, Kuba'),
('HRG', 'HEGN', 'Hurghada, Ägypten'),
('IAD', 'KIAD', 'Washington, USA'),
('IAH', 'KIAH', 'Houston, USA'),
('ICN', 'RKSI', 'Seoul-Incheon, Korea-Süd'),
('IKA', 'OIIE', 'Teheran ImamKhomeini, Iran'),
('INN', 'LOWI', 'Innsbruck, Österreich'),
('ISB', 'OPRN', 'Islamabad, Pakistan'),
('IST', 'LTBA', 'Istanbul, Türkei'),
('JED', 'OEJN', 'Jeddah, Saudi-Arabien'),
('JFK', 'KJFK', 'New York-J.F.Kennedy, USA'),
('JNB', 'FAJS', 'Johannesburg, Südafrika'),
('JRO', 'HTKJ', 'Kilimanjaro, Tansania'),
('KBP', 'UKBB', 'Kiew-Borispol, Ukraine'),
('KEF', 'BIKF', 'Reykjavik, Island'),
('KIV', 'LUKK', 'Chisinau, Moldawien'),
('KIX', 'RJBB', 'Osaka, Japan'),
('KLU', 'LOWK', 'Klagenfurt, Österreich'),
('KRK', 'EPKK', 'Krakau, Polen'),
('KRT', 'HSSS', 'Khartoum, Sudan'),
('KTW', 'EPKT', 'Kattowitz, Polen'),
('KUL', 'WMKK', 'Kuala Lumpur, Malaysia'),
('KWI', 'OKBK', 'Kuwait, Kuwait'),
('KZN', 'UWKD', 'Kazan, Russland'),
('LAD', 'FNLU', 'Luanda, Angola'),
('LAS', 'KLAS', 'Las Vegas, USA'),
('LAX', 'KLAX', 'Los Angeles, USA'),
('LCA', 'LCLK', 'Larnaca, Zypern'),
('LCY', 'EGLC', 'London-City Airport, Großbritannien'),
('LED', 'ULLI', 'Sankt Petersburg, Russland'),
('LEJ', 'EDDP', 'Leipzig Halle, Deutschland'),
('LGW', 'EGKK', 'London-Gatwick, Großbritannien'),
('LHE', 'OPLA', 'Lahore, Pakistan'),
('LHR', 'EGLL', 'London-Heathrow, Großbritannien'),
('LIN', 'LIML', 'Mailand-Linate, Italien'),
('LIS', 'LPPT', 'Lissabon, Portugal'),
('LJU', 'LJLJ', 'Ljubljana, Slowenien'),
('LNZ', 'LOWL', 'Linz, Österreich'),
('LOS', 'DNMM', 'Lagos, Nigeria'),
('LPA', 'GCLP', 'Las Palmas, Spanien'),
('LRM', 'MDLR', 'La Romana, Dominikan. Rep.'),
('LUX', 'ELLX', 'Luxemburg, Luxemburg'),
('LXR', 'HELX', 'Luxor, Ägypten'),
('LYS', 'LFLL', 'Lyon, Frankreich'),
('MAA', 'VOMM', 'Chennai, Indien'),
('MAD', 'LEMD', 'Madrid, Spanien'),
('MAN', 'EGCC', 'Manchester, Großbritannien'),
('MBA', 'HKMO', 'Mombasa, Kenia'),
('MBJ', 'MKJS', 'Montego Bay, Jamaika'),
('MCO', 'KMCO', 'Orlando, USA'),
('MCT', 'OOMS', 'Muscat, Oman'),
('MEX', 'MMMX', 'Mexico City, Mexiko'),
('MIA', 'KMIA', 'Miami, USA'),
('MLA', 'LMML', 'Malta, Malta'),
('MLE', 'VRMM', 'Male, Malediven'),
('MRS', 'LFML', 'Marseille, Frankreich'),
('MRU', 'FIMP', 'Mauritius, Mauritius'),
('MSQ', 'UMMS', 'Minsk, Weißrussland'),
('MUC', 'EDDM', 'München, Deutschland'),
('MXP', 'LIMC', 'Mailand-Malpensa, Italien'),
('NAP', 'LIRN', 'Neapel, Italien'),
('NBE', 'DTNZ', 'Enfidha, Tunesien'),
('NBO', 'HKJK', 'Nairobi, Kenia'),
('NCE', 'LFMN', 'Nizza, Frankreich'),
('NDR', 'GMFN', 'Nador, Marokko'),
('NGO', 'RJGG', 'Nagoya, Japan'),
('NKG', 'ZSNJ', 'Nanking, China'),
('NRT', 'RJAA', 'Tokio Narita, Japan'),
('NUE', 'EDDN', 'Nürnberg, Deutschland'),
('OPO', 'LPPR', 'Porto, Portugal'),
('ORD', 'KORD', 'Chicago, USA'),
('OSL', 'ENGM', 'Oslo, Norwegen'),
('OTP', 'LROP', 'Bukarest, Rumänien'),
('OVB', 'UNNT', 'Novosibirsk, Russland'),
('PEE', 'USPP', 'Perm, Russland'),
('PEK', 'ZBAA', 'Peking, China'),
('PFO', 'LCPH', 'Paphos, Zypern'),
('PHC', 'DNPO', 'Port Harcourt, Nigeria'),
('PHL', 'KPHL', 'Philadelphia, USA'),
('PMI', 'LEPA', 'Palma de Mallorca, Spanien'),
('PNQ', 'VAPO', 'Pune, Indien'),
('PNR', 'FCPP', 'Pointe Noire, Kongo'),
('POP', 'MDPP', 'Puerto Plata, Dominikan. Rep.'),
('POZ', 'EPPO', 'Poznan/Posen, Polen'),
('PRG', 'LKPR', 'Prag, Tschechien'),
('PRN', 'LYPR', 'Pristina, Serbien'),
('PTY', 'MPTO', 'Panama City, Panama'),
('PUJ', 'MDPC', 'Punta Cana, Dominikan. Rep.'),
('PVG', 'ZSPD', 'Shanghai PuDong, China'),
('REC', 'SBRF', 'Recife, Brasilien'),
('RIX', 'EVRA', 'Riga, Lettland'),
('RMF', 'HEMA', 'Marsa Alam, Ägypten'),
('ROV', 'URRR', 'Rostow, Russland'),
('RUH', 'OERK', 'Riad, Saudi-Arabien'),
('RZE', 'EPRZ', 'Rzeszow, Polen'),
('SAH', 'OYSN', 'Sanaa, Jemen'),
('SAW', 'LTFJ', 'Istanbul S-Gokcen, Türkei'),
('SCL', 'SCEL', 'Santiago de Chile, Chile'),
('SDQ', 'MDSD', 'Santo Domingo, Dominikan. Rep.'),
('SEA', 'KSEA', 'Seattle, USA'),
('SFO', 'KSFO', 'San Francisco, USA'),
('SGN', 'VVTS', 'Ho Chi Minh City, Vietnam'),
('SHE', 'ZYTX', 'Shenyang, China'),
('SIN', 'WSSS', 'Singapur, Singapur'),
('SJO', 'MROC', 'San Jose, Costa Rica'),
('SJU', 'TJSJ', 'San Juan, Puerto Rico'),
('SKG', 'LGTS', 'Thessaloniki, Griechenland'),
('SOF', 'LBSF', 'Sofia, Bulgarien'),
('SOU', 'EGHI', 'Southampton, Großbritannien'),
('SPC', 'GCLA', 'La Palma, Spanien'),
('SPU', 'LDSP', 'Split, Kroatien'),
('SSA', 'SBSV', 'Salvador, Brasilien'),
('SSG', 'FGSL', 'Malabo, Äquator.-Guinea'),
('SSH', 'HESH', 'Sharm El Sheik, Ägypten'),
('STR', 'EDDS', 'Stuttgart, Deutschland'),
('SVG', 'ENZV', 'Stavanger, Norwegen'),
('SVO', 'UUEE', 'Moskau-Sheremetyevo, Russland'),
('SVX', 'USSS', 'Ekaterinburg, Russland'),
('SYD', 'YSSY', 'Sydney, Australien'),
('SZG', 'LOWS', 'Salzburg, Österreich'),
('TAB', 'TTCP', 'Tobago, Trinidad Tobago'),
('TAS', 'UTTT', 'Taschkent, Usbekistan'),
('TFS', 'GCTS', 'Teneriffa-Sur Reina, Spanien'),
('TGD', 'LYPG', 'Podgorica, Montenegro'),
('TIP', 'HLLT', 'Tripolis, Libyen'),
('TLL', 'EETN', 'Tallinn, Estland'),
('TLS', 'LFBO', 'Toulouse, Frankreich'),
('TLV', 'LLBG', 'Tel Aviv, Israel'),
('TPE', 'RCTP', 'Taipeh, Taiwan'),
('TRN', 'LIMF', 'Turin, Italien'),
('TSE', 'UACC', 'Astana, Kasachstan'),
('TUN', 'DTTA', 'Tunis, Tunesien'),
('TXL', 'EDDT', 'Berlin-Tegel, Deutschland'),
('UVF', 'TLPL', 'Saint Lucia, Saint Lucia'),
('VCE', 'LIPZ', 'Venedig, Italien'),
('VIE', 'LOWW', 'Wien, Österreich'),
('VNO', 'EYVI', 'Vilnius, Litauen'),
('VRA', 'MUVR', 'Varadero, Kuba'),
('VRN', 'LIPX', 'Verona, Italien'),
('WAW', 'EPWA', 'Warschau, Polen'),
('WDH', 'FYWH', 'Windhuk, Namibia'),
('WRO', 'EPWR', 'Wroclaw/Breslau, Polen'),
('XRY', 'LEJR', 'Jerez de la Frontera, Spanien'),
('YOW', 'CYOW', 'Ottawa, Kanada'),
('YUL', 'CYUL', 'Montreal-Trudeau, Kanada'),
('YVR', 'CYVR', 'Vancouver, Kanada'),
('YYC', 'CYYC', 'Calgary, Kanada'),
('YYZ', 'CYYZ', 'Toronto, Kanada'),
('ZAD', 'LDZD', 'Zadar, Kroatien'),
('ZAG', 'LDZA', 'Zagreb, Kroatien'),
('ZRH', 'LSZH', 'Zürich, Schweiz'),
('SEZ', 'FSIA', 'Mahe, Seychellen'),
('AJR', 'ESNX', 'Arvidsjaur, Schweden'),
('BIA', 'LFKB', 'Bastia, Frankreich'),
('PDL', 'LPPD', 'Ponta Delgada, Portugal'),
('GLA', 'EGPF', 'Glasgow, Großbritannien'),
('ANU', 'TAPA', 'Antigua, Antigua'),
('RKT', 'OMRK', 'Ras al Khaymah, Ver.Arab.Emirate'),
('COK', 'VOCI', 'Cochin, Indien'),
('ZNZ', 'HTZA', 'Sansibar, Tansania'),
('CGN', 'EDDK', 'Köln Bonn, Deutschland'),
('VKO', 'UUWW', 'Moskau-Vnukovo, Russland'),
('GOA', 'LIMJ', 'Genua, Italien'),
('TRD', 'ENVA', 'Trondheim, Norwegen'),
('PMO', 'LICJ', 'Palermo, Italien'),
('OLB', 'LIEO', 'Olbia, Italien'),
('KUF', 'UWWW', 'Samara, Russland'),
('GOJ', 'UWGG', 'N. Novgorod, Russland'),
('CLE', 'KCLE', 'Cleveland, USA'),
('GWT', 'EDXW', 'Westerland, Deutschland'),
('VAR', 'LBWN', 'Varna, Bulgarien'),
('PHX', 'KPHX', 'Phoenix, USA'),
('ORN', 'DAOO', 'Oran, Algerien'),
('SAN', 'KSAN', 'San Diego-Lindberg, USA'),
('TAO', 'ZSQD', 'Qingdao, China'),
('SZF', 'LTFH', 'Samsun-Carsamba, Türkei'),
('RDU', 'KRDU', 'Raleigh/Durham, USA'),
('TBS', 'UGTB', 'Tbilisi, Georgien'),
('QSH', 'DUMI', 'Seeheim, Deutschland'),
('ALC', 'LEAL', 'Alicante, Spanien'),
('MAO', 'SBEG', 'Manaus, Brasilien'),
('HER', 'LGIR', 'Heraklion, Griechenland'),
('RLG', 'ETNL', 'Rostock Laage, Deutschland'),
('ERF', 'EDDE', 'Erfurt, Deutschland'),
('SOB', 'LHSM', 'Sarmellek, Ungarn'),
('BSB', 'SBBR', 'Brasilia, Brasilien'),
('DLM', 'LTBS', 'Dalaman, Türkei'),
('TCE', 'LRTC', 'Tulcea Cataloi, Rumänien'),
('RHO', 'LGRP', 'Rhodos, Griechenland'),
('KGS', 'LGKO', 'Kos, Griechenland'),
('UGC', 'UTNU', 'Urgench, Usbekistan'),
('CFU', 'LGKR', 'Kerkyra, Griechenland'),
('ANC', 'PANC', 'Anchorage, USA'),
('IBZ', 'LEIB', 'Ibiza, Spanien'),
('YHZ', 'CYHZ', 'Halifax, Kanada'),
('REU', 'LERS', 'Reus, Spanien'),
('PAE', 'KPAE', 'Everett, USA'),
('SID', 'GVAC', 'Sal, Kap Verde'),
('VLC', 'LEVC', 'Valencia, Spanien'),
('BJV', 'LTFE', 'Bodrum, Türkei'),
('BVC', 'GVBA', 'Boa Vista, Kap Verde'),
('GPA', 'LGRX', 'Patras, Griechenland'),
('PVK', 'LGPZ', 'Preveza/Lefkas, Griechenland'),
('SIP', 'UKFF', 'Simferopol, Ukraine'),
('BOJ', 'LBBG', 'Burgas, Bulgarien'),
('HDF', 'EDAH', 'Heringsdorf, Deutschland'),
('RJK', 'LDRI', 'Rijeka, Kroatien'),
('MLX', 'LTAT', 'Malatya, Türkei'),
('JER', 'EGJJ', 'Jersey, Großbritannien'),
('SUF', 'LICA', 'Lamezia Terme, Italien'),
('MAH', 'LEMH', 'Menorca, Spanien'),
('SMI', 'LGSM', 'Samos, Griechenland'),
('CHQ', 'LGSA', 'Chania, Griechenland'),
('FRA', 'EDDF', 'Frankfurt, Deutschland'),
('JTR', 'LGSR', 'Santorini, Griechenland'),
('MIR', 'DTMB', 'Monastir, Tunesien'),
('KVA', 'LGKV', 'Kavala, Griechenland'),
('ZTH', 'LGZA', 'Zakynthos, Griechenland'),
('JMK', 'LGMK', 'Mykonos, Griechenland'),
('LDE', 'LFBT', 'Lourdes, Frankreich'),
('YXY', 'CYXY', 'Whitehorse, Kanada')
;
