/******************************************************************************
 *
 * Copyright © Tobias Kühne
 *
 * You may use and distribute this software free of charge for non-commercial
 * purposes. The software must be distributed in its entirety, i.e. containing
 * ALL binary and source files without modification.
 * Publication of modified versions of the source code provided herein,
 * is permitted only with the author's written consent. In this case the
 * copyright notice must not be removed or altered, all modifications to the
 * source code must be clearly marked as such.
 *
 ******************************************************************************/

DROP DATABASE IF EXISTS `flederwiesel_fra-schedule`;

CREATE DATABASE `flederwiesel_fra-schedule` CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci';
USE `flederwiesel_fra-schedule`;

/******************************************************************************
 * Tables
 ******************************************************************************/

CREATE TABLE IF NOT EXISTS `users`
(
	`id` integer NOT NULL AUTO_INCREMENT,
	`email` varchar(255) NOT NULL,
	`name` varchar(64) NOT NULL,
	`salt` varchar(64) NOT NULL,
	`passwd` varchar(64) NOT NULL,
	`token` varchar(64) NULL DEFAULT NULL,
	`token_type` enum('none', 'activation', 'password') NOT NULL,
	`token_expires` timestamp NULL DEFAULT NULL,
	# ALTER TABLE `users` ADD COLUMN `last login` timestamp NULL DEFAULT NULL
	`last login` timestamp NULL DEFAULT NULL,
	`timezone` smallint DEFAULT 3600,
	`language` varchar(2) NOT NULL DEFAULT 'en',
	`ip` varchar(16) NOT NULL,	/* at the time of registration */
	`tm-` integer NOT NULL DEFAULT 0,
	`tm+` integer NOT NULL DEFAULT 3600,
	`tt-` integer NOT NULL DEFAULT 0,
	`tt+` integer NOT NULL DEFAULT 86400,
	`notification-from` time NOT NULL DEFAULT '00:00',
	`notification-until` time NOT NULL DEFAULT '00:00',
	# ALTER TABLE `users` ADD COLUMN `send mail` BOOL DEFAULT TRUE
	`send mail` BOOL DEFAULT TRUE,
	# ALTER TABLE `users` ADD COLUMN `notification-timefmt` varchar(24)
	`notification-timefmt` varchar(24) DEFAULT NULL,
	PRIMARY KEY (`id`),
	UNIQUE KEY `name` (`name`),
	UNIQUE KEY `email` (`email`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `groups`
(
	`id` integer NOT NULL AUTO_INCREMENT,
	`name` varchar(64) NOT NULL,
	`comment` varchar(64) DEFAULT NULL,
	PRIMARY KEY (`id`),
	UNIQUE KEY `name` (`name`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `membership`
(
	`user` integer NOT NULL,
	`group` integer NOT NULL,
	PRIMARY KEY(`user`, `group`),
	FOREIGN KEY(`user`) REFERENCES `users`(`id`),
	FOREIGN KEY(`group`) REFERENCES `groups`(`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `airlines`
(
	`id` integer NOT NULL AUTO_INCREMENT,
	`code` varchar(3),
	`name` varchar(128),
	PRIMARY KEY (`id`),
	CONSTRAINT `unique: code` UNIQUE (`code`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `models`
(
	`id` integer NOT NULL AUTO_INCREMENT,
	`icao` varchar(4) NOT NULL,
	`name` varchar(96) NOT NULL,
	PRIMARY KEY (`id`),
	CONSTRAINT `unique:icao` UNIQUE (`icao`)
) COMMENT = 'http://www.airlinecodes.co.uk'
ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `aircrafts`
(
	`id` integer NOT NULL AUTO_INCREMENT,
	`reg` varchar(8) NOT NULL,
	`model` integer NOT NULL,
	PRIMARY KEY (`id`),
	CONSTRAINT `unique:reg` UNIQUE (`reg`),
	FOREIGN KEY(`model`) REFERENCES `models`(`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `airports`
(
	`id` integer NOT NULL AUTO_INCREMENT,
	`iata` varchar(3) NULL,
	`icao` varchar(4) NOT NULL,
	`name` varchar(255) NOT NULL,
	PRIMARY KEY (`id`),
	CONSTRAINT `unique:icao` UNIQUE(`icao`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `flights`
(
	`id` integer NOT NULL AUTO_INCREMENT,
	`type` enum('P', 'F', 'C') NOT NULL DEFAULT 'P',
	`direction` enum('arrival', 'departure') NOT NULL,
	`airline` integer NOT NULL,
	`code` varchar(6) NOT NULL,
	`scheduled` datetime NOT NULL,
	`expected` timestamp NULL DEFAULT NULL,
	`airport` integer DEFAULT NULL,
	`model` integer DEFAULT NULL,
	`aircraft` integer DEFAULT NULL,
	`last update` timestamp NULL,
	PRIMARY KEY (`id`),
	CONSTRAINT `unique:direction, airline, code, scheduled` UNIQUE (`direction`, `airline`, `code`, `scheduled`),
	FOREIGN KEY(`airline`) REFERENCES `airlines`(`id`),
	FOREIGN KEY(`airport`) REFERENCES `airports`(`id`),
	FOREIGN KEY(`model`) REFERENCES `models`(`id`),
	FOREIGN KEY(`aircraft`) REFERENCES `aircrafts`(`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

/* Copy `flights` table structure (including indices!) */
CREATE TABLE IF NOT EXISTS `history` LIKE `flights`;

/* Remove AUTO_INCREMENT */
ALTER TABLE `history` AUTO_INCREMENT = 0;

/* Count visits to FRA */
CREATE TABLE IF NOT EXISTS `visits`
(
	`aircraft` integer NOT NULL,
	`num` integer NOT NULL,
	`current` datetime NOT NULL,
	`previous` datetime DEFAULT NULL,
	PRIMARY KEY (`aircraft`),
	FOREIGN KEY(`aircraft`) REFERENCES `aircrafts`(`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `watchlist`
(
	`id` integer NOT NULL AUTO_INCREMENT,
	`user` int(11) NOT NULL,
	`notify` bool DEFAULT FALSE,
	# ALTER TABLE `watchlist` MODIFY `reg` varchar(31)
	`reg` varchar(31) NOT NULL,
	`comment` varchar(255) DEFAULT NULL,
	PRIMARY KEY (`id`),
	UNIQUE KEY `user, reg` (`user`, `reg`),
	FOREIGN KEY(`user`) REFERENCES `users`(`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `watchlist-notifications`
(
	`id` integer NOT NULL AUTO_INCREMENT,
	`watch` integer NOT NULL,
	`flight` integer NOT NULL,
	`notified` datetime DEFAULT NULL,
	PRIMARY KEY(`id`),
	UNIQUE KEY(`watch`, `flight`),
	FOREIGN KEY(`watch`) REFERENCES `watchlist`(`id`),
	FOREIGN KEY(`flight`) REFERENCES `flights`(`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

/******************************************************************************
 * Indices
 ******************************************************************************/

CREATE INDEX `flights:scheduled` ON `flights`(`scheduled` ASC);
CREATE INDEX `flights:code` ON `flights`(`code` ASC);
CREATE INDEX `flights:direction` ON `flights`(`direction` ASC);
CREATE INDEX `history:scheduled` ON `history`(`scheduled` ASC);
CREATE INDEX `history:code` ON `history`(`code` ASC);
CREATE INDEX `history:direction` ON `history`(`direction` ASC);
CREATE INDEX `watchlist:user` ON `watchlist`(`user` ASC);
CREATE INDEX `watchlist:reg` ON `watchlist`(`reg` ASC);
CREATE INDEX `visits:aircraft` ON `visits`(`aircraft` ASC);
CREATE INDEX `visits:current` ON `visits`(`current` ASC);
CREATE INDEX `membership:user` ON `membership`(`user` ASC);
CREATE INDEX `membership:group` ON `membership`(`group` ASC);

/******************************************************************************
 * Data
 ******************************************************************************/

INSERT INTO `groups`(`name`, `comment`)
VALUES
('admin',      NULL),
('users',      NULL),
('addflights', NULL),
('specials',   NULL);

INSERT INTO `users`(`name`, `email`, `salt`, `passwd`, `language`)
VALUES
(
	'root',
	'flederwiesel@fra-flugplan.de',
	'cf78aafd5c5410b7b12c2794a52cda1bccd01316f30df57aa29c5609ba979c15',
	'c4ae99aa0209ce5bea9687cf0548d8ebc942ba14e166c45957a876bcec194fed',
	'en'
);

SELECT LAST_INSERT_ID() INTO @root;

INSERT INTO `membership`(`user`, `group`)
(
	SELECT @root AS `user`, `id` AS `group`
	FROM `groups`
	WHERE `name` IN ('admin', 'addflights', 'specials', 'users')
);

INSERT INTO `airlines`(`id`, `code`, `name`)
VALUES
(  1, 'A3',  'Aegean Airlines'),
(  2, 'AA',  'American Airlines'),
(  3, 'AB',  'Airberlin'),
(  4, 'AC',  'Air Canada'),
(  5, 'AEE', 'Aegean Airlines'),
(  6, 'AF',  'Air France'),
(  7, 'AH',  'Air Algerie'),
(  8, 'AI',  'Air India'),
(  9, 'AP',  'Air One'),
( 10, 'AT',  'Royal Air Maroc'),
( 11, 'AY',  'Finnair'),
( 12, 'AZ',  'Alitalia'),
( 13, 'BA',  'British Airways'),
( 14, 'BD',  'British Midland International'),
( 15, 'BE',  'Flybe'),
( 16, 'BPA', 'Blue Panorama Airlines'),
( 17, 'BRU', 'Belavia'),
( 18, 'BT',  'Air Baltic'),
( 19, 'BUC', 'Bulgarian Air Charter'),
( 20, 'CA',  'Air China'),
( 21, 'CAI', 'Corendon Airlines'),
( 22, 'CFE', 'BA CityFlyer'),
( 23, 'CI',  'China Airlines'),
( 24, 'CX',  'Cathay Pacific Airways'),
( 25, 'CY',  'Cyprus Airways'),
( 26, 'DE',  'Condor'),
( 27, 'DL',  'Delta Air Lines'),
( 28, 'DLN', 'Dalmatian'),
( 29, 'EI',  'Aer Lingus'),
( 30, 'EK',  'Emirates'),
( 31, 'EN',  'Air Dolomiti'),
( 32, 'ERT', 'Eritrean Airlines'),
( 33, 'ET',  'Ethiopian Airlines'),
( 34, 'EY',  'Etihad Airways'),
( 35, 'FB',  'Bulgaria Air'),
( 36, 'FHY', 'Freebird Airlines'),
( 37, 'FI',  'Icelandair'),
( 38, 'FV',  'Rossiya'),
( 39, 'GF',  'Gulf Air'),
( 40, 'GH',  'Globus'),
( 41, 'GHY', 'German Sky Airlines '),
( 42, 'GWI', 'Germanwings'),
( 43, 'GXL', 'XL Airways Germany'),
( 44, 'HCC', 'Holidays Czech Airlines'),
( 45, 'HG',  'NIKI'),
( 46, 'HY',  'Uzbekistan Airways'),
( 47, 'IB',  'Iberia'),
( 48, 'IR',  'Iran Air'),
( 49, 'IY',  'Yemenia Yemen Airways'),
( 50, 'IZ',  'Arkia Israel Airlines'),
( 51, 'JA',  'B&H Airlines'),
( 52, 'JFU', 'Jet4you'),
( 53, 'JJ',  'TAM Linhas Aéreas'),
( 54, 'JL',  'JAL Japan Airlines'),
( 55, 'JU',  'Air Serbia'),
( 56, 'KC',  'Air Astana'),
( 57, 'KE',  'Korean Air'),
( 58, 'KIL', 'Kuban Airlines'),
( 59, 'KK',  'Atlasjet Airlines'),
( 60, 'KL',  'KLM Royal Dutch Airlines'),
( 61, 'KM',  'Air Malta'),
( 62, 'KRP', 'Carpatair'),
( 63, 'KU',  'Kuwait Airways'),
( 64, 'LA',  'LAN Airlines'),
( 65, 'LBT', 'Nouvelair Tunisie'),
( 66, 'LG',  'Luxair'),
( 67, 'LH',  'Lufthansa'),
( 68, 'LO',  'LOT Polish Airlines'),
( 69, 'LV',  'Albanian Airlines'),
( 70, 'LX',  'Swiss International Air Lines'),
( 71, 'LY',  'El Al Israel Airlines'),
( 72, 'ME',  'MEA Middle East Airlines'),
( 73, 'MH',  'Malaysia Airlines'),
( 74, 'MHK', 'Alnaser Airlines'),
( 75, 'MK',  'Air Mauritius'),
( 76, 'MLD', 'Air Moldova'),
( 77, 'MS',  'Egypt Air'),
( 78, 'MSC', 'Air Cairo'),
( 79, 'MU',  'China Eastern Airlines'),
( 80, 'NH',  'ANA'),
( 81, 'OK',  'CSA Czech Airlines'),
( 82, 'OLT', 'OLT Express'),
( 83, 'OM',  'MIAT Mongolian Airlines'),
( 84, 'OS',  'Austrian Airlines Group'),
( 85, 'OU',  'Croatia Airlines'),
( 86, 'OZ',  'Asiana Airlines'),
( 87, 'PGT', 'Pegasus Airlines'),
( 88, 'PHW', 'Ave.com'),
( 89, 'PK',  'PIA Pakistan International Airlines'),
( 90, 'PS',  'Ukraine International Airlines'),
( 91, 'QB',  'Sky Georgia'),
( 92, 'QF',  'Qantas Airways'),
( 93, 'QR',  'Qatar Airways'),
( 94, 'RB',  'Syrianair'),
( 95, 'RJ',  'Royal Jordanian'),
( 96, 'RKM', 'RAK Airways'),
( 97, 'RNV', 'Armavia'),
( 98, 'RO',  'Tarom'),
( 99, 'SA',  'South African Airways'),
(100, 'SBI', 'S7 Airlines'),
(101, 'SK',  'SAS Scandinavian Airlines'),
(102, 'SMR', 'Somon Air'),
(103, 'SOV', 'Saravia-Saratov Airlines'),
(104, 'SP',  'SATA Internacional'),
(105, 'SQ',  'Singapore Airlines'),
(106, 'SU',  'Aeroflot'),
(107, 'SUW', 'Sunny Airways'),
(108, 'SV',  'Saudi Arabian Airlines'),
(109, 'SW',  'Air Namibia'),
(110, 'TG',  'Thai Airways International'),
(111, 'TGZ', 'Georgian Airways'),
(112, 'TK',  'Turkish Airlines'),
(113, 'TP',  'TAP Portugal'),
(114, 'TRK', 'Turkuaz Airlines'),
(115, 'TS',  'Air Transat'),
(116, 'TU',  'Tunis Air'),
(117, 'TUA', 'Turkmenistan Airlines'),
(118, 'TUI', 'TUIfly'),
(119, 'TWI', 'Tailwind Havayollari'),
(120, 'UA',  'United Airlines'),
(121, 'UDN', 'Dniproavia'),
(122, 'UL',  'Srilankan Airlines'),
(123, 'UN',  'Transaero Airlines'),
(124, 'US',  'US Airways'),
(125, 'VIM', 'Air VIA Bulgarian'),
(126, 'VLM', 'VLM Airlines'),
(127, 'VN',  'Vietnam Airlines'),
(128, 'VQ',  'FlyHellas.com'),
(129, 'WY',  'Oman Air'),
(130, 'X3',  'TUIfly'),
(131, 'XG',  'SunExpress Deutschland'),
(132, 'XQ',  'SunExpress'),
(133, 'YM',  'Montenegro Airlines'),
(134, 'ZY',  'Sky Airlines'),
(135, 'ZZ',  'ZZ'),
(136, 'JP',  'Adria Airways'),
(137, 'HU',  'Hainan Airlines'),
(138, 'ST',  'Germania'),
(139, 'EW',  'Eurowings'),
(140, '4U',  'Germanwings'),
(141, 'EZE', 'Eastern Airways'),
(142, 'MON', 'Monarch Airlines'),
(143, 'IFA', 'FAI Airservice'),
(144, 'BV',  'Blue Panorama Airlines'),
(145, 'TFL', 'Arkefly'),
(146, 'AEY', 'Air Italy'),
(147, 'DWT', 'Darwin Airline'),
(148, 'YW',  'Air Nostrum'),
(149, 'OHY', 'Onur Air'),
(150, 'FPO', 'Europe Airpost'),
(151, 'JTG', 'Jet Time'),
(152, 'EXS', 'Jet2.com'),
(153, 'HAY', 'Hamburg Airways'),
(154, 'EZ',  'Evergreen International Airlines'),
(155, 'HV',  'Transavia Airlines'),
(156, 'VPA', 'VIP Wings'),
(157, 'JAF', 'JetAirFly'),
(158, 'BO',  'Aerologic'),
(159, 'BOX', 'Aerologic'),
(160, 'UC',  'LAN Cargo'),
(161, 'ACX', 'ACG Air Cargo Germany'),
(162, 'BR',  'EVA Air'),
(163, 'ABW', 'AirBridgeCargo'),
(164, 'FX',  'FedEx'),
(165, 'RGN', 'Cygnus Air'),
(166, 'CZ',  'China Southern Airlines'),
(167, 'ABR', 'Air Bridge Carriers'),
(168, 'AHO', 'Air Hamburg'),
(169, 'CSA', 'Czech Airlines'),
(170, 'DLH', 'Lufthansa'),
(171, 'ETD', 'Etihad Airways'),
(172, 'EXH', 'Executive AG'),
(173, 'EXT', 'Nightexpress'),
(174, 'FFD', 'Stuttgarter Flugdienst'),
(175, 'FMY', 'Aviation Legere de l\'Armee de Terre'),
(176, 'IAM', 'Aeronautica Militare Italiana'),
(177, 'JEI', 'Jet Executive International Charter'),
(178, 'KAC', 'Kuwait Airways'),
(179, 'KZR', 'Air Astana'),
(180, 'LNX', 'London Executive Aviation - LEA'),
(181, 'LZB', 'Bulgaria Air'),
(182, 'MAS', 'Malaysia Airlines'),
(183, 'MGR', 'Magna Air'),
(184, 'NJE', 'NetJets Transportes Aereos'),
(185, 'QAJ', 'Quick Air Jet Charter'),
(186, 'RZO', 'SATA Internacional'),
(187, 'SHY', 'Sky Airlines'),
(188, 'THY', 'Turkish Airlines'),
(189, 'AFL', 'Aeroflot'),
(190, 'AZG', 'Sakaviaservice'),
(191, 'CMB', 'US Transportation Command'),
(192, 'GTI', 'Atlas Air'),
(193, 'MNB', 'MNG Airlines'),
(194, 'YZR', 'Yangtze River Express Airlines'),
(195, 'AG',  'Affretair'),
(196, 'FRA', 'FR Aviation'),
(197, 'OAW', 'Helvetic'),
(198, 'AEA', 'Air Europa'),
(199, 'QS',  'Travel Servis/Smartwings'),
(200, 'BIE', 'Air Mediterranee'),
(201, 'I2',  'Iberia Express'),
(202, 'HC',  'Aero Tropics'),
(203, 'BM',  'BMI regional'),
(204, 'FQ',  'Thomas Cook Belgium Airlines'),
(205, 'IQ',  'Augsburg Airways'),
(206, 'ZZZ', 'ZZZ'),
(207, 'SWT', 'Swiftair'),
(208, 'XLF', 'XL Airways France'),
(209, 'FC',  'Flybe Nordic'),
(210, 'KZ',  'Nippon Cargo Airlines'),
(211, 'WDL', 'WDL Aviation'),
(212, 'VLG', 'Vueling'),
(213, 'VY',  'Vueling Airlines'),
(214, 'S4',  'SATA International'),
(215, 'IA',  'Iraqi Airways'),
(216, 'AHY', 'Azerbaijan Airlines'),
(217, 'SZ',  'Somon Air'),
(218, 'UT',  'UTAir'),
(219, 'TDR', 'Trade Air'),
(220, 'QY',  'DHL'),
(221, 'TF',  'Malmö Aviation'),
(222, 'RU',  'Air Brigde Cargo'),
(223, 'AWC', 'Titan Airways'),
(224, 'MT',  'Thomas Cook Airlines'),
(225, 'OAE', 'Omni Air International'),
(226, 'RC',  'Atlantic Airways'),
(227, 'CLJ', 'Cello Aviation'),
(228, 'YY',  'General Aviation'),
(229, 'WX',  'CityJet'),
(230, '6G',  'Go2Sky'),
(231, 'AXE', 'AirExplore'),
(232, 'HFY', 'Hi Fly'),
(233, 'LAV', 'Alba Star'),
(234, 'PVG', 'Privilege Style'),
(235, 'PC',  'Pegasus Hava Tasimaciligi'),
(236, 'ISK', 'Intersky'),
(237, 'ENT', 'Enter Air'),
(238, 'A6',  'Air Alps'),
(239, '9Y',  'FlyGeorgia'),
(240, '6W',  'Saratov Airlines'),
(241, 'A9',  'Air Zena'),
(242, 'DTR', 'Danish Air Transport'),
(243, 'NJ',  'Nordic Global Airlines'),
(244, 'ORB', 'Oren Air'),
(245, 'EZY', 'easyJet'),
(246, 'BG',  'Biman Bangladesh Airlines'),
(247, 'UX',  'Air Europa'),
(248, 'CKS', 'Kalitta Air'),
(249, 'HQ',  'Thomas Cook Airlines Belgium'),
(250, 'SRK', 'SkyWork Airlines'),
(251, 'DNM', 'Denim Air'),
(252, 'DK',  'Thomas Cook Airlines Scandinavia'),
(253, 'DY',  'Norwegian Air Shuttle'),
(254, 'WLC', 'Welcome Air'),
(255, 'SN',  'Brussels Airlines'),
(256, 'ISR', 'Israir Airlines'),
(257, 'AIB', 'Airbus Industrie'),
(258, 'NMA', 'Nesma Airlines'),
(259, 'AJD', 'flyVista'),
(260, 'QN',  'Air Armenia'),
(261, 'V7',  'Volotea'),
(262, 'OV',  'Estonian Air'),
(263, 'OR',  'Arkefly'),
(264, '8Q',  'Onur Air'),
(265, 'AAB', 'Abelag Aviation'),
(266, 'AV',  'Avianca'),
(267, 'GA',  'Garuda Indonesia'),
(268, 'HM',  'Air Seychelles'),
(269, 'JAI', 'Jet Airways'),
(270, 'LPV', 'Air Alps Aviation'),
(271, 'NZ',  'Air New Zealand'),
(272, 'TUL', 'Tulpar Air'),
(273, 'HRM', 'Hermes Airlines'),
(274, 'JQ',  'Alba Star'),
(276, '7W',  'Wind Rose Aviation'),
(277, 'B2',  'Belavia'),
(278, 'A5',  'Hop!'),
(279, 'V3',  'Carpatair'),
(280, 'TOM', 'Thomson Airways'),
(281, 'EVE', 'Evelop Airlines'),
(282, 'MSA', 'Mistral Air'),
(283, 'MMZ', 'euroAtlantic Airways'),
(284, 'IG',  'Meridiana Fly'),
(285, 'PF',  'Primera Air Scandinavia'),
(286, 'PRW', 'Primera Air Nordic'),
(287, '6F',  'Primera Air Nordic'),
(288, 'AX',  'Avanti Air'),
(289, 'TXC', 'Transaviaexport'),
(290, 'ZT',  'Titan Airways'),
(291, 'SRN', 'Sprint Air'),
(292, 'NO',  'Neos'),
(293, 'DM',  'Asian Air'),
(294, 'FRF', 'Fleet Air International'),
(295, 'YB',  'Bora Jet'),
(296, 'SWU', 'Swiss European Air Lines'),
(297, 'MLT', 'Maleth Aero'),
(298, 'BRJ', 'Bora Jet'),
(299, 'EZS', 'easyJet Switzerland'),
(300, 'RSY', 'I fly'),
(301, 'BLX', 'TUIfly Nordic'),
(302, 'FEG', 'Fly Egypt'),
(303, '3O',  'Air Arabia Maroc'),
(304, 'PTG', 'PrivatAir'),
(305, 'CC',  'Air Atlanta Icelandic'),
(306, 'BCS', 'European Air Transport'),
(307, 'SUA', 'Silesia Air'),
(308, 'BVR', 'ACM Air Charter'),
(309, 'VJT', 'VistaJet'),
(310, 'AOJ', 'Avcon Jet'),
(311, 'MMD', 'Air Alsie'),
(312, 'LXA', 'Luxaviation'),
(313, 'EFD', 'Eisele Flugdienst'),
(314, 'EJM', 'Executive Jet Management'),
(315, '??', ''),
(316, 'DCS', 'DC Aviation'),
(317, 'PNC', 'Prince Aviation'),
(318, 'TOY', 'Toyo Aviation'),
(319, 'AVB', 'Aviation Beauport'),
(320, 'BZE', 'Zenith Aviation'),
(321, 'QGA', 'Windrose Air'),
(322, 'EDC', 'Air Charter Scotland'),
(323, 'ADN', 'Aero-Dienst'),
(324, 'ATL', 'Atlas Air Service'),
(325, 'QNR', 'Queen Air'),
(326, 'SIO', 'Sirio'),
(327, 'FYG', 'Flying Service'),
(328, 'HTM', 'HTM Jet Service'),
(329, 'FAT', 'ASL Airlines (Switzerland)'),
(330, 'CLU', 'Cargologicair'),
(331, 'XPE', 'Amira Air'),
(332, 'GAC', 'GlobeAir'),
(333, 'XES', 'Europstar Express'),
(334, 'UU',  'Air Austral'),
(335, 'JSY', 'Jung Sky'),
(336, 'WGT', 'Volkswagen Air Service'),
(337, 'SAZ', 'REGA Swiss Air-Ambulance'),
(338, 'PHA', 'Phoenix Air Group'),
(339, 'JSI', 'Jet Air Group'),
(340, 'LLT', 'Classic Jet'),
(341, 'IGA', 'Skytaxi'),
(342, 'CLF', 'Centreline Air Charter'),
(343, 'PTI', 'Privatair'),
(344, 'AYY', 'Air Alliance Express'),
(345, 'SVB', 'SiAvia'),
(346, 'TJS', 'Tyrolean Jet Service'),
(347, 'GMA', 'Gama Aviation'),
(348, 'SCR', 'Silver Cloud Air'),
(349, 'LEU', 'Lions Air'),
(350, 'IJM', 'International Jet Management'),
(351, 'AZI', 'Astra Airlines'),
(352, 'ESQ', 'Europ Star'),
(353, 'FXR', 'K-air'),
(354, 'ECA', 'OHL Air Charterflug GmbH'),
(355, 'FBR', 'Baden Aircraft Operations'),
(356, 'CAZ', 'CAT Aviation'),
(357, 'RBB', 'Rabbit-Air'),
(358, 'NUB', 'Nomad Aviation (Europe)'),
(359, 'DUK', 'Luxembourg Air Ambulance'),
(360, 'TIH', 'Tiriac Air'),
(361, 'BAF', 'Belgian Air Force'),
(362, 'GNJ', 'GainJet'),
(363, 'JKH', 'JK Jetkontor AG'),
(364, 'BBA', 'Bombardier'),
(365, 'BKK', 'Blink'),
(366, 'JDI', 'Jet Story'),
(367, 'SVW', 'Global Jet Luxembourg'),
(368, 'HFM', 'Hi Fly Limited Malta'),
(369, 'NPT', 'Atlantic Airlines'),
(370, 'FPG', 'TAG Aviation (Schweiz)'),
(371, 'FLJ', 'FlairJet'),
(372, 'GOT', 'Walt Air Europe'),
(373, 'FCK', 'FCS Flight Calibration Services'),
(374, 'VLB', 'Air Volta'),
(375, 'RHK', 'Sovereign Business Jets'),
(376, 'ITL', 'Italfly'),
(377, 'LXG', 'Luxaviation Germany'),
(378, 'BOB', 'Backbone'),
(379, 'SXN', 'SaxonAir Charter'),
(380, 'HR',  'Hahn Air Lines'),
(381, 'TYW', 'Tyrol Air Ambulance'),
(382, 'GSW', 'Germania Flug'),
(383, 'VR',  'TACV Cabo Verde Airlines'),
(384, 'BFD', 'Bertelsmann Aviation'),
(385, 'MLM', 'Comlux Malta'),
(386, 'MJC', 'Mandarin Air'),
(387, 'CLS', 'Challenge Air'),
(388, 'KFE', 'Skyfirst'),
(389, 'FYL', 'Flying Group Luxembourg'),
(390, 'JEF', 'Jetflite Oy'),
(391, 'MHV', 'MHS Aviation'),
(392, 'XRO', 'Exxaero'),
(393, 'HRN', 'Heron Luftfahrt'),
(394, 'ESW', 'Silk Way Business Aviation LLC'),
(395, 'HYP', 'Hyperion Aviation'),
(396, 'TJT', 'Twin Jet'),
(397, 'MJF', 'MJet'),
(398, 'VVV', 'Valair'),
(399, 'BFX', 'Fly Alpha'),
(400, 'P7',  'Small Planet Airlines (Poland)'),
(401, 'ADZ', 'Avio Delta'),
(402, 'WW',  'WOW Air'),
(403, 'S5',  'Small Planet Airlines UAB'),
(404, 'SOO', 'Southern Air'),
(405, 'CRL', 'Corse Air International (Corsair)'),
(406, 'TAY', 'TNT Airways'),
(407, 'PEA', 'Pan Europeenne Air Service'),
(408, 'MOZ', 'SalzburgJetAviation'),
(409, 'STC', 'Skytaxi Luftfahrt GmbH'),
(410, 'VMP', 'Execujet Europe'),
(411, 'IBG', 'Springfield Air'),
(412, 'EXJ', 'Executive Jet Charter'),
(413, 'NFA', 'North Flying'),
(414, 'VPC', 'Panaviatic'),
(415, 'EXU', 'Executive Airlines'),
(416, 'NVR', 'Novair'),
(417, 'ASJ', 'Astonjet'),
(418, 'LWG', 'Luxwing'),
(419, 'GDK', 'Goldeck Flug'),
(420, 'AZE', 'Arcus Air-Logistic'),
(421, 'BHP', 'Belair Airlines'),
(422, 'XGO', 'Airgo Flugservice'),
(423, 'EAT', 'Air Transport Europe'),
(424, 'VCG', 'Fly Vectra'),
(425, 'LDM', 'LaudaMotion'),
(426, 'PVJ', 'Privajet'),
(427, 'IMX', 'Zimex Aviation'),
(428, 'PY',  'Surinam Airways'),
(429, 'DFC', 'Aeropartner'),
(430, 'SM',  'Air Cairo'),
(431, 'JTI', 'ImperialJet Europe'),
(432, 'KD',  'Western Global Airlines'),
(433, 'ECC', 'Eclair Aviation'),
(434, 'HSG', 'Hesnes Air'),
(435, 'BMS', 'Blue Air'),
(436, 'AWU', 'Sylt Air'),
(437, 'LMJ', 'Masterjet Aviacao Executiva'),
(438, 'SYG', 'Synergy Aviation'),
(439, 'VND', 'Avionord'),
(440, 'CND', 'Corendon Dutch Airlines'),
(441, 'PJS', 'Jet Aviation'),
(442, 'PAV', 'ProAir'),
(443, 'FTY', 'ABC Bedarfsflug	'),
(444, 'PWF', 'Private Wings Flugcharter'),
(445, 'GSJ', 'G-Jet'),
(446, 'EOL', 'Airailes'),
(447, 'JAR', 'Airlink'),
(448, 'VS',  'Virgin Atlantic'),
(449, 'NWG', 'Airwing'),
(450, 'JFA', 'Jetfly Aviation'),
(451, 'M4',  'Mistral Air'),
(452, 'AEH', 'Aero4M'),
(453, 'AMQ', 'Aircraft Management and Consulting'),
(454, 'EDG', 'Jet Edge'),
(455, 'EOA', 'Elilombarda'),
(456, 'LFO', 'DLR Flugbetriebe'),
(457, 'LUC', 'Albinati Aeronautics'),
(458, 'JME', 'EJME Aircraft Management'),
(459, 'PSK', 'Prescott'),
(460, 'UJ',  'AlMasria Universal Airlines'),
(461, 'GER', 'Eagle Aviation GmbH, Mannheim'),
(462, 'LLX', 'Small Planet Airlines'),
(463, 'MYX', 'SmartLynx Estonia'),
(464, 'TVF', 'Transavia France'),
(465, 'GLJ', 'Global Jet Austria'),
(466, 'ARN', 'Aeronexus'),
(467, 'LSA', 'Leader SRL'),
(468, 'FR',  'Ryanair'),
(469, 'ABP', 'ABS Jets'),
(470, 'EVJ', 'Everjets'),
(471, 'TGM', 'TAG Aviation España'),
(472, 'DHK', 'DHL Air'),
(473, 'LJB', 'Al Jaber Aviation'),
(474, 'TIE', 'Time Air'),
(475, 'POF', 'Police Nationale'),
(476, 'ABF', 'Scanwings Oy'),
(477, 'ED',  'AirExplore'),
(478, 'AXY', 'Air X Charter Limited'),
(479, 'CV',  'Cargolux Airlines International'),
(480, 'EL',  'Ellinair S.A.'),
(481, 'JCB', 'J C Bamford Excavators'),
(482, 'SPG', 'Speedwings Executive'),
(483, 'CAO', 'Air China Cargo');

INSERT INTO `models`(`id`, `icao`, `name`)
VALUES
(  1, 'A124', 'Antonov AN-124 Ruslan'),
(  2, 'A140', 'Antonov AN-140'),
(  3, 'A148', 'Antonov AN-148'),
(  4, 'A306', 'Airbus Industrie A300-600'),
(  5, 'A30B', 'Airbus Industrie A300B2/B4/C4/F4'),
(  6, 'A310', 'Airbus A310'),
(  7, 'A318', 'Airbus A318'),
(  8, 'A319', 'Airbus A319'),
(  9, 'A320', 'Airbus A320-100/200'),
( 10, 'A32A', 'Airbus A320-100/200 (Sharklets)'),
( 11, 'A321', 'Airbus A321-100/200'),
( 12, 'A330', 'Airbus A330 all models'),
( 13, 'A332', 'Airbus A330-200'),
( 14, 'A333', 'Airbus A330-300'),
( 15, 'A340', 'Airbus A340 all models'),
( 16, 'A342', 'Airbus A340-200'),
( 17, 'A343', 'Airbus A340-300'),
( 18, 'A345', 'Airbus A340-500'),
( 19, 'A346', 'Airbus A340-600'),
( 20, 'A388', 'Airbus A380-800'),
( 21, 'A3ST', 'Airbus Industrie A300-600ST Beluga Freighter'),
( 22, 'A748', 'Hawker Siddeley HS.748'),
( 23, 'AC68', 'Gulfstream/Rockwell (Aero) Commander'),
( 24, 'AC90', 'Gulfstream/Rockwell (Aero) Turbo Commander'),
( 25, 'AN12', 'Antonov AN-12'),
( 26, 'AN24', 'Antonov AN-24'),
( 27, 'AN26', 'Antonov AN-26'),
( 28, 'AN28', 'Antonov AN-28 / PZL Miele M-28 Skytruck'),
( 29, 'AN30', 'Antonov AN-30'),
( 30, 'AN32', 'Antonov AN-32'),
( 31, 'AN72', 'Antonov AN-72 / AN-74'),
( 32, 'AT43', 'Aerospatiale/Alenia ATR 42-300 / 320'),
( 33, 'AT45', 'Aerospatiale/Alenia ATR 42-500'),
( 34, 'AT72', 'Aerospatiale/Alenia ATR 72-200/210'),
( 35, 'ATP', 'British Aerospace ATP'),
( 36, 'B190', 'Beechcraft 1900/1900C/1900D'),
( 37, 'B461', 'BAe 146-100'),
( 38, 'B462', 'BAe 146-200'),
( 39, 'B463', 'BAe 146-300'),
( 40, 'B703', 'Boeing 707-300'),
( 41, 'B712', 'Boeing 717'),
( 42, 'B720', 'Boeing 720B'),
( 43, 'B721', 'Boeing 727-100'),
( 44, 'B722', 'Boeing 727-200'),
( 45, 'B731', 'Boeing 737-100'),
( 46, 'B732', 'Boeing 737-200'),
( 47, 'B733', 'Boeing 737-300'),
( 48, 'B734', 'Boeing 737-400'),
( 49, 'B735', 'Boeing 737-500'),
( 50, 'B736', 'Boeing 737-600'),
( 51, 'B737', 'Boeing 737-700'),
( 52, 'B738', 'Boeing 737-800'),
( 53, 'B739', 'Boeing 737-900'),
( 54, 'B741', 'Boeing 747-100'),
( 55, 'B742', 'Boeing 747-200'),
( 56, 'B743', 'Boeing 747-300'),
( 57, 'B744', 'Boeing 747-400'),
( 58, 'B748', 'Boeing 747-8I'),
( 59, 'B74R', 'Boeing 747SR'),
( 60, 'B752', 'Boeing 757-200'),
( 61, 'B753', 'Boeing 757-300'),
( 62, 'B762', 'Boeing 767-200'),
( 63, 'B763', 'Boeing 767-300'),
( 64, 'B764', 'Boeing 767-400'),
( 65, 'B772', 'Boeing 777-200'),
( 66, 'B773', 'Boeing 777-300'),
( 67, 'B77L', 'Boeing 777-200LR'),
( 68, 'B77W', 'Boeing 777-300ER'),
( 69, 'B788', 'Boeing 787 "Dreamliner"'),
( 70, 'BA11', 'British Aerospace (BAC) One Eleven'),
( 71, 'BELF', 'Shorts SC-5 Belfast'),
( 72, 'BN2P', 'Pilatus Britten-Norman BN-2A/B Islander'),
( 73, 'C130', 'Lockheed L-182 / 282 / 382 (L-100) Hercules'),
( 74, 'C212', 'CASA / IPTN 212 Aviocar'),
( 75, 'C46', 'Curtiss C-46 Commando'),
( 76, 'CL44', 'Canadair CL-44'),
( 77, 'CL60', 'Canadair Challenger'),
( 78, 'CN35', 'CASA / IPTN CN-235'),
( 79, 'CONC', 'Aerospatiale/BAC Concorde'),
( 80, 'CONI', 'Lockheed L-1049 Super Constellation'),
( 81, 'COUC', 'Helio H-250 Courier / H-295 / 385 Super Courier'),
( 82, 'CRJ1', 'Canadair Regional Jet 100'),
( 83, 'CRJ2', 'Canadair Regional Jet 200'),
( 84, 'CRJ7', 'Canadair Regional Jet 700'),
( 85, 'CRJ9', 'Canadair Regional Jet 900'),
( 86, 'CVLP', 'Convair CV-240/440'),
( 87, 'CVLT', 'Convair CV-580/600/640'),
( 88, 'D228', 'Fairchild Dornier Do.228'),
( 89, 'D328', 'Fairchild Dornier Do.328'),
( 90, 'DC10', 'Douglas DC-10'),
( 91, 'DC3', 'Douglas DC-3'),
( 92, 'DC6', 'Douglas DC6A/B/C'),
( 93, 'DC85', 'Douglas DC-8-50 Freighter'),
( 94, 'DC86', 'Douglas DC-8-62'),
( 95, 'DC87', 'Douglas DC-8-71/72/73'),
( 96, 'DC9', 'Douglas DC-9 all models'),
( 97, 'DC91', 'Douglas DC-9-10'),
( 98, 'DC92', 'Douglas DC-9-20'),
( 99, 'DC93', 'Douglas DC-9-30'),
(100, 'DC94', 'Douglas DC-9-40'),
(101, 'DC95', 'Douglas DC-9-50'),
(102, 'DH2T', 'De Havilland Canada DHC-2 Turbo-Beaver'),
(103, 'DH8A', 'De Havilland Canada DHC-8-100 Dash 8 / 8Q'),
(104, 'DH8B', 'De Havilland Canada DHC-8-200 Dash 8 / 8Q'),
(105, 'DH8C', 'De Havilland Canada DHC-8-300 Dash 8 / 8Q'),
(106, 'DH8D', 'De Havilland Canada DHC-8-400 Dash 8Q'),
(107, 'DHC2', 'De Havilland Canada DHC-2 Beaver'),
(108, 'DHC3', 'De Havilland Canada DHC-3 Otter / Turbo Otter'),
(109, 'DHC4', 'De Havilland Canada DHC-4 Caribou'),
(110, 'DHC6', 'De Havilland Canada DHC-6 Twin Otter'),
(111, 'DHC7', 'De Havilland Canada DHC-7 Dash 7'),
(112, 'DOVE', 'De Havilland DH.104 Dove'),
(113, 'E110', 'Embraer EMB.110 Bandeirnate'),
(114, 'E120', 'Embraer EMB.120 Brasilia'),
(115, 'E135', 'Embraer RJ135'),
(116, 'E145', 'Embraer RJ145 Amazon'),
(117, 'E170', 'Embraer 170'),
(118, 'E190', 'Embraer 190'),
(119, 'F100', 'Fokker 100'),
(120, 'F27', 'Fokker F.27 Friendship / Fairchild F.27'),
(121, 'F28', 'Fokker F.28 Fellowship'),
(122, 'F50', 'Fokker 50'),
(123, 'F70', 'Fokker 70'),
(124, 'G159', 'Gulfstream Aerospace G-159 Gulfstream I'),
(125, 'G21', 'Grumman G.21 Goose'),
(126, 'G73T', 'Grumman G.73 Turbo Mallard'),
(127, 'GLEX', 'Canadair Global Express'),
(128, 'HERN', 'De Havilland DH.114 Heron'),
(129, 'I114', 'Ilyushin IL114'),
(130, 'IL18', 'Ilyushin IL18'),
(131, 'IL62', 'Ilyushin IL62'),
(132, 'IL76', 'Ilyushin IL76'),
(133, 'IL86', 'Ilyushin IL86'),
(134, 'IL96', 'Ilyushin IL96'),
(135, 'J328', 'Fairchild Dornier 328JET'),
(136, 'JS31', 'British Aerospace Jetstream 31'),
(137, 'JS32', 'British Aerospace Jetstream 32'),
(138, 'JS41', 'British Aerospace Jetstream 41'),
(139, 'JU52', 'Junkers Ju52/3M'),
(140, 'L101', 'Lockheed L-1011 1 / 50 / 100 / 150 / 200 / 250 Tristar'),
(141, 'L188', 'Lockheed L-188 Electra'),
(142, 'L410', 'LET 410'),
(143, 'LOAD', 'Ayres LM-200 Loadmaster'),
(144, 'MD11', 'McDonnell Douglas MD11'),
(145, 'MD80', 'McDonnell Douglas MD80'),
(146, 'MD81', 'McDonnell Douglas MD81'),
(147, 'MD82', 'McDonnell Douglas MD82'),
(148, 'MD83', 'McDonnell Douglas MD83'),
(149, 'MD87', 'McDonnell Douglas MD87'),
(150, 'MD88', 'McDonnell Douglas MD88'),
(151, 'MD90', 'McDonnell Douglas MD90'),
(152, 'MU2', 'Mitsubishi Mu-2'),
(153, 'N262', 'Aerospatiale (Nord) 262'),
(154, 'N74S', 'Boeing 747SP'),
(155, 'NOMA', 'Government Aircraft Factories N22B / N24A Nomad'),
(156, 'P68', 'Partenavia P.68'),
(157, 'PC12', 'Pilatus PC-12'),
(158, 'PC6T', 'Pilatus PC-6 Turbo Porter'),
(159, 'RJ1H', 'Avro RJ100 Avroliner'),
(160, 'RJ70', 'Avro RJ70 Avroliner'),
(161, 'RJ85', 'Avro RJ85 Avroliner'),
(162, 'RX1H', 'Avro RJX100'),
(163, 'RX85', 'Avro RJX85 	M B11 	BA11 	British Aerospace (BAC) One Eleven / RomBAC One Eleven'),
(164, 'S210', 'Aerospatiale (Sud Aviation) Se.210 Caravelle'),
(165, 'S601', 'Aerospatiale SN.601 Corvette'),
(166, 'SB20', 'Saab 2000'),
(167, 'SC7', 'Shorts SC-7 Skyvan'),
(168, 'SF34', 'Saab SF340A/B'),
(169, 'SH33', 'Shorts SD.330'),
(170, 'SH36', 'Shorts SD.360'),
(171, 'T134', 'Tupolev Tu134'),
(172, 'T154', 'Tupolev Tu154'),
(173, 'T204', 'Tupolev Tu-204 / Tu-214'),
(174, 'TRIS', 'Pilatus Britten-Norman BN-2A Mk III Trislander'),
(175, 'VISC', 'Vickers Viscount'),
(176, 'WW24', 'Israel Aircraft Industries 1124 Westwind'),
(177, 'Y12', 'Harbin Yunshuji Y12'),
(178, 'YK40', 'Yakovlev Yak 40'),
(179, 'YK42', 'Yakovlev Yak 42'),
(180, 'YS11', 'NAMC YS-11'),
(181, 'AT75', 'Aerospatiale/Alenia ATR 72-500'),
(182, 'AT76', 'Aerospatiale/Alenia ATR 72-600'),
(183, 'CRJX', 'Canadair Regional Jet 1000'),
(184, 'AT73', 'Aerospatiale/Alenia ATR72-200'),
(187, 'GLF4', 'Gulfstream 4'),
(188, 'H25B', 'Hawker-Siddeley HS-125-700'),
(189, 'A32B', 'Airbus A321-100/200 (Sharklets)'),
(193, 'A359', 'Airbus A350-900'),
(194, 'EPIC', 'Epic LT'),
(195, 'CL30', 'Bombardier Challenger 300'),
(196, 'B789', 'Boeing 787-9'),
(197, 'SU95', 'Sukhoi Superjet 100-95B'),
(199, 'C525', 'Cessna CitationJet'),
(200, 'AT44', 'ATR-42-400'),
(201, 'C56X', 'Cessna 560XL Citation Excel'),
(202, 'LJ55', 'Learjet 55'),
(203, 'FA7X', 'Dassault Falcon 7X'),
(204, 'GLF6', 'Gulfstream G650'),
(205, 'GALX', 'IAI-1126 Galaxy/Gulfstream G200'),
(206, 'C510', 'Cessna 510 Citation Mustang'),
(207, 'C25A', 'Cessna 525A Citation CJ2'),
(208, 'F2TH', 'Dassault Falcon 2000'),
(209, 'LJ35', 'Gate Learjet 35,36 (C-21,C-35,R-35,RC-35,VU-35,RC-36,U-36)'),
(210, 'LJ45', 'Bombardier Learjet 45/75'),
(211, 'GLF5', 'Gulfstream Aerospace G-1159D Gulfstream 5/5SP/500/550 (C-37)'),
(212, 'C25C', 'Cessna 525C Citation CJ4'),
(213, 'E55P', 'Embraer EMB-505 Phenom 300'),
(214, 'LJ60', 'Bombardier Learjet 60'),
(215, 'C25B', 'Cessna 525B Citation CJ3'),
(216, 'CL35', 'Bombardier BD-100-1A10 Challenger 350'),
(217, 'E35L', 'Embraer EMB-135BJ Legacy 600/650 (VC-99B)'),
(218, 'BE20', 'Beech/Hawker Beechcraft 200/B200/B200C/T/GT,1300 Super King Air (C-12A to F/C-12L/NC/RC/UC-12)'),
(219, 'C750', 'Cessna 750 Citation X, Citation X+'),
(220, 'C680', 'Cessna 680 Citation Sovereign, Sovereign +, 680A Latitude'),
(221, 'C560', 'Cessna 560 Citation 5/5 Ultra/5 Ultra Encore (UC-35,OT-47,TR-20)'),
(222, 'BE40', 'Beech/Hawker Beechcraft 400A/XP Beechjet (T-1/T-400)'),
(223, 'FA50', 'Dassault-Breguet Falcon 50/50EX, Mystère 50 (T-16)'),
(224, 'C55B', 'Cessna 550B Citation Bravo'),
(225, 'A109', 'AgustaWestland AW109 Power/Grand (Hkp15/MH-68)'),
(226, 'B350', 'Beech/Hawker Beechcraft B/C-300 Super King Air 350 (MC-12)'),
(227, 'PRM1', 'Raytheon/Hawker Beechcraft 390 Premier 1'),
(228, 'B430', 'Bell 430'),
(229, 'F900', 'Dassault-Breguet/Dassault Falcon 900,900DX/EX,Mystère 900 (T-18)'),
(230, 'GLF3', 'Gulfstream Aerospace G-1159A Gulfstream 3 (C-20A/B/C/D/E)'),
(231, 'HA4T', 'Hawker Beechcraft 4000 Hawker Horizon/Hawker Horizon'),
(232, 'C650', 'Cessna 650 Citation 3/6/7'),
(233, 'LJ40', 'Bombardier Learjet 40/70'),
(234, 'PAY2', 'Piper PA-31T-620/T2-620 Cheyenne,Cheyenne 2'),
(235, 'P180', 'Piaggio P-180 Avanti'),
(236, 'BE9L', 'Beech/Hawker Beechcraft B/C-90,C-90A/B/GT,E90 King Air (T-44/VC-6)'),
(237, 'GL5T', 'Bombardier BD-700-1A11 Global 5000'),
(238, 'BCS1', 'Bombardier BD-500 CSeries CS100'),
(239, 'C425', 'Cessna 425 Corsair,Conquest 1'),
(240, 'G150', 'Israel Aircraft Industries Gulfstream G150'),
(241, 'PAY3', 'Piper PA-42-720 Cheyenne 3'),
(242, 'R44',  'Robinson R-44 Astro,Clipper,Raven'),
(243, 'LJ31', 'Gates Learjet 31'),
(244, 'E50P', 'Embraer EMB-500 Phenom 100'),
(245, 'DA42', 'Diamond DA-42 Twinstar'),
(246, 'G280', 'Gulfstream Aerospace Gulfstream G280'),
(247, 'ASTR', 'Israel Aircraft Industries/Gulfstream 1125 Astra/G100 (C-38)'),
(248, 'C441', 'Cessna 441 Conquest,Conquest 2'),
(249, 'A35K', 'Airbus A350-1000XWB'),
(250, 'SW4',  'Fairchild-Swearingen SA-226AT/TC,SA-227AC/AT/CC/DC/PC,Merlin 23/23E/4, Metro 2/2A/3/3A/23/23E/4A'),
(251, 'TRS',  'Deutsche Bundesbahn Train Airport Express'),
(252, 'EC35', 'Eurocopter EC135/635'),
(253, 'B407', 'Bell 407'),
(254, 'E175', 'Embraer 175,ERJ 170-200'),
(255, 'E195', 'Embraer 195,ERJ 190-200'),
(256, 'E550', 'Embraer EMB-550 Legacy 500'),
(257, 'C421', 'Cessna 421,Golden Eagle,Executive Commuter'),
(258, 'TBM7', 'Socata TBM-700'),
(259, 'A139', 'AgustaWestland. AW139'),
(260, 'TBM8', 'Socata TBM-850'),
(261, 'C68A', 'Cessna 680A Citation Latitude'),
(263, 'B78J', 'Boeing 787-10'),
(264, 'EA50', 'Eclipse Eclipse 500'),
(265, 'PAY1', 'Piper PA-31T3-500 T-1040'),
(266, 'BCS3', 'Bombardier BD-500 CSeries CS300');

INSERT INTO `airports`(`id`, `iata`, `icao`, `name`)
VALUES
(  1, 'ABV', 'DNAA', 'Abuja, Nigeria'),
(  2, 'ABZ', 'EGPD', 'Aberdeen, Großbritannien'),
(  3, 'ACC', 'DGAA', 'Accra, Ghana'),
(  4, 'ACE', 'GCRR', 'Lanzarote, Spanien'),
(  5, 'ADA', 'LTAF', 'Adana, Türkei'),
(  6, 'ADB', 'LTBJ', 'Izmir, Türkei'),
(  7, 'ADD', 'HAAB', 'Addis Abeba, Äthiopien'),
(  8, 'AGA', 'GMAD', 'Agadir, Marokko'),
(  9, 'AGP', 'LEMG', 'Malaga, Spanien'),
( 10, 'ALA', 'UAAA', 'Almaty, Kasachstan'),
( 11, 'ALG', 'DAAG', 'Algier, Algerien'),
( 12, 'AMM', 'OJAI', 'Amman, Jordanien'),
( 13, 'AMS', 'EHAM', 'Amsterdam, Niederlande'),
( 14, 'ARN', 'ESSA', 'Stockholm, Schweden'),
( 15, 'ASB', 'UTAA', 'Ashgabat, Turkmenistan'),
( 16, 'ASM', 'HHAS', 'Asmara, Eritrea'),
( 17, 'ASR', 'LTAU', 'Kayseri, Türkei'),
( 18, 'ATH', 'LGAV', 'Athen, Griechenland'),
( 19, 'ATL', 'KATL', 'Atlanta, USA'),
( 20, 'AUH', 'OMAA', 'Abu Dhabi, Ver.Arab.Emirate'),
( 21, 'AYT', 'LTAI', 'Antalya, Türkei'),
( 22, 'BAH', 'OBBI', 'Bahrain, Bahrain'),
( 23, 'BCN', 'LEBL', 'Barcelona, Spanien'),
( 24, 'BEG', 'LYBE', 'Belgrad, Serbien'),
( 25, 'BEY', 'OLBA', 'Beirut, Libanon'),
( 26, 'BGI', 'TBPB', 'Barbados, Barbados'),
( 27, 'BGO', 'ENBR', 'Bergen, Norwegen'),
( 28, 'BGY', 'LIME', 'Bergamo-Orio AlSerio, Italien'),
( 29, 'BHX', 'EGBB', 'Birmingham, Großbritannien'),
( 30, 'BIO', 'LEBB', 'Bilbao, Spanien'),
( 31, 'BJL', 'GBYD', 'Banjul, Gambia'),
( 32, 'BKK', 'VTBS', 'Bangkok, Thailand'),
( 33, 'BLL', 'EKBI', 'Billund, Dänemark'),
( 34, 'BLQ', 'LIPE', 'Bologna, Italien'),
( 35, 'BLR', 'VOBL', 'Bangalore, Indien'),
( 36, 'BOG', 'SKBO', 'Bogota, Kolumbien'),
( 37, 'BOM', 'VABB', 'Mumbai, Indien'),
( 38, 'BOS', 'KBOS', 'Boston, USA'),
( 39, 'BRE', 'EDDW', 'Bremen, Deutschland'),
( 40, 'BRU', 'EBBR', 'Brüssel, Belgien'),
( 41, 'BSL', 'LFSB', 'Basel, Schweiz'),
( 42, 'BUD', 'LHBP', 'Budapest, Ungarn'),
( 43, 'CAI', 'HECA', 'Kairo, Ägypten'),
( 44, 'CAN', 'ZGGG', 'Guangzhou, China'),
( 45, 'CCS', 'SVMI', 'Caracas, Venezuela'),
( 46, 'CCU', 'VECC', 'Kolkata, Indien'),
( 47, 'CDG', 'LFPG', 'Paris-Ch.De Gaulle, Frankreich'),
( 48, 'CLT', 'KCLT', 'Charlotte, USA'),
( 49, 'CMB', 'VCBI', 'Colombo, Sri Lanka'),
( 50, 'CMN', 'GMMN', 'Casablanca, Marokko'),
( 51, 'CPH', 'EKCH', 'Kopenhagen, Dänemark'),
( 52, 'CPT', 'FACT', 'Kapstadt, Südafrika'),
( 53, 'CTA', 'LICC', 'Catania, Italien'),
( 54, 'CUN', 'MMUN', 'Cancun, Mexiko'),
( 55, 'DAM', 'OSDI', 'Damaskus, Syrien'),
( 56, 'DBV', 'LDDU', 'Dubrovnik, Kroatien'),
( 57, 'DEL', 'VIDP', 'Delhi, Indien'),
( 58, 'DEN', 'KDEN', 'Denver, USA'),
( 59, 'DFW', 'KDFW', 'Dallas-Fort Worth, USA'),
( 60, 'DJE', 'DTTJ', 'Djerba, Tunesien'),
( 61, 'DME', 'UUDD', 'Moskau-Domodedovo, Russland'),
( 62, 'DMM', 'OEDF', 'Dammam, Saudi-Arabien'),
( 63, 'DOH', 'OTBD', 'Doha, Katar'),
( 64, 'DRS', 'EDDC', 'Dresden, Deutschland'),
( 65, 'DTW', 'KDTW', 'Detroit, USA'),
( 66, 'DUB', 'EIDW', 'Dublin, Irland'),
( 67, 'DUS', 'EDDL', 'Düsseldorf, Deutschland'),
( 68, 'DXB', 'OMDB', 'Dubai, Ver.Arab.Emirate'),
( 69, 'DYU', 'UTDD', 'Duschanbe, Tadschikistan'),
( 70, 'EBL', 'ORER', 'Erbil, Irak'),
( 71, 'EDI', 'EGPH', 'Edinburgh, Großbritannien'),
( 72, 'EMA', 'EGNX', 'East Midlands, Großbritannien'),
( 73, 'ESB', 'LTAC', 'Ankara, Türkei'),
( 74, 'EWR', 'KEWR', 'New York-Newark, USA'),
( 75, 'EZE', 'SAEZ', 'Buenos Aires, Argentinien'),
( 76, 'FAO', 'LPFR', 'Faro, Portugal'),
( 77, 'FCO', 'LIRF', 'Rom-Fiumicino, Italien'),
( 78, 'FDH', 'EDNY', 'Friedrichshafen, Deutschland'),
( 79, 'FLL', 'KFLL', 'Fort Lauderdale, USA'),
( 80, 'FLR', 'LIRQ', 'Florenz, Italien'),
( 81, 'FMO', 'EDDG', 'Münster Osnabrück, Deutschland'),
( 82, 'FNC', 'LPMA', 'Madeira, Portugal'),
( 83, 'FUE', 'GCFV', 'Fuerteventura, Spanien'),
( 84, 'GDN', 'EPGD', 'Gdansk/Danzig, Polen'),
( 85, 'GIG', 'SBGL', 'Rio de Janeiro, Brasilien'),
( 86, 'GOI', 'VAGO', 'Goa, Indien'),
( 87, 'GOT', 'ESGG', 'Göteborg, Schweden'),
( 88, 'GRU', 'SBGR', 'Sao Paulo-Guarulhos, Brasilien'),
( 89, 'GRZ', 'LOWG', 'Graz, Österreich'),
( 90, 'GVA', 'LSGG', 'Genf, Schweiz'),
( 91, 'GZT', 'LTAJ', 'Gaziantep, Türkei'),
( 92, 'HAJ', 'EDDV', 'Hannover, Deutschland'),
( 93, 'HAM', 'EDDH', 'Hamburg, Deutschland'),
( 94, 'HAN', 'VVNB', 'Hanoi, Vietnam'),
( 95, 'HAV', 'MUHA', 'Havanna, Kuba'),
( 96, 'HEL', 'EFHK', 'Helsinki, Finnland'),
( 97, 'HGH', 'ZSHC', 'Hangzhou, China'),
( 98, 'HKG', 'VHHH', 'Hongkong, Hong Kong'),
( 99, 'HKT', 'VTSP', 'Phuket'),
(100, 'HND', 'RJTT', 'Tokio Haneda, Japan'),
(101, 'HOG', 'MUHG', 'Holguin, Kuba'),
(102, 'HRG', 'HEGN', 'Hurghada, Ägypten'),
(103, 'IAD', 'KIAD', 'Washington, USA'),
(104, 'IAH', 'KIAH', 'Houston, USA'),
(105, 'ICN', 'RKSI', 'Seoul-Incheon, Korea-Süd'),
(106, 'IKA', 'OIIE', 'Teheran ImamKhomeini, Iran'),
(107, 'INN', 'LOWI', 'Innsbruck, Österreich'),
(108, 'ISB', 'OPRN', 'Islamabad, Pakistan'),
(109, 'IST', 'LTBA', 'Istanbul, Türkei'),
(110, 'JED', 'OEJN', 'Jeddah, Saudi-Arabien'),
(111, 'JFK', 'KJFK', 'New York-J.F.Kennedy, USA'),
(112, 'JNB', 'FAJS', 'Johannesburg, Südafrika'),
(113, 'JRO', 'HTKJ', 'Kilimanjaro, Tansania'),
(114, 'KBP', 'UKBB', 'Kiew-Borispol, Ukraine'),
(115, 'KEF', 'BIKF', 'Reykjavik, Island'),
(116, 'KIV', 'LUKK', 'Chisinau, Moldawien'),
(117, 'KIX', 'RJBB', 'Osaka, Japan'),
(118, 'KLU', 'LOWK', 'Klagenfurt, Österreich'),
(119, 'KRK', 'EPKK', 'Krakau, Polen'),
(120, 'KRT', 'HSSS', 'Khartoum, Sudan'),
(121, 'KTW', 'EPKT', 'Kattowitz, Polen'),
(122, 'KUL', 'WMKK', 'Kuala Lumpur, Malaysia'),
(123, 'KWI', 'OKBK', 'Kuwait, Kuwait'),
(124, 'KZN', 'UWKD', 'Kazan, Russland'),
(125, 'LAD', 'FNLU', 'Luanda, Angola'),
(126, 'LAS', 'KLAS', 'Las Vegas, USA'),
(127, 'LAX', 'KLAX', 'Los Angeles, USA'),
(128, 'LCA', 'LCLK', 'Larnaca, Zypern'),
(129, 'LCY', 'EGLC', 'London-City Airport, Großbritannien'),
(130, 'LED', 'ULLI', 'Sankt Petersburg, Russland'),
(131, 'LEJ', 'EDDP', 'Leipzig Halle, Deutschland'),
(132, 'LGW', 'EGKK', 'London-Gatwick, Großbritannien'),
(133, 'LHE', 'OPLA', 'Lahore, Pakistan'),
(134, 'LHR', 'EGLL', 'London-Heathrow, Großbritannien'),
(135, 'LIN', 'LIML', 'Mailand-Linate, Italien'),
(136, 'LIS', 'LPPT', 'Lissabon, Portugal'),
(137, 'LJU', 'LJLJ', 'Ljubljana, Slowenien'),
(138, 'LNZ', 'LOWL', 'Linz, Österreich'),
(139, 'LOS', 'DNMM', 'Lagos, Nigeria'),
(140, 'LPA', 'GCLP', 'Las Palmas, Spanien'),
(141, 'LRM', 'MDLR', 'La Romana, Dominikan. Rep.'),
(142, 'LUX', 'ELLX', 'Luxemburg, Luxemburg'),
(143, 'LXR', 'HELX', 'Luxor, Ägypten'),
(144, 'LYS', 'LFLL', 'Lyon, Frankreich'),
(145, 'MAA', 'VOMM', 'Chennai, Indien'),
(146, 'MAD', 'LEMD', 'Madrid, Spanien'),
(147, 'MAN', 'EGCC', 'Manchester, Großbritannien'),
(148, 'MBA', 'HKMO', 'Mombasa, Kenia'),
(149, 'MBJ', 'MKJS', 'Montego Bay, Jamaika'),
(150, 'MCO', 'KMCO', 'Orlando, USA'),
(151, 'MCT', 'OOMS', 'Muscat, Oman'),
(152, 'MEX', 'MMMX', 'Mexico City, Mexiko'),
(153, 'MIA', 'KMIA', 'Miami, USA'),
(154, 'MLA', 'LMML', 'Malta, Malta'),
(155, 'MLE', 'VRMM', 'Male, Malediven'),
(156, 'MRS', 'LFML', 'Marseille, Frankreich'),
(157, 'MRU', 'FIMP', 'Mauritius, Mauritius'),
(158, 'MSQ', 'UMMS', 'Minsk, Weißrussland'),
(159, 'MUC', 'EDDM', 'München, Deutschland'),
(160, 'MXP', 'LIMC', 'Mailand-Malpensa, Italien'),
(161, 'NAP', 'LIRN', 'Neapel, Italien'),
(162, 'NBE', 'DTNZ', 'Enfidha, Tunesien'),
(163, 'NBO', 'HKJK', 'Nairobi, Kenia'),
(164, 'NCE', 'LFMN', 'Nizza, Frankreich'),
(165, 'NDR', 'GMFN', 'Nador, Marokko'),
(166, 'NGO', 'RJGG', 'Nagoya, Japan'),
(167, 'NKG', 'ZSNJ', 'Nanking, China'),
(168, 'NRT', 'RJAA', 'Tokio Narita, Japan'),
(169, 'NUE', 'EDDN', 'Nürnberg, Deutschland'),
(170, 'OPO', 'LPPR', 'Porto, Portugal'),
(171, 'ORD', 'KORD', 'Chicago, USA'),
(172, 'OSL', 'ENGM', 'Oslo, Norwegen'),
(173, 'OTP', 'LROP', 'Bukarest, Rumänien'),
(174, 'OVB', 'UNNT', 'Novosibirsk, Russland'),
(175, 'PEE', 'USPP', 'Perm, Russland'),
(176, 'PEK', 'ZBAA', 'Peking, China'),
(177, 'PFO', 'LCPH', 'Paphos, Zypern'),
(178, 'PHC', 'DNPO', 'Port Harcourt, Nigeria'),
(179, 'PHL', 'KPHL', 'Philadelphia, USA'),
(180, 'PMI', 'LEPA', 'Palma de Mallorca, Spanien'),
(181, 'PNQ', 'VAPO', 'Pune, Indien'),
(182, 'PNR', 'FCPP', 'Pointe Noire, Kongo'),
(183, 'POP', 'MDPP', 'Puerto Plata, Dominikan. Rep.'),
(184, 'POZ', 'EPPO', 'Poznan/Posen, Polen'),
(185, 'PRG', 'LKPR', 'Prag, Tschechien'),
(186, 'PRN', 'LYPR', 'Pristina, Serbien'),
(187, 'PTY', 'MPTO', 'Panama City, Panama'),
(188, 'PUJ', 'MDPC', 'Punta Cana, Dominikan. Rep.'),
(189, 'PVG', 'ZSPD', 'Shanghai PuDong, China'),
(190, 'REC', 'SBRF', 'Recife, Brasilien'),
(191, 'RIX', 'EVRA', 'Riga, Lettland'),
(192, 'RMF', 'HEMA', 'Marsa Alam, Ägypten'),
(193, 'ROV', 'URRR', 'Rostow, Russland'),
(194, 'RUH', 'OERK', 'Riad, Saudi-Arabien'),
(195, 'RZE', 'EPRZ', 'Rzeszow, Polen'),
(196, 'SAH', 'OYSN', 'Sanaa, Jemen'),
(197, 'SAW', 'LTFJ', 'Istanbul S-Gokcen, Türkei'),
(198, 'SCL', 'SCEL', 'Santiago de Chile, Chile'),
(199, 'SDQ', 'MDSD', 'Santo Domingo, Dominikan. Rep.'),
(200, 'SEA', 'KSEA', 'Seattle, USA'),
(201, 'SFO', 'KSFO', 'San Francisco, USA'),
(202, 'SGN', 'VVTS', 'Ho Chi Minh City, Vietnam'),
(203, 'SHE', 'ZYTX', 'Shenyang, China'),
(204, 'SIN', 'WSSS', 'Singapur, Singapur'),
(205, 'SJO', 'MROC', 'San Jose, Costa Rica'),
(206, 'SJU', 'TJSJ', 'San Juan, Puerto Rico'),
(207, 'SKG', 'LGTS', 'Thessaloniki, Griechenland'),
(208, 'SOF', 'LBSF', 'Sofia, Bulgarien'),
(209, 'SOU', 'EGHI', 'Southampton, Großbritannien'),
(210, 'SPC', 'GCLA', 'La Palma, Spanien'),
(211, 'SPU', 'LDSP', 'Split, Kroatien'),
(212, 'SSA', 'SBSV', 'Salvador, Brasilien'),
(213, 'SSG', 'FGSL', 'Malabo, Äquator.-Guinea'),
(214, 'SSH', 'HESH', 'Sharm El Sheik, Ägypten'),
(215, 'STR', 'EDDS', 'Stuttgart, Deutschland'),
(216, 'SVG', 'ENZV', 'Stavanger, Norwegen'),
(217, 'SVO', 'UUEE', 'Moskau-Sheremetyevo, Russland'),
(218, 'SVX', 'USSS', 'Ekaterinburg, Russland'),
(219, 'SYD', 'YSSY', 'Sydney, Australien'),
(220, 'SZG', 'LOWS', 'Salzburg, Österreich'),
(221, 'TAB', 'TTCP', 'Tobago, Trinidad Tobago'),
(222, 'TAS', 'UTTT', 'Taschkent, Usbekistan'),
(223, 'TFS', 'GCTS', 'Teneriffa-Sur Reina, Spanien'),
(224, 'TGD', 'LYPG', 'Podgorica, Montenegro'),
(225, 'TIP', 'HLLT', 'Tripolis, Libyen'),
(226, 'TLL', 'EETN', 'Tallinn, Estland'),
(227, 'TLS', 'LFBO', 'Toulouse, Frankreich'),
(228, 'TLV', 'LLBG', 'Tel Aviv, Israel'),
(229, 'TPE', 'RCTP', 'Taipeh, Taiwan'),
(230, 'TRN', 'LIMF', 'Turin, Italien'),
(231, 'TSE', 'UACC', 'Astana, Kasachstan'),
(232, 'TUN', 'DTTA', 'Tunis, Tunesien'),
(233, 'TXL', 'EDDT', 'Berlin-Tegel, Deutschland'),
(234, 'UVF', 'TLPL', 'Saint Lucia, Saint Lucia'),
(235, 'VCE', 'LIPZ', 'Venedig, Italien'),
(236, 'VIE', 'LOWW', 'Wien, Österreich'),
(237, 'VNO', 'EYVI', 'Vilnius, Litauen'),
(238, 'VRA', 'MUVR', 'Varadero, Kuba'),
(239, 'VRN', 'LIPX', 'Verona, Italien'),
(240, 'WAW', 'EPWA', 'Warschau, Polen'),
(241, 'WDH', 'FYWH', 'Windhuk, Namibia'),
(242, 'WRO', 'EPWR', 'Wroclaw/Breslau, Polen'),
(243, 'XRY', 'LEJR', 'Jerez de la Frontera, Spanien'),
(244, 'YOW', 'CYOW', 'Ottawa, Kanada'),
(245, 'YUL', 'CYUL', 'Montreal-Trudeau, Kanada'),
(246, 'YVR', 'CYVR', 'Vancouver, Kanada'),
(247, 'YYC', 'CYYC', 'Calgary, Kanada'),
(248, 'YYZ', 'CYYZ', 'Toronto, Kanada'),
(249, 'ZAD', 'LDZD', 'Zadar, Kroatien'),
(250, 'ZAG', 'LDZA', 'Zagreb, Kroatien'),
(251, 'ZRH', 'LSZH', 'Zürich, Schweiz'),
(252, 'SEZ', 'FSIA', 'Mahe, Seychellen'),
(253, 'AJR', 'ESNX', 'Arvidsjaur, Schweden'),
(254, 'BIA', 'LFKB', 'Bastia, Frankreich'),
(255, 'PDL', 'LPPD', 'Ponta Delgada, Portugal'),
(256, 'GLA', 'EGPF', 'Glasgow, Großbritannien'),
(257, 'ANU', 'TAPA', 'Antigua, Antigua'),
(258, 'RKT', 'OMRK', 'Ras al Khaymah, Ver.Arab.Emirate'),
(259, 'COK', 'VOCI', 'Cochin, Indien'),
(260, 'ZNZ', 'HTZA', 'Sansibar, Tansania'),
(261, 'CGN', 'EDDK', 'Köln Bonn, Deutschland'),
(262, 'VKO', 'UUWW', 'Moskau-Vnukovo, Russland'),
(263, 'GOA', 'LIMJ', 'Genua, Italien'),
(264, 'TRD', 'ENVA', 'Trondheim, Norwegen'),
(265, 'PMO', 'LICJ', 'Palermo, Italien'),
(266, 'OLB', 'LIEO', 'Olbia, Italien'),
(267, 'KUF', 'UWWW', 'Samara, Russland'),
(268, 'GOJ', 'UWGG', 'N. Novgorod, Russland'),
(269, 'CLE', 'KCLE', 'Cleveland, USA'),
(270, 'GWT', 'EDXW', 'Westerland, Deutschland'),
(271, 'VAR', 'LBWN', 'Varna, Bulgarien'),
(272, 'PHX', 'KPHX', 'Phoenix, USA'),
(273, 'ORN', 'DAOO', 'Oran, Algerien'),
(274, 'SAN', 'KSAN', 'San Diego-Lindberg, USA'),
(275, 'TAO', 'ZSQD', 'Qingdao, China'),
(276, 'SZF', 'LTFH', 'Samsun-Carsamba, Türkei'),
(277, 'RDU', 'KRDU', 'Raleigh/Durham, USA'),
(278, 'TBS', 'UGTB', 'Tbilisi, Georgien'),
(279, 'QSH', 'DUMI', 'Seeheim, Deutschland'),
(280, 'ALC', 'LEAL', 'Alicante, Spanien'),
(281, 'MAO', 'SBEG', 'Manaus, Brasilien'),
(282, 'HER', 'LGIR', 'Heraklion, Griechenland'),
(283, 'RLG', 'ETNL', 'Rostock Laage, Deutschland'),
(284, 'ERF', 'EDDE', 'Erfurt, Deutschland'),
(285, 'SOB', 'LHSM', 'Sarmellek, Ungarn'),
(286, 'BSB', 'SBBR', 'Brasilia, Brasilien'),
(287, 'DLM', 'LTBS', 'Dalaman, Türkei'),
(288, 'TCE', 'LRTC', 'Tulcea Cataloi, Rumänien'),
(289, 'RHO', 'LGRP', 'Rhodos, Griechenland'),
(290, 'KGS', 'LGKO', 'Kos, Griechenland'),
(291, 'UGC', 'UTNU', 'Urgench, Usbekistan'),
(292, 'CFU', 'LGKR', 'Kerkyra, Griechenland'),
(293, 'ANC', 'PANC', 'Anchorage, USA'),
(294, 'IBZ', 'LEIB', 'Ibiza, Spanien'),
(295, 'YHZ', 'CYHZ', 'Halifax, Kanada'),
(296, 'REU', 'LERS', 'Reus, Spanien'),
(297, 'PAE', 'KPAE', 'Everett, USA'),
(298, 'SID', 'GVAC', 'Sal, Kap Verde'),
(299, 'VLC', 'LEVC', 'Valencia, Spanien'),
(300, 'BJV', 'LTFE', 'Bodrum, Türkei'),
(301, 'BVC', 'GVBA', 'Boa Vista, Kap Verde'),
(302, 'GPA', 'LGRX', 'Patras, Griechenland'),
(303, 'PVK', 'LGPZ', 'Preveza/Lefkas, Griechenland'),
(304, 'SIP', 'UKFF', 'Simferopol, Ukraine'),
(305, 'BOJ', 'LBBG', 'Burgas, Bulgarien'),
(306, 'HDF', 'EDAH', 'Heringsdorf, Deutschland'),
(307, 'RJK', 'LDRI', 'Rijeka, Kroatien'),
(308, 'MLX', 'LTAT', 'Malatya, Türkei'),
(309, 'JER', 'EGJJ', 'Jersey, Großbritannien'),
(310, 'SUF', 'LICA', 'Lamezia Terme, Italien'),
(311, 'MAH', 'LEMH', 'Menorca, Spanien'),
(312, 'SMI', 'LGSM', 'Samos, Griechenland'),
(313, 'CHQ', 'LGSA', 'Chania, Griechenland'),
(314, 'FRA', 'EDDF', 'Frankfurt, Deutschland'),
(315, 'JTR', 'LGSR', 'Santorini, Griechenland'),
(316, 'MIR', 'DTMB', 'Monastir, Tunesien'),
(317, 'KVA', 'LGKV', 'Kavala, Griechenland'),
(318, 'ZTH', 'LGZA', 'Zakynthos, Griechenland'),
(319, 'JMK', 'LGMK', 'Mykonos, Griechenland'),
(320, 'LDE', 'LFBT', 'Lourdes, Frankreich'),
(321, 'YXY', 'CYXY', 'Whitehorse, Kanada'),
(322, 'EZS', 'LTCA', 'Elazig, Türkei'),
(323, 'JNB', 'FAOR', 'Johannesburg, Südafrika'),
(324, 'BRS', 'EGGD', 'Bristol, Großbritannien'),
(325, 'BGW', 'ORBI', 'Bagdad, Irak'),
(326, 'SXB', 'LFST', 'Strassburg, Frankreich'),
(327, 'BWI', 'KBWI', 'Baltimore-Washington, USA'),
(328, 'NBE', 'DTNH', 'Enfidha, Tunesien'),
(329, 'CTU', 'ZUUU', 'Chengdu, China'),
(330, 'TIV', 'LYTV', 'Tivat, Montenegro'),
(331, 'PUY', 'LDPL', 'Pula, Kroatien'),
(332, 'NDR', 'GMMW', 'Nador, Marokko'),
(333, 'CAS', 'GMMC', 'Casablanca / Anfa, Marokko'),
(334, 'TZX', 'LTCG', 'Trabzon, Türkei'),
(335, 'FAI', 'PAFA', 'Fairbanks, USA'),
(336, 'KSF', 'EDVK', 'Kassel, Deutschland'),
(337, 'SCN', 'EDDR', 'Saarbrücken, Deutschland'),
(338, 'BTS', 'LZIB', 'Bratislava, Slowakei'),
(339, 'STN', 'EGSS', 'London-Stansted, Großbritannien'),
(340, 'GCI', 'EGJB', 'Guernsey, Großbritannien'),
(341, 'SXF', 'EDDB', 'Berlin-Schönefeld, Deutschland'),
(342, 'LPL', 'EGGP', 'Liverpool, Großbritannien'),
(343, 'RTM', 'EHRD', 'Rotterdam, Niederlande'),
(344, 'LTN', 'EGGW', 'London-Luton Airport, Großbritannien'),
(345, 'QEF', 'EDFE', 'Egelsbach, Deutschland'),
(346, 'GYD', 'UBBB', 'Baku, Aserbaidschan'),
(347, 'FAE', 'EKVG', 'Vagar, Dänemark'),
(348, 'QMZ', 'EDFZ', 'Mainz Finthen, Deutschland'),
(349, 'LIL', 'LFQQ', 'Lille, Frankreich'),
(350, 'BOD', 'LFBD', 'Bordeaux, Frankreich'),
(351, 'LBV', 'FOOL', 'Libreville, Gabun'),
(352, 'BDS', 'LIBR', 'Brindisi, Italien'),
(353, 'GZP', 'LTFG', 'Gazipasa / Alanya, Türkei'),
(354, 'PAD', 'EDLP', 'Paderborn/Lippstadt, Deutschland'),
(355, 'MED', 'OEMA', 'Medina, Saudi-Arabien'),
(356, 'CND', 'LRCK', 'Konstanza, Rumänien'),
(357, 'RTW', 'UWSS', 'Saratov, Russland'),
(358, 'KLX', 'LGKL', 'Kalamata, Griechenland'),
(359, 'LWO', 'UKLL', 'Lvov, Ukraine'),
(360, 'HYD', 'VOHS', 'Hyderabad, Indien'),
(361, 'KUN', 'EYKA', 'Kaunas, Litauen'),
(362, 'AAA', 'AAAA', 'Ausland, FICTITIOUSPOINTS'),
(363, 'SFJ', 'BGSF', 'Kangerlussuaq, Grönland'),
(364, 'SVQ', 'LEZL', 'Sevilla, Spanien'),
(365, 'BVA', 'LFOB', 'Paris-Beauvais, Frankreich'),
(366, 'GRX', 'LEGR', 'Granada, Spanien'),
(367, 'AVN', 'LFMV', 'Avignon, Frankreich'),
(368, 'RAK', 'GMMX', 'Marrakesch, Marokko'),
(369, 'SGE', 'EDGS', 'Siegen, Deutschland'),
(370, 'ZAZ', 'LEZG', 'Zaragoza, Spanien'),
(371, 'SHJ', 'OMSJ', 'Sharjah, Ver.Arab.Emirate'),
(372, 'RGN', 'VYYY', 'Yangon, Myanmar'),
(373, 'REP', 'VDSR', 'Siem Reap, Kambodscha'),
(374, 'KRR', 'URKK', 'Krasnodar, Russland'),
(375, 'JKG', 'ESGJ', 'Jonkoping, Schweden'),
(376, 'CAG', 'LIEE', 'Cagliari, Italien'),
(377, 'EVN', 'UDYZ', 'Eriwan, Armenien'),
(378, 'UFA', 'UWUU', 'Ufa, Russland'),
(379, 'GOI', 'VOGO', 'Goa, Indien'),
(380, 'RVN', 'EFRO', 'Rovaniemi, Finnland'),
(381, 'TRS', 'LIPQ', 'Triest, Italien'),
(382, 'KTT', 'EFKT', 'Kittila, Finnland'),
(383, 'MEL', 'YMML', 'Melbourne, Australien'),
(384, 'DTM', 'EDLW', 'Dortmund, Deutschland'),
(385, 'PNA', 'LEPP', 'Pamplona, Spanien'),
(386, 'VLL', 'LEVD', 'Valladolid, Spanien'),
(387, 'TSR', 'LRTR', 'Timisoara, Rumänien'),
(388, 'BRN', 'LSZB', 'Bern, Schweiz'),
(389, 'TTU', 'GMTN', 'Tetouan, Marokko'),
(390, 'SLC', 'KSLC', 'Salt Lake City, USA'),
(391, 'MSP', 'KMSP', 'Minneapolis, USA'),
(392, 'SJJ', 'LQSA', 'Sarajevo, Bosnien-Herzegow'),
(393, 'TFN', 'GCXO', 'Teneriffa-Norte, Spanien'),
(394, 'TCP', 'HETB', 'Taba, Ägypten'),
(395, 'IGS', 'ETSI', 'Ingolstadt-Manching, Deutschland'),
(396, 'AZS', 'MDAB', 'Samana, Dominikan. Rep.'),
(397, 'DWC', 'OMDW', 'Dubai-Al Maktoum, Ver.Arab.Emirate'),
(398, 'IND', 'KIND', 'Indianapolis, USA'),
(399, 'OSI', 'LDOS', 'Osijek, Kroatien'),
(400, 'NJF', 'ORNI', 'Al Najaf, Irak'),
(401, 'PTP', 'TFFR', 'Pointe a Pitre, Guadeloupe'),
(402, 'DNZ', 'LTAY', 'Denizli, Türkei'),
(403, 'ACA', 'MMAA', 'Acapulco, Mexiko'),
(404, 'MJV', 'LELC', 'Murcia, Spanien'),
(405, 'AER', 'URSS', 'Sochi, Russland'),
(406, 'LIM', 'SPIM', 'Lima, Peru'),
(407, 'LME', 'LFRM', 'Le Mans, Frankreich'),
(409, 'HHN', 'EDFH', 'Frankfurt-Hahn, Deutschland'),
(410, 'BQN', 'TJBQ', 'Aguadilla, Puerto Rico'),
(411, 'CKG', 'ZUCK', 'Chongqing, China'),
(412, 'CVT', 'EGBE', 'Coventry'),
(413, 'CUR', 'TNCC', 'Curaçao'),
(414, 'CWB', 'SBCT', 'Curitiba, Brasilien'),
(415, 'DKR', 'GOOY', 'Dakar, Senegal'),
(416, 'DAC', 'VGHS', 'Dhaka, Bangladesh'),
(417, 'GDL', 'MMGL', 'Guadalajara, Mexiko'),
(418, 'KAN', 'DNKN', 'Kano, Nigeria'),
(419, 'KJA', 'UNKL', 'Krasnojarsk, Russland'),
(420, 'MEM', 'KMEM', 'Memphis, USA'),
(421, 'MVD', 'SUMU', 'Montevideo, Uruguay'),
(422, 'UIO', 'SEQM', 'Quito, Ecuador'),
(423, 'VCP', 'SBKP', 'São Paulo-Viracopos, Brasilien'),
(424, 'HFE', 'ZSOF', 'Hefei/Luogang, China'),
(425, 'TIA', 'LATI', 'Tirana, Albanien'),
(426, 'XFW', 'EDHI', 'Hamburg-Finkenwerder, Deutschland'),
(428, 'BRI', 'LIBD', 'Bari, Italien'),
(429, 'MPL', 'LFMT', 'Montpellier, Frankreich'),
(430, 'KSD', 'ESOK', 'Karlstad, Schweden'),
(431, 'CGK', 'WIII', 'Jakarta, Indonesien'),
(432, 'DOH', 'OTHH', 'Doha, Katar'),
(433, 'PEG', 'LIRZ', 'Perugia, Italien'),
(434, 'ULN', 'ZMUB', 'Ulan Bator, Mongolei'),
(435, 'FOR', 'SBFZ', 'Fortaleza, Brasilien'),
(436, 'LUZ', 'EPLB', 'Lublin, Polen'),
(437, 'ZQW', 'EDRZ', 'Zweibrücken, Deutschland'),
(438, 'YFB', 'CYFB', 'Iqaluit, Kanada'),
(439, 'OUD', 'GMFO', 'Oujda, Marokko'),
(440, 'QRR', 'EDRR', 'Rundflug, Deutschland'),
(441, 'SLL', 'OOSA', 'Salalah, Oman'),
(442, 'ORB', 'ESOE', 'Oerebro, Schweden'),
(443, 'GND', 'TGPY', 'Grenada, Grenada'),
(444, 'VGO', 'LEVX', 'Vigo, Spanien'),
(445, 'FKB', 'EDSB', 'Karlsruhe-Söllingen, Deutschland'),
(446, 'NAS', 'MYNN', 'Nassau, Bahamas'),
(447, 'ASW', 'HESN', 'Assuan, Ägypten'),
(448, 'YEI', 'LTBR', 'Bursa, Türkei'),
(449, 'OAI', 'OAIX', 'Bagram, Afghanistan'),
(450, 'LBG', 'LFPB', 'Paris-Le Bourget, Frankreich'),
(451, 'GRQ', 'EHGG', 'Groningen, Niederlande'),
(452, 'IVL', 'EFIV', 'Ivalo, Finnland'),
(453, 'NTE', 'LFRS', 'Nantes, Frankreich'),
(454, 'SKP', 'LWSK', 'Skopje, Mazedonien'),
(455, 'BZG', 'EPBY', 'Bydgoszcz, Polen'),
(456, 'AAL', 'EKYT', 'Aalborg, Dänemark'),
(457, 'VIT', 'LEVT', 'Vitoria, Spanien'),
(458, 'DHF', 'OMAM', 'Abu Dhabi-Al Dhafra, Ver.Arab.Emirate'),
(459, 'RIV', 'KRIV', 'Riverside, USA'),
(460, 'LEN', 'LELN', 'Leon, Spanien'),
(461, 'SLM', 'LESA', 'Salamanca, Spanien'),
(462, 'OSR', 'LKMT', 'Ostrava, Tschechien'),
(463, 'LGG', 'EBLG', 'Liege, Belgien'),
(464, 'NGB', 'ZSNB', 'Ningbo, China'),
(465, 'TUF', 'LFOT', 'Tours, Frankreich'),
(466, 'CSY', 'UWKS', 'Cheboksary, Russland'),
(467, 'PVD', 'KPVD', 'Providence, USA'),
(468, 'PDX', 'KPDX', 'Portland, USA'),
(469, 'VDB', 'ENFG', 'Fagernes, Norwegen'),
(470, 'QZX', 'EQZX', 'Teststation, Deutschland'),
(471, 'HBE', 'HEBA', 'Borg El Arab, Ägypten'),
(472, 'UUD', 'UIUU', 'Ulan-Ude, Russland'),
(473, 'ILZ', 'LZZI', 'Zilina, Slowakei'),
(474, 'LUG', 'LSZA', 'Lugano, Schweiz'),
(475, 'BDU', 'ENDU', 'Bardufoss, Norwegen'),
(476, 'ANR', 'EBAW', 'Antwerpen, Belgien'),
(477, 'TPA', 'KTPA', 'Tampa, USA'),
(478, 'RSW', 'KRSW', 'Fort Myers, USA'),
(479, 'TSN', 'ZBTJ', 'Tianjin, China'),
(480, 'NVI', 'UTSA', 'Navoi, Usbekistan'),
(481, 'MNL', 'RPLL', 'Manila, Philippinen'),
(482, 'CSX', 'ZGHA', 'Changsha, China'),
(483, 'TEQ', 'LTBU', 'Tekidag, Türkei'),
(484, 'KJK', 'EBKT', 'Kortrijk-Wevelgem International'),
(486, 'SNU', 'MUSC', 'Santa Clara-Abel Santamaria'),
(487, 'LHW', 'ZLLL', 'Lanzhou Zhongchuan'),
(488, '???', '????', ''),
(489, 'FDF', 'TFFF', 'Fort-de France  Martinique A.Cesaire'),
(490, 'PSA', 'LIRP', 'Pisa-Galileo Galilei International'),
(491, 'SNN', 'EINN', 'Shannon'),
(492, 'INV', 'EGPE', 'Inverness'),
(493, 'SIR', 'LSGS', 'Sion'),
(494, 'SEN', 'EGMC', 'London-Southend'),
(495, 'CEG', 'EGNR', 'Chester-Hawarden'),
(496, 'BQH', 'EGKB', 'London-Biggin Hill'),
(497, 'CFE', 'LFLC', 'Clermont-Ferrand-Auvergne'),
(498, 'FAB', 'EGLF', 'Farnborough'),
(499, 'BRQ', 'LKTB', 'Brünn-Turany'),
(500, 'ODE', 'EKOD', 'Odense-Hans Christian Andersen'),
(501, 'QMN', 'EDTM', 'Mengen'),
(502, 'OXF', 'EGTK', 'Oxford'),
(503, 'LLA', 'ESPA', 'Lulea-Kallax'),
(504, 'TSF', 'LIPH', 'Venice-Treviso Sant\'Angelo'),
(505, 'ACH', 'LSZR', 'Altenrhein'),
(506, 'BWE', 'EDVE', 'Braunschweig/Wolfsburg'),
(507, 'MGL', 'EDLN', 'Mönchengladbach'),
(508, 'EXT', 'EGTE', 'Exeter-International'),
(509, 'NCL', 'EGNT', 'Newcastle-International'),
(510, 'BYJ', 'LPBJ', 'Beja'),
(511, 'ADJ', 'OJAM', 'Amman-Marka International'),
(512, 'IEV', 'UKKK', 'Kiew-Zhuliany International'),
(513, 'ZHI', 'LSZG', 'Grenchen'),
(514, 'RNS', 'LFRN', 'Rennes-Saint-Jacques'),
(515, 'MST', 'EHBK', 'Maastricht/Aachen'),
(516, 'SYX', 'ZJSY', 'Sanya-Phoenix International'),
(517, 'NYO', 'ESKN', 'Stockholm-Skavsta'),
(518, 'OBF', 'EDMO', 'Oberpfaffenhofen'),
(519, 'EIN', 'EHEH', 'Eindhoven'),
(520, 'BZV', 'FCBB', 'Brazzaville-Maya-Maya'),
(521, 'TLN', 'LFTH', 'Toulon-Hyères'),
(522, 'TRF', 'ENTO', 'Sandefjord-Torp'),
(523, 'PIK', 'EGPK', 'Glasgow-Prestwick'),
(524, 'LBA', 'EGNM', 'Leeds/Bradford-International'),
(525, 'UGN', 'KUGN', 'Waukegan'),
(526, 'CIA', 'LIRA', 'Rom-Ciampino'),
(527, 'HPN', 'KHPN', 'Westchester County'),
(528, 'BMA', 'ESSB', 'Stockholm-Bromma'),
(529, 'AKH', 'OEKJ', 'Al Kharj-Prince Sultan Air Base'),
(530, 'AGH', 'ESTA', 'Angelholm-Helsingborg'),
(531, 'FMM', 'EDJA', 'Memmingen-Allgäu'),
(532, 'BOH', 'EGHH', 'Bournemouth'),
(533, 'LYX', 'EGMD', 'Lydd-London Ashford'),
(534, 'ZQC', 'EDRY', 'Speyer'),
(535, 'CMF', 'LFLB', 'Chambery/Aix-les-Bains'),
(536, 'PMF', 'LIMP', 'Parma-Giuseppe Verdi'),
(537, 'DSA', 'EGCN', 'Doncaster Sheffield'),
(538, 'OST', 'EBOS', 'Ostende/Brügge-International'),
(539, 'ABJ', 'DIAP', 'Abidjan-Felix Houphouet-Boigny International'),
(540, 'FIH', 'FZAA', 'Kinshasa-N\'Djili International'),
(541, 'KGL', 'HRYR', 'Kigali-International'),
(542, 'AGB', 'EDMA', 'Augsburg Airport'),
(543, 'OUA', 'DFFD', 'Ouagadougou'),
(544, 'GNY', 'LTCS', 'Sanliurfa- GAP'),
(545, 'MMX', 'ESMS', 'Malmo'),
(546, 'TTN', 'KTTN', 'Trenton-Mercer'),
(547, 'KLV', 'LKKV', 'Karlovy Vary'),
(548, 'XMN', 'ZSAM', 'Xiamen-Gaoqi International'),
(549, 'AOI', 'LIPY', 'Ancona-Falconara'),
(550, 'LHA', 'EDTL', 'Lahr-Black Forest'),
(551, 'VCV', 'KVCV', 'Victorville'),
(552, 'CEQ', 'LFMD', 'Cannes-Mandelieu'),
(553, 'LBC', 'EDHL', 'Lübeck'),
(554, 'PWK', 'KPWK', 'Chicago-Executive'),
(555, 'GRO', 'LEGE', 'Gerona-Costa Brava'),
(556, 'NRN', 'EDLV', 'Niederrhein'),
(557, 'RKE', 'EKRK', 'Kopenhagen-Roskilde'),
(558, 'JSI', 'LGSK', 'Skiathos-Alexandros Papadiamantis'),
(559, 'NWI', 'EGSH', 'Norwich-International'),
(560, 'NHT', 'EGWU', 'Northolt'),
(561, 'SZX', 'ZGSZ', 'Shenzhen-Bao\'an International'),
(562, 'IOM', 'EGNS', 'Isle of Man'),
(563, 'BGR', 'KBGR', 'Bangor-International'),
(564, 'BZO', 'LIPB', 'Bozen-Dolomiti'),
(565, 'BZR', 'LFMU', 'Beziers-Cap d\'Agde'),
(566, 'DOL', 'LFRG', 'Deauville-Saint-Gatien'),
(567, 'LYN', 'LFLY', 'Lyon-Bron'),
(568, 'FNA', 'GFLL', 'Freetown-Lungi International'),
(569, 'KIR', 'EIKY', 'Kerry'),
(570, 'OVD', 'LEAS', 'Asturias'),
(571, 'LCK', 'KLCK', 'Columbus-Rickenbacker International'),
(572, 'QKL', 'EDKK', 'Köln Hauptbahnhof'),
(573, 'AUS', 'KAUS', 'Austin-Robert Mueller Municipal'),
(574, 'SJC', 'KSJC', 'San Jose-Norman Y. Mineta International'),
(575, 'BLK', 'EGNH', 'Blackpool-International'),
(576, 'SGD', 'EKSB', 'Sonderborg'),
(577, 'BXO', 'LSZC', 'Buochs'),
(578, 'CGO', 'ZHCC', 'Zhengzhou-Xinzheng International'),
(579, 'TNG', 'GMTT', 'Tanger'),
(580, 'PXO', 'LPPS', 'Porto Santo Madeira'),
(581, 'VBS', 'LIPO', 'Brescia-Montichiari'),
(591, 'GRS', 'LIRS', 'Grosetto-Corrado Baccarini'),
(594, 'AZI', 'OMAD', 'Abu Dhabi-Al Bateen Executive'),
(596, 'MME', 'EGNV', 'Durham-Tees Valley'),
(597, 'PAP', 'MTPP', 'Port au Prince-Toussaint Louverture Internati'),
(599, 'KYA', 'LTAN', 'Konya'),
(608, 'CLY', 'LFKC', 'Calvi-Sainte-Catherine'),
(609, 'NQY', 'EGHQ', 'Newquay'),
(610, 'MHG', 'EDFM', 'Mannheim-City Airport'),
(611, 'ORY', 'LFPO', 'Paris-Orly'),
(612, 'EAS', 'LESO', 'San Sebastian'),
(613, 'VXO', 'ESMX', 'Vaxjo'),
(614, 'SBK', 'LFRT', 'Saint-Brieuc-Armor'),
(615, 'XXX', 'XXXX', 'Cancelled'),
(616, 'YQX', 'CYQX', 'Gander-International'),
(617, 'GIB', 'LXGB', 'Gibraltar'),
(620, 'NIM', 'DRRN', 'Niamey-Diori Hamani International'),
(621, 'RMI', 'LIPR', 'Rimini-Federico Fellini International'),
(622, 'HAD', 'ESMT', 'Halmstad'),
(623, 'YHM', 'CYHM', 'Hamilton-John C. Munro Hamilton International'),
(624, 'TOS', 'ENTC', 'Tromso-Langnes'),
(625, 'BIQ', 'LFBZ', 'Biarritz-Anglet Bayonne'),
(630, 'GBB', 'UBBQ', 'Gabala'),
(631, 'CMR', 'LFGA', 'Colmar-Houssen'),
(632, 'KMG', 'ZPPP', 'Kunming'),
(633, 'MLH', 'LFGB', 'Mulhouse-Basel-Mulhouse-Freiburg EuroAirport'),
(634, 'KGF', 'UAKK', 'Karaganda-Sary-Arka'),
(635, 'SKS', 'EKSP', 'Vojens-Skrydstrup'),
(636, 'TAY', 'EETU', 'Tartu'),
(637, 'SMV', 'LSZS', 'St.Moritz-Engadin'),
(638, 'SZL', 'KSZL', 'Whiteman Air Force Base'),
(639, 'XCR', 'LFOK', 'Chalons-Vatry');

TRUNCATE `visits`;

INSERT INTO `visits`(`aircraft`, `num`, `current`)
SELECT
	`flights`.`aircraft` AS `aircraft`,
	COUNT(`flights`.`scheduled`) AS `num`,
	MAX(`flights`.`scheduled`) AS `current`
FROM
(
	SELECT `direction`, `scheduled`, `aircraft`
	FROM `flights`
	WHERE `aircraft` IS NOT NULL

	UNION ALL

	SELECT `direction`,`scheduled`, `aircraft`
	FROM `history`
	WHERE `aircraft` IS NOT NULL
) AS `flights`
LEFT JOIN `aircrafts`
	   ON `aircrafts`.`id`=`flights`.`aircraft`
WHERE `direction`='arrival'
GROUP BY `aircraft`;
